### ISSUE TITLE
"Insufficient gas" is reported when some contracts are deployed

### ISSUE THREAD

**Issue by kw805** [PlatONnetwork/PlatON-Go#1018]
Hi there,

please note that this is an issue tracker reserved for bug reports and feature requests.

#### System information

PlatON version: `platon version`
OS & Version: Windows/Linux/OSX
Commit hash : (if `develop`)

#### Backtrace

````
[backtrace]
````

**Comment by zjsunzone** [comment]
For this kind of error, the sender's balance is generally insufficient.

**Comment by zjsunzone** [comment]
If the library is referenced in the contract, please refer to: https://solidity.readthedocs.io/en/v0.5.13/using-the-compiler.html
