### ISSUE TITLE
Get block hash error in contract

### ISSUE THREAD

**Issue by kw805** [PlatONnetwork/PlatON-Go#1019]
Hi there,

please note that this is an issue tracker reserved for bug reports and feature requests.

#### System information

PlatON version: `platon version`
OS & Version: Windows/Linux/OSX
Commit hash : (if `develop`)

#### Backtrace

````
[backtrace]
````

**Comment by zjsunzone** [comment]
Is there a more detailed log.

**Comment by zjsunzone** [comment]
The problem was caused by the consensus algorithm switching from POW to CBFT.  fixed: #984
