### ISSUE TITLE
solidity calls sha256 function, insufficient gas

### ISSUE THREAD

**Issue by kw805** [PlatONnetwork/PlatON-Go#1020]
Hi there,

please note that this is an issue tracker reserved for bug reports and feature requests.

#### System information

PlatON version: `platon version`
OS & Version: Windows/Linux/OSX
Commit hash : (if `develop`)

#### Backtrace

````
[backtrace]
````

**Comment by zjsunzone** [comment]
Maybe using the old instruction set.
