### ISSUE TITLE
When a node withdraws a staking, the chain does not return the block height or period that was actually revoked

### ISSUE THREAD

**Issue by shinnng** [PlatONnetwork/PlatON-Go#1039]
When a node withdraws a staking, the chain does not return the block height or period that was actually revoked, and the application does not prompt for it.If the user is not familiar with the rules of the system, he may think it is a real time undo and then close the node, resulting in the node being penalized for zero outblock rate.

在节点撤销质押时，底层没有返回实际撤销的块高或周期，同时周边也没有相应提示。如果用户不熟悉系统规则，可能会以为是实时撤销，然后关闭节点，导致节点因为零出块率被处罚。

**Comment by benbaley** [comment]
This needs to be discussed

**Comment by benbaley** [comment]
The blocknumber has already contained in tx's receipt, and sdk can give the period according the blocknumber.
