### ISSUE TITLE
When revoking the entrustment, the effective and ineffective amounts of the entrustment information are not updated

### ISSUE THREAD

**Issue by qiusese** [PlatONnetwork/PlatON-Go#1040]
PlatON version: `platon 0.7.6`
OS & Version: Windows/Linux/OSX

1、The node is still in a period of hesitation
2、Cancel the delegation in the same cycle after being entrusted
3、There is no record for calculating the unit price of reward

**Comment by WeiLoy** [comment]
The node is still in the hesitation period. After being commissioned, the execution of the withdrawal of the commission is performed in the same cycle, and then the unit price data of the calculation of the reward is not available. As a result, the validity and non-effective amount of the commission information is not updated when the commission is cancelled.

**Comment by benbaley** [comment]
close by done
