### ISSUE TITLE
Total node commission returns are not as expected

### ISSUE THREAD

**Issue by awake006** [PlatONnetwork/PlatON-Go#1041]
Hi there,

Total node commission returns are not as expected

#### System information

PlatON version: `0.7.6`
OS & Version: Windows/Linux/OSX
Commit hash :c402b1d25a9787bc2e06aa5a00f9a21d62a6eb13

When I commission a node and become a verification node, when this settlement period ends, the entrusted revenue of the query node is not as expected

Number of consensus nodes: 4
Dividend ratio: 1000

The entrusted enquiry income is: 140222321925133689839572
Expected income: 271680748729946524064170
Expected return = (Pledged reward + block reward * number of blocks) * 1000/10000

````
[backtrace]
````

**Comment by cheng762** [comment]
This is because  cal DelegateRewardPer use gvon，but cal reward not use gvon，Units are inconsistent，have fix in latest version
