### ISSUE TITLE
The gas is insufficient when the dividend reward interface is transferred, but the transaction can be linked

### ISSUE THREAD

**Issue by qiusese** [PlatONnetwork/PlatON-Go#1044]
PlatON version: `platon 0.7.6`
OS & Version: Windows/Linux/OSX

1、Estimating gas with non commissioned address
2、Send transaction with insufficient gas in the entrusted address
3、Transaction receipt is returned on the transaction chain, but the transaction is not executed

**Comment by benbaley** [comment]
This is what it's been desined to
