### ISSUE TITLE
 Stress test contract interface with the generated empty wallet, causing the system to crash

### ISSUE THREAD

**Issue by zhangrongjin** [PlatONnetwork/PlatON-Go#1045]
Hi there,

Stress test contract interface with the generated empty wallet, causing the system to crash

#### System information

PlatON version: `0.7.5.0`
OS & Version: Linux
Commit hash : 0b1494

#### Backtrace

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x6892f7]

goroutine 215540 [running]:
container/list.(*List).remove(...)
	/home/juzix/source/go/go/src/container/list/list.go:110
container/list.(*List).MoveToFront(0xc0025dad80, 0xc00ffa8180)
	/home/juzix/source/go/go/src/container/list/list.go:173 +0x47
github.com/PlatONnetwork/PlatON-Go/trie.(*LRU).Get(0xc0025d8540, 0xc043e47b28, 0x20, 0x1f61020, 0x1270d69, 0x8, 0x48340e)
	/home/juzix/source/PlatON-Go/build/_workspace/src/github.com/PlatONnetwork/PlatON-Go/trie/bigcache.go:88 +0x81
github.com/PlatONnetwork/PlatON-Go/trie.(*BigCache).Get(0xc0004dc320, 0xc043e47b28, 0x20, 0x20, 0xc043e47b28, 0x20, 0xc047091500)
	/home/juzix/source/PlatON-Go/build/_workspace/src/github.com/PlatONnetwork/PlatON-Go/trie/bigcache.go:191 +0x60
github.com/PlatONnetwork/PlatON-Go/trie.(*Database).node(0xc000252240, 0x1489ec3684e8d919, 0x1bf51d7856a4db70, 0xe8c7558a07f52cdc, 0x8bfce05d6cffd35a, 0x1, 0x0, 0x10a54e0)
	/home/juzix/source/PlatON-Go/build/_workspace/src/github.com/PlatONnetwork/PlatON-Go/trie/database.go:374 +0x3b3
github.com/PlatONnetwork/PlatON-Go/trie.(*Trie).resolveHash(0xc04e63d490, 0xc002dc9e20, 0x20, 0x20, 0xc044a9f9f0, 0x1, 0x41, 0xc044ced080, 0x5, 0xc043e47d30, ...)
	/home/juzix/source/PlatON-Go/build/_workspace/src/github.com/PlatONnetwork/PlatON-Go/trie/trie.go:440 +0x140
github.com/PlatONnetwork/PlatON-Go/trie.(*Trie).tryGet(0xc04e63d490, 0x14f5960, 0xc002651f60, 0xc044a9f9f0, 0x41, 0x41, 0x1, 0xd1fe7c35def1d695, 0xfce701d317f80949, 0xc043e47e98, ...)
	/home/juzix/source/PlatON-Go/build/_workspace/src/github.com/PlatONnetwork/PlatON-Go/trie/trie.go:173 +0xef
github.com/PlatONnetwork/PlatON-Go/trie.(*Trie).tryGet(0xc04e63d490, 0x14f3560, 0xc04e631180, 0xc044a9f9f0, 0x41, 0x41, 0x0, 0x20, 0xc04e63d4d0, 0x20, ...)
	/home/juzix/source/PlatON-Go/build/_workspace/src/github.com/PlatONnetwork/PlatON-Go/trie/trie.go:165 +0x6ce
github.com/PlatONnetwork/PlatON-Go/trie.(*Trie).TryGet(0xc04e63d490, 0xc04e63d4d0, 0x20, 0x20, 0xc04e63d4d0, 0x20, 0x20, 0x2, 0x2)
	/home/juzix/source/PlatON-Go/build/_workspace/src/github.com/PlatONnetwork/PlatON-Go/trie/trie.go:139 +0x7b
github.com/PlatONnetwork/PlatON-Go/trie.(*SecureTrie).TryGet(0xc04e63d490, 0xc043dd9040, 0x14, 0x14, 0x0, 0x0, 0x0, 0x0, 0x0)
	/home/juzix/source/PlatON-Go/build/_workspace/src/github.com/PlatONnetwork/PlatON-Go/trie/secure_trie.go:80 +0x7b
github.com/PlatONnetwork/PlatON-Go/core/state.(*StateDB).getStateObject(0xc0523b1d40, 0x10, 0x0, 0x3000000, 0xc044aadad0)
	/home/juzix/source/PlatON-Go/build/_workspace/src/github.com/PlatONnetwork/PlatON-Go/core/state/statedb.go:622 +0x1ca
github.com/PlatONnetwork/PlatON-Go/core/state.(*StateDB).GetOrNewStateObject(0xc0523b1d40, 0x10, 0x0, 0x3000000, 0x6)
	/home/juzix/source/PlatON-Go/build/_workspace/src/github.com/PlatONnetwork/PlatON-Go/core/state/statedb.go:647 +0x3f
github.com/PlatONnetwork/PlatON-Go/core/state.(*StateDB).AddBalance(0xc0523b1d40, 0x10, 0x0, 0xc003000000, 0xc043e590c0)
	/home/juzix/source/PlatON-Go/build/_workspace/src/github.com/PlatONnetwork/PlatON-Go/core/state/statedb.go:383 +0x3f
github.com/PlatONnetwork/PlatON-Go/core.(*StateTransition).TransitionDb(0xc04e63d650, 0x14fbb80, 0xc05cc51ec0, 0xc044a84220, 0xc04e63d650, 0xc05cc51ec0, 0xc05cc51ec0, 0x1228f80)
	/home/juzix/source/PlatON-Go/build/_workspace/src/github.com/PlatONnetwork/PlatON-Go/core/state_transition.go:231 +0x558
github.com/PlatONnetwork/PlatON-Go/core.ApplyMessage(0xc0505bea80, 0x14fbb80, 0xc05cc51ec0, 0xc044a84220, 0xc0505bea80, 0xc0523b1d40, 0xc04e5dad80, 0x0, 0x0, 0x0, ...)
	/home/juzix/source/PlatON-Go/build/_workspace/src/github.com/PlatONnetwork/PlatON-Go/core/state_transition.go:130 +0x5b
github.com/PlatONnetwork/PlatON-Go/internal/ethapi.(*PublicBlockChainAPI).doCall(0xc002dda1e0, 0x14f6c60, 0xc05cc51da0, 0x10, 0x0, 0x1000000, 0xc04806ef20, 0x0, 0x0, 0x0, ...)
	/home/juzix/source/PlatON-Go/build/_workspace/src/github.com/PlatONnetwork/PlatON-Go/internal/ethapi/api.go:639 +0x659
github.com/PlatONnetwork/PlatON-Go/internal/ethapi.(*PublicBlockChainAPI).Call(0xc002dda1e0, 0x14f6ca0, 0xc0403d96b0, 0x10, 0x0, 0x1000000, 0xc04806ef20, 0x0, 0x0, 0x0, ...)
	/home/juzix/source/PlatON-Go/build/_workspace/src/github.com/PlatONnetwork/PlatON-Go/internal/ethapi/api.go:649 +0xdb
reflect.Value.call(0xc000240b00, 0xc00023d780, 0x13, 0x126b627, 0x4, 0xc05cc51d40, 0x4, 0x4, 0x0, 0xc05cc51d40, ...)
	/home/juzix/source/go/go/src/reflect/value.go:447 +0x449
reflect.Value.Call(0xc000240b00, 0xc00023d780, 0x13, 0xc05cc51d40, 0x4, 0x4, 0x2, 0x2, 0xc02f6364e0)
	/home/juzix/source/go/go/src/reflect/value.go:308 +0xa4
github.com/PlatONnetwork/PlatON-Go/rpc.(*Server).handle(0xc008ed12c0, 0x14f6ca0, 0xc0403d96b0, 0x14fc960, 0xc0401008c0, 0xc05cc51ce0, 0xc05ddfdf38, 0x467112, 0x8)
	/home/juzix/source/PlatON-Go/build/_workspace/src/github.com/PlatONnetwork/PlatON-Go/rpc/server.go:309 +0x6c3
github.com/PlatONnetwork/PlatON-Go/rpc.(*Server).exec(0xc008ed12c0, 0x14f6ca0, 0xc0403d96b0, 0x14fc960, 0xc0401008c0, 0xc05cc51ce0)
	/home/juzix/source/PlatON-Go/build/_workspace/src/github.com/PlatONnetwork/PlatON-Go/rpc/server.go:330 +0x1a6
github.com/PlatONnetwork/PlatON-Go/rpc.(*Server).serveRequest.func2(0xc04080e890, 0xc008ed12c0, 0xc0408164a0, 0x14fc960, 0xc0401008c0, 0xc051574bc8, 0x1, 0x1, 0xc00000f200)
	/home/juzix/source/PlatON-Go/build/_workspace/src/github.com/PlatONnetwork/PlatON-Go/rpc/server.go:204 +0xad
created by github.com/PlatONnetwork/PlatON-Go/rpc.(*Server).serveRequest
	/home/juzix/source/PlatON-Go/build/_workspace/src/github.com/PlatONnetwork/PlatON-Go/rpc/server.go:199 +0x28a

**Comment by benbaley** [comment]
this issue has been fixed at #1045

**Comment by shinnng** [comment]
this issue was fixed in 0.12.1
