### ISSUE TITLE
Trust cross settlement query the trust revenue to be collected and the account has no trust reward in each node

### ISSUE THREAD

**Issue by qiusese** [PlatONnetwork/PlatON-Go#1047]
PlatON version: `platon 0.7.6`
OS & Version: Windows/Linux/OSX

1、The node entrusts one transaction in the hesitation period, and the entrustment is in the ineffective period
2、Waiting for two settlement cycles to query bonus
3、The commission income to be collected and the query account have no commission reward withdrawn in each node is empty

**Comment by WeiLoy** [comment]
When a node is commissioned during the hesitation period, since there is no unit price reward in this period, the data of the period is not included when obtaining the unit price interface, and special judgment is required.

**Comment by benbaley** [comment]
close by done
