### ISSUE TITLE
After double signing, the amount of dividend pool is wrong

### ISSUE THREAD

**Issue by awake006** [PlatONnetwork/PlatON-Go#1052]
Hi there,

Nodes are pledged and entrusted in the first settlement cycle, and nodes are reported after the second signing cycle. After the third settlement cycle, the dividend pool amount is incorrect.

#### System information

PlatON version: `0.7.6`
OS & Version: Windows/Linux/OSX
Commit hash : 67d09831818382ab92e8295b1a85a57ce04e04c2

Nodes are pledged and entrusted in the first settlement cycle, and nodes are reported after the second signing cycle. After the third settlement cycle, the dividend pool amount is incorrect.

Number of consensus nodes: 4
Dividend ratio: 1000

Expected dividend pool balance: 0
Actual dividend pool balance: 43619475601604278074860

````
[backtrace]
````

**Comment by WeiLoy** [comment]
After the node was punished, it was removed from the candidate, but the cache of the candidate list in the reward module did not read the latest state data, causing a calculation error.

**Comment by benbaley** [comment]
close by done

**Comment by awake006** [comment]
done by ce89253b1c355ab31fb6c98f761362332cfe6113
