### ISSUE TITLE
After the modification of the entrusted income ratio becomes effective, the total entrusted income amount is wrong

### ISSUE THREAD

**Issue by awake006** [PlatONnetwork/PlatON-Go#1053]
Hi there,

After the modification of the entrusted income ratio becomes effective, the total entrusted income amount is wrong

#### System information

PlatON version: `0.7.6`
OS & Version: Windows/Linux/OSX
Commit hash : 67d09831818382ab92e8295b1a85a57ce04e04c2

+ In the first settlement cycle, a node is pledged, and the commission income is set to 1000, and the node is commissioned, and looks at the block rewards and pledge rewards of this settlement cycle;
+ In the second settlement cycle, check the block reward and pledge reward of this settlement cycle;
+ The third settlement cycle modifies the proportion of node division of labor, calculates the node income and entrusted income of the second settlement cycle；
+ The fourth cycle calculates the node income and entrusted income of the third settlement cycle;

The second settlement cycle:
Total revenue: 2716807487299465240641702
Commission income 1: 271680748729946524064152
The third settlement cycle:
Total revenue: 2716807487299465240641702
Commission income 2: 543361497459893048128334

Expected total entrusted return = entrusted return 1 + entrusted return 2
Actual total commissioned income = 674819924264705882352884

````
[backtrace]
````

**Comment by cheng762** [comment]
The third settlement cycle modifies will Take effect on The fourth cycle ，based on your description，your collect income seems not right。
         the income cal have some problem before https://github.com/PlatONnetwork/PlatON-Go/commit/e480a0019c2e045b5108a01237420122d256be9f,please test use this commitid

**Comment by benbaley** [comment]
close by done

**Comment by awake006** [comment]
done by ce89253b1c355ab31fb6c98f761362332cfe6113
