### ISSUE TITLE
Expected value is not the same as return value

### ISSUE THREAD

**Issue by hudenian** [PlatONnetwork/PlatON-Go#1057]
Hi there,

when i call contract,Expected value is not the same as return value

#### System information

PlatON version: `platon version`
OS & Version: Windows/Linux/OSX
Commit hash : (if `develop`)

#### Expected behaviour
when i call getF() ,return false from contract

#### Actual behaviour
Empty value (0x) returned from contract

#### Steps to reproduce the behaviour
1.my contract like this:
pragma solidity ^0.5.13;
contract C {
    struct S { bool f; }
    S s;
    function f() internal view returns (S storage c) {
        for(c = s;;) {
        }
    }
    function getF() public view returns(bool){
        S storage forS = f();
        return forS.f;
    }
}

#### Backtrace

````
[backtrace]
````

**Comment by zjsunzone** [comment]
Code: 
```
function f() internal view returns (S storage c) {
     for(c = s;;) {
     }
}
```
Endless loop causes call timeout. For calls, the default timeout is 5 seconds.

**Comment by zjsunzone** [comment]
Please try single line assignment for verification.

**Comment by hudenian** [comment]
It's really caused by infinite cycles，when i modify by this:

function f() internal view returns (S storage c) {
        for(c = s;c.f==true;) {}
}

can return Expected value

**Comment by zjsunzone** [comment]
> It's really caused by infinite cycles，when i modify by this:
> 
> function f() internal view returns (S storage c) {
> for(c = s;c.f==true;) {}
> }
> 
> can return Expected value

Ok, thank you very much for your feedback.

**Comment by hudenian** [comment]
Thanks for your explanation.I understand.
