### ISSUE TITLE
The Delegate reward cannot be withdraw completely, but can only be withdraw to the accuracy of G wei

### ISSUE THREAD

**Issue by shinnng** [PlatONnetwork/PlatON-Go#1065]
The delegate reward cannot be withdraw completely, but can only be withdraw to the accuracy of G wei, and the rest will be accumulated in the delegate reward pool. Please confirm the design method.

委托奖励不能领取完，只能领取G wei以上的委托奖励，剩余奖励将累积在委托奖励池。请确认该设计方式。

**Comment by benbaley** [comment]
This is what it's been desined to
设计如此，请@cheng762在设计中说明
