### ISSUE TITLE
The operation error is caused by the wrong amount when the Commission reward is withdrawn

### ISSUE THREAD

**Issue by qiusese** [PlatONnetwork/PlatON-Go#1068]
PlatON version: `platon 0.7.6`
OS & Version: Windows/Linux/OSX

1、Account delegation node, the delegation is in the ineffective period
2、Receive entrusted dividend after reaching the effective period
3、Incorrect display of the amount of the entrusted reward

**Comment by cheng762** [comment]
This is due to when every epoch begin ，not clean the verfier current epoch  delegate reward。have fix it in latest version
