### ISSUE TITLE
In the commission effective settlement cycle, a request for withdrawal of the commission reward is initiated, and in the next settlement cycle, the query dividend reward is 0

### ISSUE THREAD

**Issue by lipingD** [PlatONnetwork/PlatON-Go#1069]
In the commission effective settlement cycle, a request for withdrawal of the commission reward is initiated, and in the next settlement cycle, the query dividend reward is 0
@cheng762

**Comment by cheng762** [comment]
Analysis of the cause of the problem. When receiving the revenue that has not yet been generated, the revenue cycle in the commission information was incorrectly updated. The commission information was updated only when the plan was modified to generate revenue.

**Comment by benbaley** [comment]
close by done

**Comment by lipingD** [comment]
verify OK
