### ISSUE TITLE
Program version error

### ISSUE THREAD

**Issue by awake006** [PlatONnetwork/PlatON-Go#1076]
Hi there,

Program version error

#### System information

PlatON version: `0.7.6`
OS & Version: Windows/Linux/OSX
Commit hash : ce89253b1c355ab31fb6c98f761362332cfe6113

#### Expected behaviour
PlatON
Version: 0.7.6-unstable
Git Commit: ce89253b1c355ab31fb6c98f761362332cfe6113
Architecture: amd64
Protocol Versions: [63 62]
Network Id: 1
Go Version: go1.13.1
Operating System: linux
GOPATH=
GOROOT=/opt/go1.11.3

#### Actual behaviour

PlatON
Version: 0.7.5-unstable
Git Commit: ce89253b1c355ab31fb6c98f761362332cfe6113
Architecture: amd64
Protocol Versions: [63 62]
Network Id: 1
Go Version: go1.13.1
Operating System: linux
GOPATH=
GOROOT=/opt/go1.11.3

#### Steps to reproduce the behaviour

./platon version

#### Backtrace

````
[backtrace]
````

**Comment by benbaley** [comment]
This is a bug, please use the latest version https://github.com/PlatONnetwork/PlatON-Go/commit/97e1180b8696699c1ca60b917f32994522e901f2

**Comment by awake006** [comment]
Validation by c5885ecdaf08a4df47ab9160f61592f5f2575997
