### ISSUE TITLE
Withdraw part of the delegation in the  effective settlement cycle of delegating, and the next settlement cycle to query the dividend reward is 0

### ISSUE THREAD

**Issue by lipingD** [PlatONnetwork/PlatON-Go#1078]
Withdraw part of the delegation in the  effective settlement cycle of delegating, and the next settlement cycle to query the dividend reward is 0

**Comment by cheng762** [comment]
this is due to when cal  delegateReward,the handle not  get  the right epoch of  delegateRewardPer,have fix on https://github.com/PlatONnetwork/PlatON-Go/pull/1073

**Comment by lipingD** [comment]
The same problem occurs with increasing delegation
