### ISSUE TITLE
No delegation wallet. It is recommended to be clear about the delegation reward tips.

### ISSUE THREAD

**Issue by lipingD** [PlatONnetwork/PlatON-Go#1087]
No delegation wallet. It is recommended to be clear about the delegation reward tips.

 {'Code': 2, 'Ret': 'Object not found'}

**Comment by cheng762** [comment]
add error coed 305001 when not found delegation info  on getDelegateReward,https://github.com/PlatONnetwork/PlatON-Go/pull/1088

**Comment by lipingD** [comment]
Verification OK
