### ISSUE TITLE
Error in the prompt information of querying the available bonus after all the entrustments of the account redemption node

### ISSUE THREAD

**Issue by qiusese** [PlatONnetwork/PlatON-Go#1093]
PlatON version: `platon 0.7.6`
OS & Version: Windows/Linux/OSX

1.The account entrusts a transaction in the ineffective period
2.The account redeems all entrustments during the effective period
3.Users can get dividends after querying
4.Prompt message returned：{'Code': 2, 'Ret': 'Object not found'}

**Comment by cheng762** [comment]
this is a bug，account don't have delegate info in some node will
return error，fix in https://github.com/PlatONnetwork/PlatON-Go/pull/1092
