### ISSUE TITLE
small contract library calls error in double virtual 

### ISSUE THREAD

**Issue by qcxiao** [PlatONnetwork/PlatON-Go#1094]
small contract library calls error in double virtual.
Current small contract binary code is not supported,as attached screenshot.
![image](https://user-images.githubusercontent.com/13958152/72243366-bb76be80-3626-11ea-9295-e5cdb747953d.png)

**Comment by zjsunzone** [comment]
Hi,
  The library of solidity does not be recognized, because it does not have a default magic prefix. So we use the default EVM for unrecognized types.

**Comment by zjsunzone** [comment]
Solution: #1090
