### ISSUE TITLE
getDelegateReward() in core/vm/delegate_reward_contract.go, could be attacked

### ISSUE THREAD

**Issue by fksyuan** [PlatONnetwork/PlatON-Go#1101]
attacker  could pass very very long length arrary for nodeIDs parameters，perform ddos attack on a node。

suggest: limit nodeIDs length。

**Comment by jiangshangqifeng** [comment]
First of all, this interface provides the rpc query function. The rpc interface will not be open to the outside world. Only trusted people can operate the rpc interface.
Secondly, the query transaction will not be broadcast, and the attacker can only attack a single point without affecting the entire network.

For receiving rewards, commissioning or decommissioning interfaces, the blockchain charges a gas fee to limit the use of attacks. If a large array is passed, it will cost a lot of money.

The measured 7000 nodeid query consumes 30ms. If the message exceeds 7000 nodeid, the message will exceed 1M, so there is no risk of attack.

**Comment by fksyuan** [comment]
the size of message limit the length of nodeIDs parameters
