### ISSUE TITLE
In the delegate reward pool, the delegate reward amount that cannot be withdraw  is too larger

### ISSUE THREAD

**Issue by shinnng** [PlatONnetwork/PlatON-Go#1116]
In the delegate reward pool, the discarded reward amount (delegate reward amount that cannot be withdraw) is too larger. The discarded reward amount should be less than G VON per withdraw, but in fact, each lat will generate the discarded reward of G VON per cycle. Please confirm the design method.

在委托奖励池中，不能领取的委托奖励金额过大。预期每次提取委托奖励金额，不能领取的部分不超过G VON，但实际上，委托的每个LAT在每个周期，都可能产生不超过G VON的不可领取奖励。请确认该设计方案。

**Comment by cheng762** [comment]
对节点的某个周期进行数据分析如下:
分红比例:5%
委托奖励:135840374364973262032076VON
生效的委托:1000000LAT
单位委托奖励:  委托奖励(VON)/生效的委托(GVON)   =   135840374VON/GVON
可领取的收益:  单位委托奖励(VON/GVON)*节点生效的委托(VON) = 135840374000000000000000VON
留在委托池的收益:  364973262032076VON:

预估10年(约1600周期/年）该节点在委托池的残留金额=每个周期留在委托池的收益* 1600*10 = 5LAT

该算法确实会导致委托池收益残留，具体是否需要优化需要确认


The data analysis of a certain period of the node is as follows:
Dividend ratio: 5%
Commissioned reward: 135840374364973262032076VON
Effective commission: 1000000LAT
Unit commission reward: commission reward (VON) / effective commission (GVON) = 135840374VON / GVON
Receivable benefits: Unit commission reward (VON / GVON) * node effective commission (VON) = 135840374000000000000000VON
Revenue remaining in the commission pool: 364973262032076VON:

Estimated 10 years (approximately 1600 cycles / year) The residual amount of the node in the commission pool = the revenue left in the commission pool for each cycle * 1600 * 10 = 5LAT

**Comment by cheng762** [comment]
更新算法如下
某个账户在某个周期获得的委托奖励计算方法,假设账户的生效委托为delegate,单位委托奖励P为
DelegateRewardPer.Reward/DelegateRewardPer.Delegate(不预先计算),
委托奖励=P*delegate = delegate*DelegateRewardPer.Reward/DelegateRewardPer.Delegate

The calculation method of the commission reward obtained by an account in a certain period, assuming that the effective commission of the account is delegate,DelegateRewardPer.Reward/DelegateRewardPer.Delegate(Not pre-calculated
),DelegateReward = P*delegate = delegate*DelegateRewardPer.Reward/DelegateRewardPer.Delegate
