### ISSUE TITLE
use platon-cpp compile contract occurred error 

### ISSUE THREAD

**Issue by hudenian** [PlatONnetwork/PlatON-Go#1118]
Hi there,

use platon-cpp compile contract occurred error 

#### System information

PlatON version: `platon version`
OS & Version: Windows/Linux/OSX
Commit hash : (if `develop`)

#### Expected behaviour
compile success

#### Actual behaviour
error: use of undeclared identifier 'platon_assert'

#### Steps to reproduce the behaviour
**1.Contract_termination.cpp contract like this**
#include <platon/platon.hpp>
#include <string>

using namespace platon;
extern char const string_storage[] = "stringstorage";

CONTRACT ContractTermination : public platon::Contract{
   public:
      ACTION void init(){
      }
      ACTION bool transfer_assert(std::string name, uint64_t value){
            platon_assert(value >= 100, "bad value");
            stringstorage.self() = name;
      }
      CONST std::string get_string_storage(){
          return stringstorage.self();
      }
   private:
      platon::StorageType<string_storage, std::string> stringstorage;
};
PLATON_DISPATCH(ContractTermination, (init)(transfer_assert)(get_string_storage))

**2. compile command**
./platon-cpp Contract_termination.cpp -std=c++17

**3. compile errors**
Contract_termination.cpp:19:24: error: use of undeclared identifier 'platon_assert'

#### Backtrace

````
[backtrace]
````

**Comment by jatel** [comment]
Platon_assert was not provided in the previous version, but the latest version has added and closed the issue.

**Comment by hudenian** [comment]
thanks,when i pull the latest code,compile is nomal
