### ISSUE TITLE
invoke contract with function platon_assert  occurred error

### ISSUE THREAD

**Issue by hudenian** [PlatONnetwork/PlatON-Go#1119]
Hi there,

invoke contract with function platon_assert  occurred error

#### System information

PlatON version: `platon version`
OS & Version: Windows/Linux/OSX
Commit hash : (if `develop`)

#### Expected behaviour

invoke success

#### Actual behaviour

when invoke contract,return status is 0x0

#### Steps to reproduce the behaviour
1.Contract_termination.cpp contract like this
````
#include <platon/platon.hpp>
#include <string>
using namespace platon;

extern char const string_storage[] = "stringstorage";
/**
 * platon_assert
 */
CONTRACT ContractTermination : public platon::Contract{
   public:
      ACTION void init(){
      }
 
      ACTION bool transfer_assert(std::string name, uint64_t value){
            platon_assert(value >= 100, "bad value");
            stringstorage.self() = name;
      }

      CONST std::string get_string_storage(){
          return stringstorage.self();
      }

   private:
      platon::StorageType<string_storage, std::string> stringstorage;
};

PLATON_DISPATCH(ContractTermination, (init)(transfer_assert)(get_string_storage))
````
invoke contract as below:
invoke --addr 0x093acd8fF0b8aC2Cd1491571142205474342e887 --func transfer_assert --params {"name":"2","value":112}

return value as below:
{
 "root": "0x",
 "status": "0x0",
 "cumulativeGasUsed": "0x2faf080",
 "logsBloom": "0x00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000",
 "logs": [],
 "transactionHash": "0xa143b8bcb5444fb66a5ba2986aadcc076f9d9c64c6dcd734ce7f32fb55dc4c4e",
 "contractAddress": "0x0000000000000000000000000000000000000000",
 "gasUsed": "0x2faf080"
}

````



#### Backtrace

````
[backtrace]
````

**Comment by hudenian** [comment]
log error as bellow
![image](https://user-images.githubusercontent.com/16871744/73641514-17bf8200-46ab-11ea-98f6-881026c41dd2.png)

**Comment by jatel** [comment]
The transfer_assert function has a return value, but there is no return statement with the corresponding return value at the end of the function.When the contract method transfer_assert is called, the virtual machine crashes when the completion function does not get the return value.
Solution, the compiler platon-cpp adds the mandatory check return value when compiling the contract.

**Comment by w453908766** [comment]
clang++ will report a warning and generate call llvm.trap() instruction when lack return value,  cound lift warning to error, let developer add return statement.

**Comment by hudenian** [comment]
thanks very much
