### ISSUE TITLE
PlatON-CDT cmake error

### ISSUE THREAD

**Issue by qcxiao** [PlatONnetwork/PlatON-Go#1124]
Hi there,

#### System information

PlatON version: `platon version`
OS & Version: ubuntu
Commit hash : feature/wasm

#### Expected behaviour
cmake pass

#### Actual behaviour
cmake error

#### Steps to reproduce the behaviour
after `cmake ..` ,The following error occurred:
![image](https://user-images.githubusercontent.com/13958152/73804628-58301480-47ff-11ea-9dd0-8ebffbae3081.png)

**Comment by jatel** [comment]
https://github.com/PlatONnetwork/PlatON-CDT/pull/77，Pr fixed the bug, please refer to the latest readme.

**Comment by qcxiao** [comment]
> [https://github.com/PlatONnetwork/PlatON-CDT/pull/77，Pr](https://github.com/PlatONnetwork/PlatON-CDT/pull/77%EF%BC%8CPr) fixed the bug, please refer to the latest readme.

OK，ths
