### ISSUE TITLE
./platon-cpp Contract ，Contract method contains int8 type occurred error

### ISSUE THREAD

**Issue by qudongGithub** [PlatONnetwork/PlatON-Go#1125]
Hi there,

./platon-cpp Contract ，Contract method contains int8 type occurred error

#### System information

PlatON version: `platon version`
OS & Version: Windows/Linux/OSX
Commit hash : (if `develop`)

#### Expected behaviour
./platon-cpp Contract success

#### Actual behaviour
./platon-cpp Contract  occurred error

#### Steps to reproduce the behaviour
1、BasicDataTypeContract.cpp
`#include <platon/platon.hpp>
#include <string>
using namespace platon;

extern char const int8_a[] = "int8_t";
extern char const int32_b[] = "int32_t";
extern char const uint8_c[] = "uint8_t";
extern char const uint8_d[] = "uint8_t";
extern char const uint8_e[] = "uint8_t";

CONTRACT basicDataTypeContract : public platon::Contract{    
    private:
       platon:: StorageType<int8_a,int8_t> aInt8;
       platon:: StorageType<uint8_c,uint8_t> cUint8;
       platon:: StorageType<uint8_d,uint8_t> dUint8;
       platon:: StorageType<uint8_e,uint8_t> eUint8;

    public:
       ACTION void init(){
       }

       ACTION void setSignedInt(){
            aInt8.self() = 1;//发生异常
            cUint8.self() = 3;//正常
       }
};
PLATON_DISPATCH(basicDataTypeContract,(init)(setSignedInt))
`
2、./platon-cpp BasicDataTypeContract.cpp
![image](https://user-images.githubusercontent.com/7149295/73809099-0a220d80-480d-11ea-97a7-bae96cc09812.png)
 

#### Backtrace

````
[backtrace]
````

**Comment by jatel** [comment]
Int8 type c++ language package does not provide this type, so compile error is normal.

**Comment by qudongGithub** [comment]
Int8 type Already supported
