### ISSUE TITLE
How to call Sha3 encryption function in wasm contract? Do you have an example for reference？

### ISSUE THREAD

**Issue by liweichengcode** [PlatONnetwork/PlatON-Go#1126]

**Comment by jatel** [comment]
The platon_sha3 function implements the sha3-256 algorithm
example
uint8_t src[5] = {0x01, 0x07, 0x10, 0x20, 0x30};
uint8_t result[32] = {};
platon_sha3(src, 5, result, 32);

**Comment by liweichengcode** [comment]
Understand!
