### ISSUE TITLE
--miner.gasprice,After parameter setting, it does not take effect

### ISSUE THREAD

**Issue by awake006** [PlatONnetwork/PlatON-Go#1127]
#### System information

PlatON version: `0.8.0`
OS & Version: Windows/Linux/OSX
Commit hash :  416e846756db18feb31af0f737457c912dfdc39f

#### Steps to reproduce the behaviour
start node add parameter   --miner.gasprice 1000
sendTransaction
platon.sendTransaction({"from":"0x2e95e3ce0a54951eb9a99152a6d5827872dfb4fd","to":"0xbbe6200787aca5b1d1a1e9902dbefb4ffcf4311c","value":1000,"gasPrice":100})

actual results
Successful transaction execution

expected results
transaction fail

#### Backtrace

````
[backtrace]
````

**Comment by luo-dahui** [comment]
添加参数--miner.gasprice启动节点，没有重现问题。
1.当启动命令指定--miner.gasprice值，交易也指定gasPrice时，如果交易指定的gasPrice小于启动命令--miner.gasprice指定的值时，会报“transaction underpriced”的错。如下图：
![image](https://user-images.githubusercontent.com/45255023/73832396-0e691d80-4843-11ea-9d99-daf9e71a86f8.png)
