### ISSUE TITLE
The return value of platon_block_hash without 0x prefix.

### ISSUE THREAD

**Issue by zjsunzone** [PlatONnetwork/PlatON-Go#1137]
Hi there,

The return value of platon_block_hash without 0x prefix.

#### System information

PlatON version: `develop`
OS & Version: Linux
Commit hash : (if `develop`)

#### Expect 

format: `0x440628cbedd43ea93cd3423abc79fb8699757f71`

#### Actual

format: `440628cbedd43ea93cd3423abc79fb8699757f71`

**Comment by mowind** [comment]
fix in [#87](https://github.com/PlatONnetwork/PlatON-CDT/pull/87)
