### ISSUE TITLE
The return value of platon_origin is missing the prefix 0x

### ISSUE THREAD

**Issue by zjsunzone** [PlatONnetwork/PlatON-Go#1139]
Hi there,

The return value of platon_origin is missing the prefix 0x.

#### System information

PlatON version: `platon version`
OS & Version: Windows/Linux/OSX
Commit hash : (if `develop`)

#### Expected behaviour

format: `0xf93F1Fc1059f774b16a053aFAF97bfa9ada7F859`

#### Actual behaviour

format: `f93F1Fc1059f774b16a053aFAF97bfa9ada7F859`

#### Steps to reproduce the behaviour

```
...
return platon::platon_origin().toString();
...
```

**Comment by mowind** [comment]
fix in [#87](https://github.com/PlatONnetwork/PlatON-CDT/pull/87)

**Comment by zjsunzone** [comment]
There is no address type in wasm, you need to convert it manually.
