### ISSUE TITLE
wasm's EVENT was not signed as the first topic

### ISSUE THREAD

**Issue by GavinXu520** [PlatONnetwork/PlatON-Go#1141]
Hi there,

#### System information

PlatON version: `platon feature/wasm`
OS & Version: Windows/Linux/OSX

When using wasm's EVENT, I found that the EVENT signature was not used as the default first topic in the logs of the receipt.
Is this different from EVM, resulting in queries that are not optimized?

**Comment by jatel** [comment]
The latest CDT already supports topic with event names
