### ISSUE TITLE
VMInterpreter Configuration error

### ISSUE THREAD

**Issue by awake006** [PlatONnetwork/PlatON-Go#1150]
testnet
VMInterpreter Configuration error

#### System information

PlatON version: `0.8.0`
OS & Version: Windows/Linux/OSX
Commit hash : (if `develop`)

#### Expected behaviour

evm
#### Actual behaviour
wasm

#### Backtrace

````
[backtrace]
````

**Comment by benbaley** [comment]
This issue had been fixed in #1149

**Comment by luo-dahui** [comment]
testnet参数配置: VMInterpreter应该为evm
