### ISSUE TITLE
contract migrate fail

### ISSUE THREAD

**Issue by hudenian** [PlatONnetwork/PlatON-Go#1151]
Hi there,

contract migrate fail

#### System information

PlatON version: `platon version`
OS & Version: Windows/Linux/OSX
Commit hash : (if `develop`)

#### Expected behaviour
contract migrate success 

#### Actual behaviour
after migrate call function can not getter expected value

#### Steps to reproduce the behaviour
**1.my contract like this:**
#include <platon/platon.hpp>
#include <string>
using namespace platon;

CONTRACT ContractMigrate : public platon::Contract{
   public:
      PLATON_EVENT1(transfer,std::string,std::string)

      ACTION void init(){
      }

      ACTION std::string migrate_contract(const bytes &init_arg, uint64_t transfer_value, uint64_t gas_value){
            Address return_address;
            platon_migrate_contract(return_address, init_arg, transfer_value, gas_value);
            PLATON_EMIT_EVENT1(transfer,return_address.toString(),return_address.toString());
            DEBUG("new contract address:", return_address.toString());
            return return_address.toString();
      }

      ACTION void set_string(const std::string  &one_name){
          stringstorage.self()= one_name;
      }

      CONST std::string get_string(){
          return stringstorage.self();
      }
   private:
      platon::StorageType<"string_storage"_n, std::string> stringstorage;
};
PLATON_DISPATCH(ContractMigrate, (init)(migrate_contract)(set_string)(get_string))

**2.deploy ContractMigrate  contract **
deploy --wasm ContractMigrate_v1.wasm
result is:contract address: 0xB69409B8D186448B0AB9854F80EC450588e12bCA tx hash 0x57b42eff1713f10d1857d198a1cc61455e48e52571d6048363a01a3e86f7ae84

**3.invoke function set_string **
invoke --addr 0xB69409B8D186448B0AB9854F80EC450588e12bCA --func set_string --params {"one_name":"8"}

**4.call function get_string**
call --addr 0xB69409B8D186448B0AB9854F80EC450588e12bCA --func get_string
result is:return 0x38

**5.call function migrate_contract**
result is: new contract address: 0xbb4d86f2b3a94803e72adf5c1e2283b5254b084b 

**6.call new contract function get_string**
call --addr 0xbb4d86f2b3a94803e72adf5c1e2283b5254b084b --func get_string
result is:return 0x80

#### Backtrace

````
[backtrace]
````

**Comment by GavinXu520** [comment]
what is this txHash ?

**Comment by hudenian** [comment]
when i call function  migrate_contract my Input parameters init_arg is null so migrate  fail. i iput corrent init_arg param migrate is nomal.
