### ISSUE TITLE
When delegatecall the wasm contract, the state of the calling party did not get the expected change.

### ISSUE THREAD

**Issue by GavinXu520** [PlatONnetwork/PlatON-Go#1155]
Hi there,

Now I have two wasm contracts, a contract A that initiates a proxy call and a target contract B. Their contents are as follows:

wasm contract A:
`#include <platon/platon.hpp>
#include <vector>
#include <string>

using namespace platon;

class message {
   public:
      message(){}
      message(const std::string &p_head):head(p_head){}
   private:
      std::string head;
      PLATON_SERIALIZE(message, (head))
};

class my_message : public message {
   public:
      my_message(){}
      my_message(const std::string &p_head, const std::string &p_body, const std::string &p_end):message(p_head), body(p_body), end(p_end){}
   private:
      std::string body;
      std::string end;
      PLATON_SERIALIZE_DERIVED(my_message, message, (body)(end))
};

CONTRACT cross_delegate_call : public platon::Contract {
    public:
        ACTION void init(){}

        ACTION uint64_t delegate_call_add_message(const std::string &target_address,
        const my_message &one_message, uint64_t gas) {
            platon::bytes params = platon::cross_call_args("add_message", one_message);
            if (platon_delegate_call(Address(target_address), params, gas)) {
                 DEBUG("Delegate call contract success", "address", target_address);
            } else {
                DEBUG("Delegate call contract fail", "address", target_address);
            }
            return 0;
        }

         CONST uint64_t get_vector_size(){
             return arr.self().size();
         }

    private:
       platon::StorageType<"info_arr"_n, std::vector<my_message>> arr;

};

PLATON_DISPATCH(cross_delegate_call, (init)(delegate_call_add_message)(get_vector_size))`
----------------------------------------------------------------------------------------------------------

And wasm contract B :

`#include <platon/platon.hpp>
#include <string>
//#include <Contract_hello.hpp>
using namespace platon;

class message {
   public:
      message(){}
      message(const std::string &p_head):head(p_head){}
   private:
      std::string head;
      PLATON_SERIALIZE(message, (head))
};

class my_message : public message {
   public:
      my_message(){}
      my_message(const std::string &p_head, const std::string &p_body, const std::string &p_end):message(p_head), body(p_body), end(p_end){}
   private:
      std::string body;
      std::string end;
      PLATON_SERIALIZE_DERIVED(my_message, message, (body)(end))
};

CONTRACT hello : public platon::Contract{
   public:
      PLATON_EVENT1(hello, std::string, std::string, uint32_t)

     ACTION void init(){}
      
      ACTION std::vector<my_message> add_message(const my_message &one_message){
          PLATON_EMIT_EVENT1(hello, "add_message", "event1", 1);
          DEBUG("hello add_message");
          arr.self().push_back(one_message);
          return arr.self();
      }
      CONST std::vector<my_message> get_message(const std::string &name){
          PLATON_EMIT_EVENT1(hello, "get_message", "event2", 2);
          DEBUG("hello get_message");
          return arr.self();
      }

      CONST uint64_t get_vector_size(){
          DEBUG("hello get_vector_size");
          return arr.self().size();
      }

   private:
      platon::StorageType<"info_arr"_n, std::vector<my_message>> arr;
};

PLATON_DISPATCH(hello, (init)(add_message)(get_message)(get_vector_size))`

The difference between them is contract A has only one vector `arr` and` get_vector_size` method, while contract B has not only the vector `arr` and` get_vector_size` methods but also the add_message method.

Contract A uses the add_message method of contract B to make changes to its own state. It is expected that there will be elements in the vector `arr` of contract A.
But the actual result is that when calling the `get_vector_size` method of the A contract, no element was found.

#### System information

PlatON version: `platon version`
OS & Version: Windows/Linux/OSX
Commit hash : (if `develop`)

**Comment by jatel** [comment]
The proxy calls the same member name, which is overridden when the template class platon::StorageType is destructed.

The solution：
The development documentation notes that the proxy calls need to have the same name, and it is recommended not to use the template class platon::StorageType, which is encapsulated by the developer to avoid destructor overwriting.
