### ISSUE TITLE
Contract definition variable StorageType<"xxx"_n>， "xxx"_n variable definition too long to return correct value

### ISSUE THREAD

**Issue by qudongGithub** [PlatONnetwork/PlatON-Go#1175]
Hi there,
Contract definition variable StorageType<"xxx"_n>， "xxx"_n variable definition too long to return correct value

#### System information
PlatON version: `platon version`
OS & Version: Windows/Linux/OSX
Commit hash : (if `develop`)

#### Expected behaviour
Return the correct variable value

#### Actual behaviour
Return variable value is null or return value is wrong

#### Steps to reproduce the behaviour
//The code is as follows
platon::StorageType<"storage_tuple_b"_n,std::tuple<std::string,uint8_t>> storage_tuple_two;

ACTION void setInitTupleModeTwo(const std::string &a,const uint8_t &b){
         storage_tuple_two.self() = make_tuple(a,b);
}
CONST std::string getTupleValueIndex3(){
         return get<0>(storage_tuple_two.self());
 }

//1、 run method  setInitTupleModeTwo(a,b)
a = "lucy";
b = 10

//2、run method   getTupleValueIndex3
result = "";

#### Backtrace

````
[backtrace]
````

**Comment by jatel** [comment]
The string encoding algorithm, which previously used base32 encoding, now USES hash to remove the string length and character restrictions.
