### ISSUE TITLE
wasm  contract，Pointer is not supported for contract compilation

### ISSUE THREAD

**Issue by qudongGithub** [PlatONnetwork/PlatON-Go#1177]
Hi there,
When the  wasm  contract contains a pointer， to compile contract failed

#### System information
PlatON version: `platon version`
OS & Version: Windows/Linux/OSX
Commit hash : (if `develop`)

#### Expected behaviour
  The contract can be compiled normally

#### Actual behaviour
  The contract can be compiled error

#### Steps to reproduce the behaviour
1、The code is as follows
//链表插入元素
        ACTION void insertElement(listNode *pNote,std::string &my_name){

               //申请新的节点空间
               listNode *body = (listNode*)malloc(sizeof(listNode));
               //遍历链表
               while (pNote != nullptr)
               	{
               		//如果下一个节点为空，则插入元素
               		if (pNote->nextPointer == nullptr)
               		{
               			pNote->nextPointer = body;
               			body->name = my_name;
               			body->nextPointer = nullptr;
               			return;
               		}
               		pNote = pNote->nextPointer;
               	}
        }
2、run   ./platon-cpp ReferenceDataTypeLinkedlistContract.cpp
3、Operation result
![image](https://user-images.githubusercontent.com/7149295/74933875-f0ddab80-541f-11ea-9ab8-128e337c1fdf.png)

#### Backtrace

````
[backtrace]
````

**Comment by jatel** [comment]
RLP does not currently support pointer types
