### ISSUE TITLE
Dockerfile is unavailable

### ISSUE THREAD

**Issue by lcgogo** [PlatONnetwork/PlatON-Go#1178]
Hi there,

please note that this is an issue tracker reserved for bug reports and feature requests.

#### System information

PlatON version: `platon version`
OS & Version: Ubuntu
Commit hash : (if `develop`)

#### Expected behaviour
docker build .

#### Actual behaviour
Step 4/9 : RUN cd /PlatON-Go && make platon
 ---> Running in 410f092cf5dd
build/build_deps.sh
build/build_deps.sh: line 14: git: command not found
/PlatON-Go/build//build_bls.sh: line 13: git: command not found
make[1]: *** No targets specified and no makefile found.  Stop.
make[1]: Entering directory '/PlatON-Go/crypto/bls/bls_linux_darwin/src/bls'
make[1]: Leaving directory '/PlatON-Go/crypto/bls/bls_linux_darwin/src/bls'
build/build_deps.sh: line 48: cd: /PlatON-Go/life/resolver/softfloat/build/Linux-x86_64-GCC: No such file or directory
make: *** [Makefile:15: platon] Error 1
The command '/bin/sh -c cd /PlatON-Go && make platon' returned a non-zero code: 2

#### Backtrace

````
[backtrace]
````

**Comment by benbaley** [comment]
fixed in #1729
