### ISSUE TITLE
Can not send LAT to inner contract, such as '0x1000000000000000000000000000000000000006'

### ISSUE THREAD

**Issue by benbaley** [PlatONnetwork/PlatON-Go#1187]
Hi there,

Can not send LAT to inner contract, such as '0x1000000000000000000000000000000000000006'， the transaction receipt return status=0 and the log output 'out of gas'

@GavinXu520 @cheng762 

please note that this is an issue tracker reserved for bug reports and feature requests.

#### System information

PlatON version: `platon version`
OS & Version: Windows/Linux/OSX
Commit hash : (if `develop`)

#### Backtrace

````
[backtrace]
````

**Comment by benbaley** [comment]
this issue will be fixed in 0.11.0

**Comment by shinnng** [comment]
It has been fixed and verified
