### ISSUE TITLE
Create a new node and report a bad block to the synchronization block

### ISSUE THREAD

**Issue by lipingD** [PlatONnetwork/PlatON-Go#1198]
step：
1、create a new node, access to the wasm test environment
2、synchronization the block of 676562, "BAD BLOCK" appears

初步判断：wasm 使用了具有随机性质的逻辑或库，导致同步是交易顺序不同，然后同样的区块，同步就bad block

**Comment by lipingD** [comment]
commit id： a1188e786fba740d0ad23e67c85883bbf3dc5bf7

step：1、create a new node,
          2、synchronization the block of 676562, "BAD BLOCK" appears

**Comment by lipingD** [comment]
Verification OK

**Comment by GavinXu520** [comment]
The storage-optimized gc mechanism results in multi-node data inconsistencies when multiple contract accounts have the same key, which leads to the "BAD BLOCK" problem.
