### ISSUE TITLE
Special nodes synchronize blocks very slowly, nearly one block per hour

### ISSUE THREAD

**Issue by shinnng** [PlatONnetwork/PlatON-Go#1199]
At uatnet, special nodes synchronize blocks very slowly, nearly one block per hour, but log updates are very fast.

node ip:192.168.9.112
platon dir: /usr/bin/splaton   
data dir: /opt/splaton/
log dir: /logbak/splaton

**Comment by niuxiaojie81** [comment]
After log analysis, the blocks are normally synchronized, but it takes a lot of time to execute the blocks and write to the disk. After checking the system resources, it is found that the CPU utilization of the machine itself is too high, and the disk IO is too high
