### ISSUE TITLE
Illegal address string converted to Address type, the compiler did not detect an exception.

### ISSUE THREAD

**Issue by zjsunzone** [PlatONnetwork/PlatON-Go#1201]
Hi there,

Illegal address string converted to Address type, the compiler did not detect an exception

#### System information

PlatON version: `platon version`
OS & Version: Windows/Linux/OSX
Commit hash : (if `develop`)

#### Expected behaviour

The compiler detected an illegal address.

#### Actual behaviour

The compiler did not detect an illegal address.

#### Steps to reproduce the behaviour

WASM Contract Code:
```
...
CONST Address addr() {
    // real: 0xEC081ab45BE978A4A630eB8cbcBffA50E747971B
    return Address("0xEC081ab45BE978A4A630eB8cbcBffA50E74797");
}
...
```
This code compiler needs to identify errors.

**Comment by mowind** [comment]
The compiler unknwon what is a correct `Address`.

**Comment by jatel** [comment]
The string encoding algorithm, which previously used base32 encoding, now USES hash to remove the string length and character restrictions.

**Comment by zjsunzone** [comment]
> The compiler unknwon what is a correct `Address`.

Whether to consider implementation in the future.

**Comment by jatel** [comment]
Platon provides the make_address function to construct the address. This function determines the address, and if the length is incorrect, an error is reported at compile time.

example，  Address arrr = make_address("0x43355c787c50b647c425f594b441d4bd751951c1");

**Comment by zjsunzone** [comment]
Address legal length verification succeeded.
