### ISSUE TITLE
C + + new features， std::forward_list、std::unordered_map、std::unordered_set  cdt compile  failure

### ISSUE THREAD

**Issue by qudongGithub** [PlatONnetwork/PlatON-Go#1206]
Hi there,

C + + new features， std::forward_list、std::unordered_map、std::unordered_set  cdt compile  failure
#### System information

PlatON version: `platon version`
OS & Version: Windows/Linux/OSX
Commit hash : (if `develop`)

#### Steps to reproduce the behaviour
Contract Code:
**1、std::forward_list type contract code**
`CONTRACT ReferenceDataTypeForwardlistContract : public platon::Contract{
     private:
       platon::StorageType<"forwardlist"_n, std::forward_list<uint8_t>> storage_int_forward_list;
    public:
    ACTION void init(){}

     //1)、forwardlist类型初始化赋值
    ACTION void init_forward_list(){
          storage_int_forward_list.self() = {1,2,3,4,5};
    }
    //2)、forwardlist创建
    ACTION void create_forward_list(){
         //1、创建空元素容器
         std::forward_list<uint8_t> values1;
         //2、创建一个包含10个元素的 容器
         std::forward_list<uint8_t> values2(10);
         //3、创建一个包含10个元素，并初始化值
         std::forward_list<uint8_t> values3(10, 5);
    }
};
PLATON_DISPATCH(ReferenceDataTypeForwardlistContract,(init)(init_forward_list)(create_forward_list))
`
**2、std::unordered_map type contract code**
`CONTRACT ReferenceDataTypeUnorderMapContract : public platon::Contract{
    private:
      platon::StorageType<"unordermap"_n, std::unordered_map<std::string,std::string>> storage_string_map;
    public:
      ACTION void init(){}
      // 1)、1)、unorderMap类型初始化赋值
      ACTION void init_unorder_map(){
            storage_string_map.self() = {{"apple","red"},{"lemon","yellow"}};
      }
};
PLATON_DISPATCH(ReferenceDataTypeUnorderMapContract,(init)(init_unorder_map))`
**3、std::unordered_set  type contract code**
`CONTRACT ReferenceDataTypeUnorderSetContract1 : public platon::Contract{
     private:
       platon::StorageType<"set"_n, std::unordered_set<std::string>> storage_string_set;
    public:
       ACTION void init(){}
     // 1)、unorederd_set类型类型初始化赋值
    ACTION void init_unordered_set(){
          storage_string_set.self() = {"one","two","three"};
    }
    //2)、unorederd_set创建
    ACTION void create_unordered_set(){
         //1、创建空元素容器
         std::unordered_set<std::string> values1;
         //2、创建一个容器并赋值
         std::unordered_set<std::string> values2{"aaa","bbb","ccc"};
    }
};
PLATON_DISPATCH(ReferenceDataTypeUnorderSetContract1,(init)
(init_unordered_set)(create_unordered_set))`

#### Backtrace
**1、std::forward_list type contract code**
![image](https://user-images.githubusercontent.com/7149295/75737215-2b0d4e00-5d3a-11ea-99d3-ac96d3ce3d33.png)
**2、std::unordered_map type contract code**
![image](https://user-images.githubusercontent.com/7149295/75737361-86d7d700-5d3a-11ea-9f47-836b5557e477.png)
**3、std::unordered_set  type contract code**
![image](https://user-images.githubusercontent.com/7149295/75737215-2b0d4e00-5d3a-11ea-99d3-ac96d3ce3d33.png)
````
[backtrace]
````

**Comment by jatel** [comment]
The commonly used STL of RLP extension has met the requirements of the present stage, and further expansion is needed in the future.
