### ISSUE TITLE
wasm contract，contract contain float type execute contract script not enough gas error

### ISSUE THREAD

**Issue by qudongGithub** [PlatONnetwork/PlatON-Go#1216]
Hi there,
wasm contract，contract contain float type execute contract script not enough gas error

#### System information
PlatON version: `platon version`
OS & Version: Windows/Linux/OSX
Commit hash : (if `develop`)

#### Steps to reproduce the behaviour
**1、contract code：**
platon::StorageType<"floatkey"_n,float> float_v;
ACTION void set_float(const float &value){
          float_v.self() = value;
}
CONST float get_float(){
          return float_v.self();
 }
**2、script  code** 
   Float floatValue = 1.5f;
            TransactionReceipt  transactionReceipt5 = basicDataTypeContract.set_float(floatValue).send();
            collector.logStepPass("basicDataTypeContract 【验证浮点类型(float)】 successfully hash:" + transactionReceipt5.getTransactionHash());
            Float actualFloatValue = basicDataTypeContract.get_float().send();
            collector.logStepPass("basicDataTypeContract 【验证浮点类型(float)取值】 执行get_float() successfully actualFloatValue:" + actualFloatValue);
            collector.assertEqual(actualFloatValue,floatValue, "checkout  execute success.");
#### Backtrace
![image](https://user-images.githubusercontent.com/7149295/75883338-d4009980-5e5d-11ea-94c7-1783e0f9d976.png)

````
[backtrace]
````

**Comment by jatel** [comment]
Floating point number operation will cause the node data inconsistent, the current stage of the mask floating point number first off the operation, the compilation phase error.
