### ISSUE TITLE
File cannot be found using #include <src/Ownable.hpp>, but #include "src/Ownable.hpp" can.

### ISSUE THREAD

**Issue by zjsunzone** [PlatONnetwork/PlatON-Go#1219]
Hi there,

File cannot be found using #include <src/a.hpp>, but #include "src/a.hpp" can.

#### System information

PlatON version: `platon version`
OS & Version: Windows/Linux/OSX
Commit hash : (if `develop`)

#### Backtrace

````
src/test/resources/contracts/wasm/contract_docs/Bank.cpp:5:10: error: 
      'src/Ownable.hpp' file not found with <angled> include; use "quotes"
      instead
#include <src/Ownable.hpp>
         ^~~~~~~~~~~~~~~~~
         "src/Ownable.hpp"
1 error generated.
````

**Comment by jatel** [comment]
Explain in the document to emphasize how to use the included file.
