### ISSUE TITLE
Missing int128 data type in wasm contract

### ISSUE THREAD

**Issue by zjsunzone** [PlatONnetwork/PlatON-Go#1233]
Hi there,

Missing int128 data type in wasm contract.

#### System information

PlatON version: `platon version`
OS & Version: Windows/Linux/OSX
Commit hash : (if `develop`)

#### Backtrace

````
[backtrace]
````

**Comment by jatel** [comment]
Large integer is mainly used for the amount and gas amount when the transfer, these values are positive, positive has been able to meet the demand, temporarily did not find that the business scenario hard need large integer negative, so temporarily not support.
