### ISSUE TITLE
u128 does not support power operations in WASM contracts

### ISSUE THREAD

**Issue by zjsunzone** [PlatONnetwork/PlatON-Go#1239]
Hi there,

u128 does not support power operations in WASM contracts.

#### System information

PlatON version: `platon version`
OS & Version: Windows/Linux/OSX
Commit hash : (if `develop`)

#### Backtrace

````
[backtrace]
````

**Comment by jatel** [comment]
U128 type c library functions do not support functions such as the power function, which can be replaced with the original multiplication and so on.U128 is mainly used for the amount and gas amount in the transfer. The complex data calculation will not be involved for the time being, so it is not necessary to extend such operation for the time being.
