### ISSUE TITLE
Cannot initialize a large number using u128.

### ISSUE THREAD

**Issue by zjsunzone** [PlatONnetwork/PlatON-Go#1242]
Hi there,

Cannot initialize a large number using u128. 

#### System information

PlatON version: `platon version`
OS & Version: Windows/Linux/OSX
Commit hash : (if `develop`)

#### Steps to reproduce the behaviour

example:
`Use u128 to initialize the number: 10000000000000000000`

**Comment by jatel** [comment]
The largest integer supported by c++ is of type uint_64, and when the value is greater than 2 to the 64 minus 1, the literal will report an error.Adds string literal operator _u128, which supports large integer string representations that can be converted directly to type u128.

The latest version has been resolved, please download the latest version of CDT

**Comment by zjsunzone** [comment]
Tks. Verified.
