### ISSUE TITLE
no malloc can assign value to point

### ISSUE THREAD

**Issue by fksyuan** [PlatONnetwork/PlatON-Go#1245]
the contract is :
`#include <platon/platon.hpp>
#include <string>
using namespace platon;

CONTRACT RecursionCall : public platon::Contract {

    private:
	    platon::StorageType<"test"_n, uint32_t> sum = 0;
	public:
        ACTION void init(){}

        ACTION void call(uint32_t n) {
            uint32_t* p = NULL;
			*(p+n) = n;
			sum.self() = *(p+n);
        }

        CONST uint32_t get_sum() {
            return sum.self();
        }
};
PLATON_DISPATCH(RecursionCall,(init)(call)(get_sum))`

call(uint32_t n) method can set value and get_sum() can get the right value.

I use js sdk test results is:
receipt gas= 44929
ret= 0
receipt gas= 45853
ret= 10000000
receipt gas= 46289
ret= 4294967295

**Comment by jatel** [comment]
The temporary variables are optimized by the compiler.If you add other operations, you will find that the invalid address cannot be accessed and the virtual machine will report an error.
