### ISSUE TITLE
Define: `PLATON_EVENT1(MyEvent, u128);` , Compile failed.

### ISSUE THREAD

**Issue by zjsunzone** [PlatONnetwork/PlatON-Go#1252]
Hi there,

Define: `PLATON_EVENT1(MyEvent, u128);` , Compile failed.

#### System information

PlatON version: `platon version`
OS & Version: Windows/Linux/OSX
Commit hash : (if `develop`)

#### Steps to reproduce the behaviour

```
...
PLATON_EVENT1(MyEvent, u128);
...
```

**Comment by mowind** [comment]
Fixes in [#151](https://github.com/PlatONnetwork/PlatON-CDT/pull/151)
