### ISSUE TITLE
static check error

### ISSUE THREAD

**Issue by fksyuan** [PlatONnetwork/PlatON-Go#1253]
1. core/vm/wagon_runtime.go:1292:15: ineffectual assignment to `err` (ineffassign)
		topicCount, err := rlp.CountValues(content)
2. [/home/pchuant/code/src/github.com/PlatONnetwork/PlatON-Go/core/vm/wasm_engine.go:103] - G104 (CWE-703): Errors unhandled. (Confidence: HIGH, Severity: LOW)
  > engine.vm.Close()
3. [/home/pchuant/code/src/github.com/PlatONnetwork/PlatON-Go/core/vm/wasm_engine.go:176] - G104 (CWE-703): Errors unhandled. (Confidence: HIGH, Severity: LOW)
  > hash.Write([]byte(initFn))

**Comment by GavinXu520** [comment]
The first and third points have been processed, the second point does not need to be processed
