### ISSUE TITLE
Using the genesis. Json file to build the chain of version 0.11, the new penalty parameter could not be properly applied

### ISSUE THREAD

**Issue by shinnng** [PlatONnetwork/PlatON-Go#1276]
Using the genesis.json file to build the chain of version 0.11, the new slashing param (zeroProduceCumulativeTime, zeroProduceNumberThreshold)  did not take effect properly.

PlatON version: `0.11.0`
OS & Version: Linux
Commit hash :  e18f2e2bf3803ef054c594e879cc7b2c32b1d0ab

**Comment by WeiLoy** [comment]
already fixed
