### ISSUE TITLE
Upgrade node, appears “BAD BLOCK”；The error message is“invalid vrf prove”

### ISSUE THREAD

**Issue by lipingD** [PlatONnetwork/PlatON-Go#1281]
@WeiLoy

**Comment by cheng762** [comment]
this is a bug when snapotdb open before blockchain,so snaoshot db can't recover from blockchain.
fix：
the snapshotdb will open baseDB instad ,https://github.com/PlatONnetwork/PlatON-Go/pull/1288

**Comment by lipingD** [comment]
verify OK

**Comment by shinnng** [comment]
It has been fixed and verified
