### ISSUE TITLE
static check error staking_plugin.go

### ISSUE THREAD

**Issue by fksyuan** [PlatONnetwork/PlatON-Go#1286]
[/home/pchuant/code/src/github.com/PlatONnetwork/PlatON-Go/x/plugin/staking_plugin.go:230] - G104 (CWE-703): Errors unhandled. (Confidence: HIGH, Severity: LOW)
  > sk.eventMux.Post(cbfttypes.AddValidatorEvent{NodeID: node.NodeId})

**Comment by WeiLoy** [comment]
Processed
