### ISSUE TITLE
Without --db.nogc, tx details will not be found

### ISSUE THREAD

**Issue by GavinXu520** [PlatONnetwork/PlatON-Go#1290]
When --db.nogc is not turned on, I find that tx will be deleted in addition to the historical state and tx receipts?

#### System information

PlatON version: `0.10.1`
OS & Version: Windows/Linux/OSX
Commit hash : 1bc1d754bbc4ac338559cdd0622884a17eec110c

#### Expected behaviour
platon.getTransaction('xxxxxx')

Need to find tx details

#### Actual behaviour
![41899e7c54ccd02dc85c71474c97dbb](https://user-images.githubusercontent.com/13655605/77499654-aa032b80-6e8d-11ea-8767-12231343ac6a.png)

**Comment by benbaley** [comment]
this issue will be fixed in 0.11.0
