### ISSUE TITLE
Submit parameter proposal and read the generated configuration;"paramProposalVoteDurationSeconds"

### ISSUE THREAD

**Issue by lipingD** [PlatONnetwork/PlatON-Go#1293]
Submit parameter proposal and read the generated configuration; "paramProposalVoteDurationSeconds"

**Comment by bglmmz** [comment]
fixed. apply version 0.10.0 (update the paramProposalVoteDurationSeconds value) only for chainID=101 or 299.

**Comment by lipingD** [comment]
verify OK
