### ISSUE TITLE
bad block when upgrade to version 0.11.0

### ISSUE THREAD

**Issue by qcxiao** [PlatONnetwork/PlatON-Go#1294]
Hi there,

from 0.10.1 upgrade to version 0.11.0, send wasm contract before and after upgrade ， bad block when synchronized with version 0.11.0

**Comment by GavinXu520** [comment]
In the 0.10.1 version, even if the wasm code is deployed on evm, it currently supports you to do so. If it is not successful, it may not be necessary! And 0.11.0 made gas optimization rules for wasm deployment parameters, but forgot to do governance fork here.
Currently fixed
