### ISSUE TITLE
If the ‘textProposalVoteDurationSeconds ’ parameter configuration is less than the number of consensus round blocks, the endvotingblock of the text proposal may be less than the submitblock

### ISSUE THREAD

**Issue by lipingD** [PlatONnetwork/PlatON-Go#1329]
If the ‘textProposalVoteDurationSeconds ’ parameter configuration is less than the number of consensus round blocks, the endvotingblock of the text proposal may be less than the submitblock

**Comment by bglmmz** [comment]
fixed. make sure the endVotingBlock is higher than submitBlock.

**Comment by lipingD** [comment]
verify ok
