### ISSUE TITLE
The result by wasm contract using the function platon_coinbase is 0x10000000000000000000000000000000000000003.

### ISSUE THREAD

**Issue by liweichengcode** [PlatONnetwork/PlatON-Go#1355]
#include <platon/platon.hpp>
#include <string>
using namespace platon;

CONTRACT CoinbaseFunction : public platon::Contract{
	public:

    ACTION void init() {}

    CONST std::string get_platon_coinbase() {
        bytes addr;
      	addr.resize(20);
        ::platon_coinbase(addr.data());
        return Address(addr).toString();
    }
};
PLATON_DISPATCH(CoinbaseFunction, (init)(get_platon_coinbase))

**Comment by jatel** [comment]
The toString() method did not adapt to the bech32 format before, and the new CDT is already adapted.
