### ISSUE TITLE
The result by wasm contract using the function platon_caller() is 0xe03887881e1e0cd6cdbfc82bc3292b8ad9a683f2.

### ISSUE THREAD

**Issue by liweichengcode** [PlatONnetwork/PlatON-Go#1356]
#include <platon/platon.hpp>
#include <string>
using namespace platon;

CONTRACT CallerFunction : public platon::Contract{
	public:

    ACTION void init() {}

    CONST std::string get_platon_caller() {
        bytes addr;
      	addr.resize(20);
        ::platon_caller(addr.data());
        Address address(addr);
        DEBUG("caller", "addr", address.toString());
        return Address(addr).toString();
    }
};

PLATON_DISPATCH(CallerFunction, (init)(get_platon_caller))

**Comment by jatel** [comment]
The toString() method did not adapt to the bech32 format before, and the new CDT is already adapted.
