### ISSUE TITLE
The caller transfers balance to the callee, the balance of the caller decreases, but the balance of the callee does not increase

### ISSUE THREAD

**Issue by hudenian** [PlatONnetwork/PlatON-Go#1357]
Hi there,

please note that this is an issue tracker reserved for bug reports and feature requests.

#### System information

PlatON version: `platon version`
OS & Version: Windows/Linux/OSX
Commit hash : (if `develop`)

#### Expected behaviour
caller balance decreases and callee balance balance increase

#### Actual behaviour
caller balance decreases and callee balance balance dose not increase

#### Steps to reproduce the behaviour
**caller contract like this:**
#include <platon/platon.hpp>
#include <vector>
#include <string>
using namespace platon;

CONTRACT cross_call_storage_str : public platon::Contract {
    public:
        ACTION void init(){}

        ACTION uint64_t call_set_string(const std::string &target_address, const std::string &name,
          uint64_t value, uint64_t gas) {

            DEBUG("Call contract start", "address", target_address, "name", name);
            platon::bytes params = platon::cross_call_args("set_string", name);

            if (platon_call(Address(target_address), params, value, gas)) {
                 DEBUG("Call contract success", "address", target_address);
             } else {
                 DEBUG("Call contract fail", "address", target_address);
             }
            return 0;
        }
       CONST const std::string get_string(){
          DEBUG("cross_call_storage_str get_string", "name:", str.self());
          return str.self();
      }
    private:
       platon::StorageType<"str"_n, std::string> str;
};

PLATON_DISPATCH(cross_call_storage_str, (init)(call_set_string)(get_string))

**callee contract like this:**
#include <platon/platon.hpp>
#include <vector>
#include <string>

using namespace platon;

CONTRACT cross_call_storage_str : public platon::Contract {
    public:
        ACTION void init(){}

        ACTION uint64_t call_set_string(const std::string &target_address, const std::string &name,
          uint64_t value, uint64_t gas) {

            DEBUG("Call contract start", "address", target_address, "name", name);
            platon::bytes params = platon::cross_call_args("set_string", name);

            if (platon_call(Address(target_address), params, value, gas)) {
                 DEBUG("Call contract success", "address", target_address);
             } else {
                 DEBUG("Call contract fail", "address", target_address);
             }
            return 0;
        }
       CONST const std::string get_string(){

          DEBUG("cross_call_storage_str get_string", "name:", str.self());
          return str.self();
      }
    private:
       platon::StorageType<"str"_n, std::string> str;
};

PLATON_DISPATCH(cross_call_storage_str, (init)(call_set_string)(get_string))

**operator detail:**
1.transfer 1000lat to caller
2. check caller and callee balance
3.call caller function call_set_string and set param value 100lat
4.check caller and callee balance 

#### Backtrace

````
[backtrace]
````

**Comment by jatel** [comment]
You can use the make_address method to convert a string Address to an internal Address of type Address
Such as:
#define TESTNET
std::string target_address = "lax10jc0t4ndqarj4q6ujl3g3ycmufgc77epxg02lt";
auto result = make_address(target_address);
if(result.second) Address address = result.first;

**Comment by hudenian** [comment]
thanks very much
