### ISSUE TITLE
It is error when you use Address(std::string) in wasm contracts. Address beginning '0x' has no problem but address beginning 'lax' fails to use.

### ISSUE THREAD

**Issue by liweichengcode** [PlatONnetwork/PlatON-Go#1358]
#include <platon/platon.hpp>
#include <string>
using namespace std;
using namespace platon;

CONTRACT ReferenceDataTypeContract: public platon::Contract{

	private:
       platon::StorageType<"maddress"_n, std::map<std::string, Address>> tmaddress;
       platon::StorageType<"mu255"_n, std::map<std::string, u128>> tmu256;
       platon::StorageType<"mh255"_n, std::map<std::string, h256>> tmh256;

    public:
        ACTION void init(){}
		
		ACTION void setAddressMap(const std::string& key, const std::string& addr)
		{
			tmaddress.self()[key] = Address(addr);
		}
		
		// get value from map of address type.
		CONST std::string getAddrFromMap(const std::string& key) 		
		{
			return tmaddress.self()[key].toString();
		}
		
		// get the length of map.
		CONST uint8_t sizeOfAddrMap()
		{
			return tmaddress.self().size();
		}
		
	public:
		ACTION void setU256Map(const std::string& key, uint64_t value)
		{
			tmu256.self()[key] = u128(value);
		}
		
		// get value from map of address type.
		CONST std::string getU256FromMap(const std::string& key) 		
		{
			return std::to_string(tmu256.self()[key]);
		}
		
		// get the length of map.
		CONST uint8_t sizeOfU256Map()
		{
			return tmu256.self().size();
		}

	public:
		ACTION void setH256Map(const std::string& key, const std::string& value)
		{
			tmh256.self()[key] = h256(value);
		}
		
		// get value from map of h256 type.
		CONST std::string getH256FromMap(const std::string& key) 		
		{
			return tmh256.self()[key].toString();
		}
		
		// get the length of map.
		CONST uint8_t sizeOfH256Map()
		{
			return tmh256.self().size();
		}
        
};

PLATON_DISPATCH(ReferenceDataTypeContract, (init)(setAddressMap)(getAddrFromMap)(sizeOfAddrMap)(setU256Map)(getU256FromMap)(sizeOfU256Map)(setH256Map)(getH256FromMap)(sizeOfH256Map))

**Comment by jatel** [comment]
The toString() method did not adapt to the bech32 format before, and the new CDT is already adapted.
You can use the make_address method to convert a string Address to an internal Address of type Address
Such as:
#define TESTNET
std::string target_address = "lax10jc0t4ndqarj4q6ujl3g3ycmufgc77epxg02lt";
auto result = make_address(target_address);
if(result.second) Address address = result.first;

**Comment by liweichengcode** [comment]
already solve
