### ISSUE TITLE
wasm cross-contract call failed

### ISSUE THREAD

**Issue by hudenian** [PlatONnetwork/PlatON-Go#1362]
Hi there,

please note that this is an issue tracker reserved for bug reports and feature requests.

#### System information

PlatON version: `platon version`
OS & Version: Windows/Linux/OSX
Commit hash : (if `develop`)

#### Expected behaviour
wasm cross-contract call success

#### Actual behaviour
wasm cross-contract call fail

#### Steps to reproduce the behaviour
**contract A like this:**
#define TESTNET
#include <platon/platon.hpp>
#include <vector>
#include <string>
using namespace platon;

CONTRACT delegate_call_storage_str : public platon::Contract {
     public:
     ACTION void init(){}

     ACTION uint64_t delegate_call_set_string(const std::string &target_address, std::string &name, uint64_t gas) {
         
         DEBUG("Delegate call contract start", "address", target_address, "name", name);
         platon::bytes params = platon::cross_call_args("set_string", name);
         
         if (platon_delegate_call(Address(target_address), params, gas)) {
              DEBUG("Delegate call contract success", "address", target_address, "name", name);
         } else {
             DEBUG("Delegate call contract fail", "address", target_address, "name", name);
         }
         return 0;
     }
      CONST const std::string get_string(){
          platon::StorageType<"str"_n, std::string> str; // Must use local definitions for manipulating the corresponding keys in th
          return str.self();
      }
};

PLATON_DISPATCH(delegate_call_storage_str, (init)(delegate_call_set_string)(get_string))

**contract B like this:**
#define TESTNET
#include <platon/platon.hpp>
#include <string>
using namespace platon;

CONTRACT storge_str : public platon::Contract{
   public:

     ACTION void init(){}
      
      ACTION void set_string(const std::string &name){
          DEBUG("storge_str set_string", "name:", name);
          str.self() = name;
      }
      
      CONST const std::string get_string(){
          DEBUG("storge_str get_string", "name:", str.self());
          return str.self();
      }

      
   private:
      platon::StorageType<"str"_n, std::string> str;
};

PLATON_DISPATCH(storge_str, (init)(set_string)(get_string))

**phenomenon：**
When call B contract through A contract, and then query the result of B contract. Not as expected
#### Backtrace

````
[backtrace]
````

**Comment by jatel** [comment]
You can use the make_address method to convert a string Address to an internal Address of type Address
Such as:
#define TESTNET
std::string target_address = "lax10jc0t4ndqarj4q6ujl3g3ycmufgc77epxg02lt";
auto result = make_address(target_address);
if(result.second) Address address = result.first;

**Comment by hudenian** [comment]
thanks very much
