### ISSUE TITLE
During the pressure test, node panic: leveldb: internal key ""

### ISSUE THREAD

**Issue by shinnng** [PlatONnetwork/PlatON-Go#1367]
platon version：0.12.1

panic: leveldb: internal key "", len=0: invalid length

goroutine 94 [running]:
github.com/PlatONnetwork/PlatON-Go/vendor/github.com/syndtr/goleveldb/leveldb.internalKey.assert(...)
	/home/platon/jenkins/workspace/PlatON/Build_Ubuntu/build/_workspace/src/github.com/PlatONnetwork/PlatON-Go/vendor/github.com/syndtr/goleveldb/leveldb/key.go:111
github.com/PlatONnetwork/PlatON-Go/vendor/github.com/syndtr/goleveldb/leveldb.internalKey.ukey(0xc193bcc000, 0x0, 0xc000000, 0xb255e6d, 0xc1496fb260, 0x20)
	/home/platon/jenkins/workspace/PlatON/Build_Ubuntu/build/_workspace/src/github.com/PlatONnetwork/PlatON-Go/vendor/github.com/syndtr/goleveldb/leveldb/key.go:116 +0x13b
github.com/PlatONnetwork/PlatON-Go/vendor/github.com/syndtr/goleveldb/leveldb.(*iComparer).Compare(0xc0001c13f0, 0xc193bcc000, 0x0, 0xc000000, 0xc1496fb260, 0x28, 0x28, 0xffffffffffffffff)
	/home/platon/jenkins/workspace/PlatON/Build_Ubuntu/build/_workspace/src/github.com/PlatONnetwork/PlatON-Go/vendor/github.com/syndtr/goleveldb/leveldb/comparer.go:38 +0x4c
github.com/PlatONnetwork/PlatON-Go/vendor/github.com/syndtr/goleveldb/leveldb/memdb.(*DB).findGE(0xc0b3919260, 0xc1496fb260, 0x28, 0x28, 0x423801, 0x2b2172, 0x423700)
	/home/platon/jenkins/workspace/PlatON/Build_Ubuntu/build/_workspace/src/github.com/PlatONnetwork/PlatON-Go/vendor/github.com/syndtr/goleveldb/leveldb/memdb/memdb.go:219 +0x169
github.com/PlatONnetwork/PlatON-Go/vendor/github.com/syndtr/goleveldb/leveldb/memdb.(*DB).Put(0xc0b3919260, 0xc1496fb260, 0x28, 0x28, 0x0, 0x0, 0x0, 0x0, 0x0)
	/home/platon/jenkins/workspace/PlatON/Build_Ubuntu/build/_workspace/src/github.com/PlatONnetwork/PlatON-Go/vendor/github.com/syndtr/goleveldb/leveldb/memdb/memdb.go:281 +0xd9
github.com/PlatONnetwork/PlatON-Go/vendor/github.com/syndtr/goleveldb/leveldb.(*Batch).putMem(0xc03405f400, 0x692384f, 0xc0b3919260, 0x1, 0x692384f)
	/home/platon/jenkins/workspace/PlatON/Build_Ubuntu/build/_workspace/src/github.com/PlatONnetwork/PlatON-Go/vendor/github.com/syndtr/goleveldb/leveldb/batch.go:219 +0x27b
github.com/PlatONnetwork/PlatON-Go/vendor/github.com/syndtr/goleveldb/leveldb.(*DB).writeLocked(0xc0000a41a0, 0xc03405f400, 0x0, 0x1, 0x0, 0x0)
	/home/platon/jenkins/workspace/PlatON/Build_Ubuntu/build/_workspace/src/github.com/PlatONnetwork/PlatON-Go/vendor/github.com/syndtr/goleveldb/leveldb/db_write.go:238 +0x4e2
github.com/PlatONnetwork/PlatON-Go/vendor/github.com/syndtr/goleveldb/leveldb.(*DB).Write(0xc0000a41a0, 0xc03405f400, 0x0, 0x2176d50, 0xc0f243af50)
	/home/platon/jenkins/workspace/PlatON/Build_Ubuntu/build/_workspace/src/github.com/PlatONnetwork/PlatON-Go/vendor/github.com/syndtr/goleveldb/leveldb/db_write.go:317 +0x2d1
github.com/PlatONnetwork/PlatON-Go/ethdb.(*ldbBatch).Write(0xc132751560, 0x4c3, 0x20)
	/home/platon/jenkins/workspace/PlatON/Build_Ubuntu/build/_workspace/src/github.com/PlatONnetwork/PlatON-Go/ethdb/database.go:401 +0x40
github.com/PlatONnetwork/PlatON-Go/trie.(*Database).UselessGC(0xc000215440, 0x1)
	/home/platon/jenkins/workspace/PlatON/Build_Ubuntu/build/_workspace/src/github.com/PlatONnetwork/PlatON-Go/trie/database.go:571 +0x449
github.com/PlatONnetwork/PlatON-Go/core.(*BlockChain).WriteBlockWithState(0xc00051a000, 0xc154047280, 0xc043063000, 0xf0, 0xf0, 0xc11bd98120, 0x0, 0x0, 0x0)
	/home/platon/jenkins/workspace/PlatON/Build_Ubuntu/build/_workspace/src/github.com/PlatONnetwork/PlatON-Go/core/blockchain.go:988 +0x1dd4
github.com/PlatONnetwork/PlatON-Go/miner.(*worker).resultLoop(0xc00000c1e0)
	/home/platon/jenkins/workspace/PlatON/Build_Ubuntu/build/_workspace/src/github.com/PlatONnetwork/PlatON-Go/miner/worker.go:700 +0xd07
created by github.com/PlatONnetwork/PlatON-Go/miner.newWorker
	/home/platon/jenkins/workspace/PlatON/Build_Ubuntu/build/_workspace/src/github.com/PlatONnetwork/PlatON-Go/miner/worker.go:250 +0x856

**Comment by benbaley** [comment]
Not sure if there's anything we can do about it.
ref: [Ethereum#16897](https://github.com/ethereum/go-ethereum/issues/16897)
