### ISSUE TITLE
return error value of address.balance

### ISSUE THREAD

**Issue by qcxiao** [PlatONnetwork/PlatON-Go#1376]
Hi there,

contract return error value of address.balance

#### contract source

`
pragma solidity ^0.4.12;

contract Test {
  function balanceOfEther(address user) public constant returns (uint256) { return user.balance; } 
}
`

#### Expected behaviour
> platon.getBalance('lax1uqug0zq7rcxddndleq4ux2ft3tv6dqljphydrl')
9.982963565996393852434677958537360216e+36

#### Actual behaviour
error value returned using java sdk

-----------------
address:lax1uqug0zq7rcxddndleq4ux2ft3tv6dqljphydrl, balance:115792089237316195423570985008687907853269984665631340667420729232106129639935
-----------------

**Comment by benbaley** [comment]
fixed in #1375
