### ISSUE TITLE
The contract uses DEBUG printing, resulting in unexpected results which #undef NDEBUG is not added to the contract. 

### ISSUE THREAD

**Issue by liweichengcode** [PlatONnetwork/PlatON-Go#1378]
#include <platon/platon.hpp>
#include <string>
using namespace std;
using namespace platon;

CONTRACT PagingQuery : public platon::Contract{

    private:
      platon::StorageType<"vecstorage"_n, std::vector<std::string>> storage_vector_string;

    public:
        ACTION void init(){}

        ACTION void insertVectorValue(const std::string &my_value)
     {
        storage_vector_string.self().push_back(my_value);
     }

        CONST uint64_t getVectorSize()
     {
       return storage_vector_string.self().size();
     }

        CONST std::string getPagingQuery(uint64_t CurrentPage, uint64_t PageMaxSize)
     {
        int vecSize = 0;
        int pages = 0;
        vecSize = storage_vector_string.self().size();
        pages = vecSize / PageMaxSize;
        if(0 != vecSize % PageMaxSize)
        {
            pages += 1;
        }

        if(CurrentPage <= 0)
        {
        	return "";
        }
        else if(CurrentPage > pages)
        {
            return "";
        }
        int nStartIndex = (CurrentPage - 1) * PageMaxSize;
        int nEndIndex = nStartIndex + PageMaxSize - 1;
        if(nEndIndex >= vecSize)
        {
        	nEndIndex = vecSize - 1;
        }
       
        DEBUG("nStartIndex","nStartIndex",nStartIndex);
        DEBUG("nEndIndex","nEndIndex",nEndIndex);
        std::string strVecInfo = "{";
        strVecInfo += "\"";
        strVecInfo += "PageTotal";
        strVecInfo += "\":";
        strVecInfo += to_string(pages);
        strVecInfo += ",";
        strVecInfo += "\"";
        strVecInfo += "Data";
        strVecInfo += "\":[";

        for(int i = nStartIndex; i <= nEndIndex; i++)
        {
            std::string strTmp = "";
            strTmp = storage_vector_string.self().at(i);
            DEBUG("strTmp","strTmp",strTmp);
            strVecInfo += strTmp + ",";
        }

        strVecInfo.pop_back();
        strVecInfo += "]}";
        char* buf = (char*)malloc(strVecInfo.size() + 1);
        memset(buf, 0, strVecInfo.size()+1);
        strcpy(buf, strVecInfo.c_str());
        return buf;
     }
};

PLATON_DISPATCH(PagingQuery, (init)(insertVectorValue)(getVectorSize)(getPagingQuery))

**Comment by jatel** [comment]
The -z optimization of wasm-opt was too aggressive, which caused the effective logic in the loop to be optimized away, which did not conform to the original actual code logic.

https://github.com/PlatONnetwork/PlatON-CDT/pull/166，The latest version has fixed this problem.
