### ISSUE TITLE
The new account lacks the StorageKeyPrefix prefix

### ISSUE THREAD

**Issue by benbaley** [PlatONnetwork/PlatON-Go#1381]
Parallel transaction version, the new account lacks the StorageKeyPrefix prefix, resulting in a bad block when synchronizing the serial version block

**Comment by niuxiaojie81** [comment]
The StorageKeyPrefix for account was not specified when the new stateObject was created, resulting in inconsistent stateRoot after the two versions executed the transaction

**Comment by benbaley** [comment]
closed by done
