### ISSUE TITLE
WASM contract execution is performed, the contract address is entered into the nonexistent contract address, and after the transaction is sent, the node stops getting out of the block

### ISSUE THREAD

**Issue by xuhuiyu1** [PlatONnetwork/PlatON-Go#1389]
#1375 ## System information
PlatON version: `platon 0.13.0`
OS & Version: ubuntu
Commit hash : aa8cdb5240dfe96e2465bd7f3ecff0dd7878d325

#### Steps to reproduce the behaviour
WASM contract execution is performed, the contract address is entered into the nonexistent contract address, sent transaction 

#### Expected behaviour
The transaction fails and the node runs normally

#### Actual behaviour
A panic error occurred in the chain parallel transaction, causing the node process to exit and stop the block

**Comment by niuxiaojie81** [comment]
To address does not exist, it is regarded as a normal transfer transaction, but the transaction transfer amount is 0, so the stateObject is empty, delete it and do not write it into statedb

**Comment by xuhuiyu1** [comment]
This issue  proved to be fixed
