### ISSUE TITLE
solc0.4.12 compile error

### ISSUE THREAD

**Issue by qcxiao** [PlatONnetwork/PlatON-Go#1403]
Hi there,

partial evm Contract，solc0.4.12 compile error
#### System information

PlatON version: `platon version`
OS & Version: Windows/Linux/OSX
Commit hash : (if `develop`)

#### Expected behaviour
compile success

#### Actual behaviour
compile error
`./solc-0.4.12: error while loading shared libraries: libboost_filesystem.so.1.65.1: cannot open shared object file: No such file or directory`

#### contract source
`
pragma solidity ^0.4.12;

contract AddressBalance {
    function balanceOfPlatON(address user) public constant returns (uint256) {
        return user.balance;
    }
}
`

**Comment by dugusanfeng** [comment]
编译出的solc依赖编译出来的so文件，不同版本的so文件是有差异的，导致0.4.12-0.4.15版本没法共同存在使用，需要在编译的时候指定static配置,命令如下：
cmake -DCMAKE_BUILD_TYPE=Release -DTESTS=0 -DSTATIC_LINKING=1 .. && make -j4
