### ISSUE TITLE
Node carshed after 50 consecutive RPC calls

### ISSUE THREAD

**Issue by cool007zqw** [PlatONnetwork/PlatON-Go#1478]
Hi there,

#### System information

PlatON version: `0.13.0`
OS & Version: Ubuntu 18.04 on WSL

#### Expected behaviour
node excutes the RPC call normally

#### Actual behaviour
node crashes

#### Steps to reproduce the behaviour
using the JS SDK

````js

var Web3 = require('@platonnetwork/web3');

var web3 = new Web3('http://127.0.0.1:6478');

for (let index = 0; index < 50; index++) {
    web3.platon.personal.newAccount('1').then(console.log);
}
````

#### Backtrace

````log
unexpected fault address 0xc31f91a020
fatal error: fault
Segmentation fault (core dumped)
````

**Comment by benbaley** [comment]
It seems that the process was killed by system because of OOM
![image](https://user-images.githubusercontent.com/45843736/89771533-0a3ff480-db33-11ea-93ce-1241ef249a5d.png)

**Comment by benbaley** [comment]
under linux we can only ask the operating system to take back memory from the processes address space, we cannot tell the operating system to do this. The operating system can, and often does, ignore this request unless it is under memory pressure from other processes.
The correct way is not to expose this RPC interface to the outside, and do not call this interface frequently when using it yourself

**Comment by cool007zqw** [comment]
Thanks for your infomation. I'll be careful on this.
