### ISSUE TITLE
When the pledge amount of the verification node list is the same, the node ranking order is wrong

### ISSUE THREAD

**Issue by qiusese** [PlatONnetwork/PlatON-Go#1499]
PlatON version: `0.13.1`

1、Pledge two nodes with the same amount
2、Inconsistent pledge block height
3、The ranking order of pledge nodes is wrong

**Comment by cheng762** [comment]
this is a bug,When the version and amount are the same, they should be sorted in the order of pledge

**Comment by benbaley** [comment]
fixed in #1501
