### ISSUE TITLE
block.timestamp is not consistent with ethereum

### ISSUE THREAD

**Issue by joeyxp** [PlatONnetwork/PlatON-Go#1505]
Hi there,

please note that this is an issue tracker reserved for bug reports and feature requests.

#### System information

PlatON version: `0.13.1`
OS & Version: Windows/Linux/OSX
Commit hash : (if `develop`)

#### Expected behaviour
Just like ethereum, block.timestamp is seconds.

#### Actual behaviour
block.timestamp is milliseconds.

#### Steps to reproduce the behaviour
`modifier ensure(uint deadline) {
        require(deadline >= block.timestamp, 'EXPIRED');
        _;
   }
`
Notice deadline should be milliseconds.

#### Backtrace

````
[backtrace]
````

**Comment by benbaley** [comment]
this is how we design it

**Comment by benbaley** [comment]
Closed due to lack of feedback for a long time
