### ISSUE TITLE
Scenario: Modifying the benefit address of the node does not take effect in real time, but takes effect after 3 blocks

### ISSUE THREAD

**Issue by zjsunzone** [PlatONnetwork/PlatON-Go#1512]
Hi there,

Scenario: Modifying the benefit address of the node does not take effect in real time, but takes effect after 3 blocks.

#### System information

PlatON version: `platon version`
OS & Version: Windows/Linux/OSX
Commit hash : (if `develop`)

#### Expected behaviour

After the beneficiary address is modified, the income can be obtained in real time.

#### Actual behaviour

After the beneficiary address is modified, there is an interval of 3 blocks to get the income.

#### Steps to reproduce the behaviour

Scenario: Modify the node's benefit address.

**Comment by benbaley** [comment]
fixed in #1515
