### ISSUE TITLE
cmd/abigen generate go eth code，cannot use on platon testnet

### ISSUE THREAD

**Issue by zongweiyang** [PlatONnetwork/PlatON-Go#1538]
Hi there,

please note that this is an issue tracker reserved for bug reports and feature requests.

#### System information

PlatON version: `platon testnet`
OS & Version: Linux
Commit hash : (`0.13.1_beta`)

#### Expected behaviour
go contract object can be used on platon testnet.

#### Actual behaviour
generate go contract wrapper class ,but import and sign method base on eth

#### Steps to reproduce the behaviour
abigen --bin=example.bin --abi=example.abi --pkg=example --out=example.go

#### Backtrace

````
[backtrace]
````

**Comment by cheng762** [comment]
this is a bug for import wrong pakges,will fix in branch develop and feature/alaya-launching

**Comment by benbaley** [comment]
close by done
