### ISSUE TITLE
use go.mod cannot download submode as (git submodule update --init .) or 

### ISSUE THREAD

**Issue by zongweiyang** [PlatONnetwork/PlatON-Go#1540]
`
# github.com/PlatONnetwork/PlatON-Go/crypto/bls
../../github.com/PlatONnetwork/PlatON-Go/crypto/bls/bls.go:4:10: fatal error: bls/bls.h: No such file or directory
 #include <bls/bls.h>
          ^~~~~~~~~~~
compilation terminated.
`

**Comment by zongweiyang** [comment]
go.mod的模式 submodule 没法解决，影响使用，只能使用replace的方式

**Comment by benbaley** [comment]
bls lib is not golang pkg， you must init it by `git submodule update --init`  or add `--recursive` when cloning the repository
