### ISSUE TITLE
VersionProposalSupportRate is 2500, version proposal was passed, node panic at EndVotingBlock

### ISSUE THREAD

**Issue by shinnng** [PlatONnetwork/PlatON-Go#1548]
VersionProposalSupportRate is 2500, version proposal was passed, node panic at EndVotingBlock

version: 0.13.2-alaya

panic: The Next Round Validator is empty, blockNumber: 180

goroutine 147 [running]:
github.com/PlatONnetwork/PlatON-Go/x/plugin.(*StakingPlugin).Election(0xc00009dd80, 0x0, 0x0, 0x0, 0x0, 0xc01c824c80, 0x17219e0, 0xc01c826480, 0x0, 0x0)
	/root/go_workspace/src/github.com/PlatONnetwork/PlatON-Go/x/plugin/staking_plugin.go:1947 +0x3aad
github.com/PlatONnetwork/PlatON-Go/x/plugin.(*StakingPlugin).EndBlock(0xc00009dd80, 0x0, 0x0, 0x0, 0x0, 0xc01c824c80, 0x17219e0, 0xc01c826480, 0x0, 0x0)
	/root/go_workspace/src/github.com/PlatONnetwork/PlatON-Go/x/plugin/staking_plugin.go:171 +0x676
github.com/PlatONnetwork/PlatON-Go/core.(*BlockChainReactor).EndBlocker(0xc000118180, 0xc01c824c80, 0x17219e0, 0xc01c826480, 0x16e5380, 0x488778)
	/root/go_workspace/src/github.com/PlatONnetwork/PlatON-Go/core/blockchain_reactor.go:312 +0x58d
github.com/PlatONnetwork/PlatON-Go/miner.(*worker).commit(0xc0000c9c00, 0x0, 0xc0000c8801, 0xbfd92c46b7389d56, 0x19b9fb7a53, 0x22efa80, 0x6, 0x2)
	/root/go_workspace/src/github.com/PlatONnetwork/PlatON-Go/miner/worker.go:1134 +0x1f4
github.com/PlatONnetwork/PlatON-Go/miner.(*worker).commitNewWork(0xc0000c9c00, 0xc01c90f588, 0x0, 0x1751c81052d, 0xc028cb5200, 0xbfd92c46d363fd13, 0x19d1c1a3eb, 0x22efa80, 0x0, 0x0)
	/root/go_workspace/src/github.com/PlatONnetwork/PlatON-Go/miner/worker.go:1052 +0x1fa7
github.com/PlatONnetwork/PlatON-Go/miner.(*worker).mainLoop(0xc0000c9c00)
	/root/go_workspace/src/github.com/PlatONnetwork/PlatON-Go/miner/worker.go:529 +0x96e
created by github.com/PlatONnetwork/PlatON-Go/miner.newWorker
	/root/go_workspace/src/github.com/PlatONnetwork/PlatON-Go/miner/worker.go:264 +0x851

**Comment by benbaley** [comment]
fixed in #1550
