### ISSUE TITLE
The staking amount of foundation nodes is 10000 lat, zeroProduce slashing will lead the nodes tobe unstaking, it is suggested to increase the staking amount

### ISSUE THREAD

**Issue by shinnng** [PlatONnetwork/PlatON-Go#1549]
The staking amount of foundation nodes is 10000 lat, zeroProduce slashing will lead the nodes tobe unstaking, it is suggested to increase the staking amount

version: 0.13.2-alaya

**Comment by benbaley** [comment]
had adjust to 10500 ref #1546
