### ISSUE TITLE
keytool file name conflict.

### ISSUE THREAD

**Issue by benbaley** [PlatONnetwork/PlatON-Go#1571]
Hi there,

The keytool file name is easy to conflict with the keytool that comes with jdk, causing various problems when using it.

#### System information
platon/alaya

PlatON version: `platon version`
OS & Version: Windows/Linux/OSX
Commit hash : (if `develop`)

#### Actual behaviour
![image](https://user-images.githubusercontent.com/45843736/96987356-7ab4ba00-1555-11eb-876e-cf5454509cf6.png)
![image](https://user-images.githubusercontent.com/45843736/96987372-80120480-1555-11eb-8d9d-ed4ff7462c2a.png)

**Comment by WeiLoy** [comment]
The name has been redefined

**Comment by Anasuya-Smith** [comment]
> The name has been redefined

Could you please give the redefined name? I am also getting the same error as above, and couldn't able to generate the keypair

**Comment by Anasuya-Smith** [comment]
Hi, got it solved.
The keytool command/binary is supposed to be called as below.

$ ./keytool genkeypair

without ./ (as shown in the readme.md file), it throws error (as shown in the picture above)

**Comment by benbaley** [comment]
> > The name has been redefined
> 
> Could you please give the redefined name? I am also getting the same error as above, and couldn't able to generate the keypair

The new file name are:
Alaya: alayakey
PlatON: platonkey

and where did you see the explanation about `keytool`? maybe we forgot to update the document

**Comment by Anasuya-Smith** [comment]
Thank you @benbaley 

The readme.md file along with the PlatON master

https://github.com/PlatONnetwork/PlatON-Go/blob/master/README.md

**Comment by benbaley** [comment]
> Thank you @benbaley
> 
> The readme.md file along with the PlatON master
> 
> https://github.com/PlatONnetwork/PlatON-Go/blob/master/README.md

It has not updated yet and we will fixed it later
thanks
