### ISSUE TITLE
recommend to support both locked and free balance staking

### ISSUE THREAD

**Issue by KenianShi** [PlatONnetwork/PlatON-Go#1582]
Hi there,

When a node staking, he can only choose to stake from the locked amount of the account or the free amount. Since staking has a minimum limit, it cannot staking when the amount in both accounts is less than the minimum amount. It is recommended to support both locked and free balance staking

#### System information

PlatON version: 0.13.2
OS & Version: Windows/Linux/OSX
Commit hash :da6a7b338fa4b0ae2f11a070610d5bee48b30b92

**Comment by blueatsky** [comment]
> Hi there,
> 
> When a node staking, he can only choose to stake from the locked amount of the account or the free amount. Since staking has a minimum limit, it cannot staking when the amount in both accounts is less than the minimum amount. It is recommended to support both locked and free balance staking
> 
> #### System information
> PlatON version: 0.13.2
> OS & Version: Windows/Linux/OSX
> Commit hash :da6a7b338fa4b0ae2f11a070610d5bee48b30b92

       你的建议很棒，给你点赞。关于节点“进入门槛”我也有一些想法，欢迎大家一起讨论。

1. 不应设置过高的进入门槛，比如初期的10000对后来者就显得过高了。总质押量=节点质押+所有人委托。这样的好处是更平等，更多优秀的后来节点可以加入验证节点的大家庭，并且前期进入的节点也要积极去运营，才能继续获得席位。
2. 基金会在初期发挥维护网络稳定的作用，对于符合“标准”的节点进行扶持，标准可以是在社区活跃，代码贡献，工具开发等。扶持也不应该直接把token(包括锁定的）发送到节点账号，应该由基金会直接委托节点。利益面前容易导致作恶。


欢迎大家一起交流，我是国产凌凌漆

**Comment by KenianShi** [comment]
> > Hi there,
> > When a node staking, he can only choose to stake from the locked amount of the account or the free amount. Since staking has a minimum limit, it cannot staking when the amount in both accounts is less than the minimum amount. It is recommended to support both locked and free balance staking
> > #### System information
> > PlatON version: 0.13.2
> > OS & Version: Windows/Linux/OSX
> > Commit hash :da6a7b338fa4b0ae2f11a070610d5bee48b30b92
> 
> ```
>    你的建议很棒，给你点赞。关于节点“进入门槛”我也有一些想法，欢迎大家一起讨论。
> ```
> 
> 1. 不应设置过高的进入门槛，比如初期的10000对后来者就显得过高了。总质押量=节点质押+所有人委托。这样的好处是更平等，更多优秀的后来节点可以加入验证节点的大家庭，并且前期进入的节点也要积极去运营，才能继续获得席位。
> 2. 基金会在初期发挥维护网络稳定的作用，对于符合“标准”的节点进行扶持，标准可以是在社区活跃，代码贡献，工具开发等。扶持也不应该直接把token(包括锁定的）发送到节点账号，应该由基金会直接委托节点。利益面前容易导致作恶。
> 
> 欢迎大家一起交流，我是国产凌凌漆

我觉得凌凌漆的提案挺好的，由基金会委托，在前期，这样也有利于网络的发展。一旦有验证人作恶，或者利用规则漏洞，做出对整个网络发展不利的事情，基金会完全可以撤销委托。有利于让真正做出贡献的人得到奖励，作恶的人得到惩罚。

**Comment by jiangshangqifeng** [comment]
> Hi there,
> 
> When a node staking, he can only choose to stake from the locked amount of the account or the free amount. Since staking has a minimum limit, it cannot staking when the amount in both accounts is less than the minimum amount. It is recommended to support both locked and free balance staking
> 
> #### System information
> PlatON version: 0.13.2
> OS & Version: Windows/Linux/OSX
> Commit hash :da6a7b338fa4b0ae2f11a070610d5bee48b30b92

质押金优先使用锁仓金额，如果锁仓金额不足，再使用自有金额，看看这样是不是就可以了？ 欢迎一起交流

**Comment by benbaley** [comment]
close by done
