### ISSUE TITLE
Actively receive the commissioned reward income, the amount is insufficient.

### ISSUE THREAD

**Issue by zjsunzone** [PlatONnetwork/PlatON-Go#1583]
Hi there,

Actively receive the commissioned reward income, the amount is insufficient.

**Comment by benbaley** [comment]
This is a bug and have fixed in #1584

**Comment by benbaley** [comment]
[account.md](https://github.com/PlatONnetwork/PlatON-Go/files/6606799/account.md)

**Comment by benbaley** [comment]
节点f2ec2830850Epoch216在epoch216的总委托量为3185100027705555555556
在块高2322005，用户atp1zhe8zecq7evp897azxssudk4t9z0a7emp8fulx，发起了委托余额不足的交易，导致79382407555555555556的委托被错误计算，此时奖励账户中剩余委托为3105717620150000000000
在块高2322221，用户atp1spk9z7j5jd32zz0kvg9eclxu43zh46tesu9lp6,领取委托:1344914050000000000    ，委托账户剩余委托3104372706100000000000,
在块高2322394，用户atp1zhe8zecq7evp897azxssudk4t9z0a7emp8fulx,领取委托:79382407555555555556   ，委托账户剩余委托3024990298544444444444,
在块高2322729，用户atp1axmlplkkzuqr8k792a5zzpq9px690a7gcay4zs,领取委托:53000000000000000000   ，委托账户剩余委托2971990298544444444444,
在块高2326981，用户atp14vzjl8zluqhntk4zzm330ff42yxtpmzkd9lxa0,领取委托:653261938360000000000  ，委托账户剩余委托2318728360184444444444,
在块高2328058，用户atp1uwstdjccjkzttlg9dd0dm0mganezj0sjexkxy5,领取委托:500000000000000000000  ，委托账户剩余委托1818728360184444444444,
在块高2328271，用户atp1ta0c3lmmqmpvzr73zem5ztg8lvqe23tpgvvncy,领取委托:2069936350000000000    ，委托账户剩余委托1816658423834444444444,
在块高2328990，用户atp134l5np4zycy78kkq4fy7x6dr84j48jnvw6z3l7,领取委托:194557201950000000000  ，委托账户剩余委托1622101221884444444444,
在块高2329328，用户atp1mau3m06ykq7n94pd6g5zvjn7cplz8pcq3xr3cn,领取委托:503000000000000000000  ，委托账户剩余委托1119101221884444444444,
在块高2330580，用户atp1aq8n8rxydfyz2rjjvu8r86nelyypuynnu5r3np,领取委托:1000000000000000000    ，委托账户剩余委托1118101221884444444444,
在块高2331565，用户atp15vty82zjgf3h2klp73g5ucexry24w2jx2rh2dn,领取委托:1001000000000000000000 ，委托账户剩余委托117101221884444444444,
在块高2332161，用户atp10xctkwvyladt8lalkcdkvcywdscvksnelauz7p,领取委托:178553352960000000000  ，委托账户剩余委托0,
导致以下账户没有委托奖励可以领取
atp12trrqnpqkj2kn03cwz5ae4v7lfshvqetqrkeez,委托金额:1000000000000000000,
atp143ml5dd3qz3wykmg4p3vnp9eqlugd9sxmgpsux,委托金额:2000000000000000000,
atp1687slxxcghuhxgv3uy6v2epftn8nhn9jss2sd6,委托金额:9361750080000000000,
atp1dtmhmexryrg7h8tzsufrg4d9y48sne7rr5ezsj,委托金额:1150000000000000000,
atp1y4arxmjpy5grkp9attefax07z56wcuq2n5937u,委托金额:2806452320000000000,
atp1z3w63q0q6rnrqw55s4hhu7ewfep0vcqaxt508d,委托金额:1612074080000000000,


--------------------


节点f1efed4e853d00ff3f在epoch216的总委托量为2980993136113333333334
在块高2322007，用户atp1zhe8zecq7evp897azxssudk4t9z0a7emp8fulx，发起了委托余额不足的交易，导致115859001333333333334的委托被错误计算，此时奖励账户中剩余委托为2865134134780000000000
在块高2322398，用户atp1zhe8zecq7evp897azxssudk4t9z0a7emp8fulx,领取委托:115859001333333333334,   委托账户剩余委托:2749275133446666666666,
在块高2322400，用户atp1jzxeyyntlypr5r44exzgdgkzdrgt7ccp9n3tc4,领取委托:280388808000000000000,   委托账户剩余委托:2468886325446666666666,
在块高2322741，用户atp18fjgxreunevg426whpx9zg4583hrjz46rf8mqf,领取委托:2000000000000000000,     委托账户剩余委托:2466886325446666666666,
在块高2326981，用户atp14vzjl8zluqhntk4zzm330ff42yxtpmzkd9lxa0,领取委托:1569000000000000000000， 委托账户剩余委托:897886325446666666666,
在块高2331565，用户atp15vty82zjgf3h2klp73g5ucexry24w2jx2rh2dn,领取委托:731000000000000000000,   委托账户剩余委托:166886325446666666666,
在块高2332274，用户atp1fz9tlsfz465xyns3h8l3ylxjrkmjkgg63k6hh2,领取委托:101795326780000000000,   委托账户剩余委托:65090998666666666666,
在块高2680031，用户atp1vtwdqhf2e4e08vyn4pam2tfv68zfu9mgns8dyx,领取委托:180950000000000000000,   委托账户剩余委托0
因此节点f1efed4e853d00ff3f在epoch216没有未发放奖励的账户


-------------------------


节点fff1010bbf176在epoch216的总委托量为3405198514793333333334
在块高2322006，用户atp1zhe8zecq7evp897azxssudk4t9z0a7emp8fulx，发起了委托余额不足的交易，导致86895433333333333334的委托被错误计算，此时奖励账户中剩余委托为3318303081460000000000
在块高,2322221,用户atp1spk9z7j5jd32zz0kvg9eclxu43zh46tesu9lp6,领取委托:1059556200000000000, 委托账户剩余委托3317243525260000000000,
在块高,2322394,用户atp1zhe8zecq7evp897azxssudk4t9z0a7emp8fulx,领取委托:86895433333333333334,委托账户剩余委托3230348091926666666666,
在块高,2322400,用户atp1jzxeyyntlypr5r44exzgdgkzdrgt7ccp9n3tc4,领取委托:73418062000000000000,委托账户剩余委托3156930029926666666666,
在块高,2322407,用户atp1gf6h9p9yh3y64z2vlgqadzn7crgyhe3am3at7h,领取委托:48526750000000000000,委托账户剩余委托3108403279926666666666,
在块高,2322729,用户atp1axmlplkkzuqr8k792a5zzpq9px690a7gcay4zs,领取委托:56000000000000000000,委托账户剩余委托3052403279926666666666,
在块高,2322733,用户atp154238hmgqdgxpfcsqfulul2j2uztuz9nlphrgq,领取委托:6000000000000000000, 委托账户剩余委托3046403279926666666666,
在块高,2325035,用户atp1aq2jk2nqp7c9kecevl2y38hz95lek3tvwfpfn8,领取委托:356835677020000000000,委托账户剩余委托2689567602906666666666,
在块高,2328271,用户atp1ta0c3lmmqmpvzr73zem5ztg8lvqe23tpgvvncy,领取委托:20163036240000000000, 委托账户剩余委托2669404566666666666666,
在块高,2329235,用户atp179daguqnx00gnjvhl6nm5maps3nv30x847k5w7,领取委托:100000000000000000000,委托账户剩余委托2569404566666666666666,
在块高,2329328,用户atp1mau3m06ykq7n94pd6g5zvjn7cplz8pcq3xr3cn,领取委托:1544000000000000000000,委托账户剩余委托1025404566666666666666,
在块高,2330580,用户atp1aq8n8rxydfyz2rjjvu8r86nelyypuynnu5r3np,领取委托:11300000000000000000,委托账户剩余委托1014104566666666666666,
在块高,2331565,用户atp15vty82zjgf3h2klp73g5ucexry24w2jx2rh2dn,领取委托:1101000000000000000000,委托账户剩余委托0
因此节点fff1010bbf176在epoch216没有未发放奖励的账户


--------------
节点fff1010bbf176在epoch475的总委托量为10986475785670000000000
在块高5106251，用户atp1jzxeyyntlypr5r44exzgdgkzdrgt7ccp9n3tc4，发起了委托余额不足的交易，导致3292772000000000000的委托被错误计算，此时奖励账户中剩余委托为10983183013670000000000
在块高5106251，用户atp1zhe8zecq7evp897azxssudk4t9z0a7emp8fulx，发起了委托余额不足的交易，导致44078471000000000000的委托被错误计算，此时奖励账户中剩余委托为10939104542670000000000
在块高5106251，用户atp1hxwwkpmuw946g7qehzm4nazh46t4e7g065xdt3，发起了委托余额不足的交易，导致182148250000000000000的委托被错误计算，此时奖励账户中剩余委托为10756956292670000000000
在块高,5106451,用户atp12jsctngpm8tn30scuc0dmpg9ncsc82rlz9vwjj,,领取委托10167000000000000000000,委托账户剩余委托589956292670000000000,
在块高,5106701,用户atp1zhe8zecq7evp897azxssudk4t9z0a7emp8fulx,,领取委托44078471000000000000,委托账户剩余委托545877821670000000000,
在块高,5106707,用户atp1jzxeyyntlypr5r44exzgdgkzdrgt7ccp9n3tc4,,领取委托3292772000000000000,委托账户剩余委托542585049670000000000,
在块高,5111788,用户atp1hxwwkpmuw946g7qehzm4nazh46t4e7g065xdt3,,领取委托182148250000000000000,委托账户剩余委托360436799670000000000,
在块高,5113852,用户atp1806v5kyy8g4dfkfqfk47hvsvyfq9dh3u0h748t,,领取委托200000000000000000000,委托账户剩余委托160436799670000000000,
在块高,5160801,用户atp1y4arxmjpy5grkp9attefax07z56wcuq2n5937u,,领取委托202647870840000000000,委托账户剩余委托0

剩余未领取的账户
atp1rek8y8nz07tdp4v469xmuyymar8qe0pnejknyw,委托金额:18729736290000000000
atp1szy8d7094kl0q82la9l2pfz3hjy99zh730flw4,委托金额:89940584120000000000
atp15wekgs8q07rs24dmnwmdgd0qhqwvqlus6dh5g5,委托金额:62385695880000000000
atp1cmfc2nea3am2znutaunaze2q8t6ttyrcu7mjqh,委托金额:16252405540000000000
