### ISSUE TITLE
Rechange the delegate reward ratio to the original value, the unStakeFreezeDuration parameter does not take effect

### ISSUE THREAD

**Issue by jiangshangqifeng** [PlatONnetwork/PlatON-Go#1602]
change ratio from 70% to 75% and rechange it to 70% immediately,  failure was expected, but it successed.

**Comment by blueatsky** [comment]
补充一下：
14：42通过下面的命令更新了分红比例70%->75%
mtool-client update_validator --delegated-reward-rate 7500 --keystore $MTOOLDIR/keystore/staking.json --config $MTOOLDIR/validator/validator_config.json
命令执行成功
17:15通过下面的命令更新了节点名称和描述，结果分红比例跟着降低了。mtool-client update_validator --name Fengshan --introduction "委托给Fengshan，我们都是凤山人" --keystore $MTOOLDIR/keystore/staking.json --config $MTOOLDIR/validator/validator_config.json
命令返回结果也成功，但同时在没有加入分红参数的同时，分红比例也变了，75%->70%

**Comment by WeiLoy** [comment]
solved

**Comment by WeiLoy** [comment]
The name has been redefined

**Comment by WeiLoy** [comment]
Resolved
