### ISSUE TITLE
Restricting contract return wrong balance

### ISSUE THREAD

**Issue by jiangshangqifeng** [PlatONnetwork/PlatON-Go#1625]
Hi there,

The balance is wrong in restricting contract when node unstaking

[ref](https://scan.alaya.network/restricting-info?address=atp15ftdv7s5sn7tswnqwegaxrdzhh9cezyaeuv7us)

#### System information

PlatON version: alaya-0.13.2
OS & Version: Windows/Linux/OSX
Commit hash : (if `develop`)

#### Backtrace

````
[backtrace]
````

**Comment by benbaley** [comment]
fixed in #1682
