### ISSUE TITLE
Use ethclient CallContract error

### ISSUE THREAD

**Issue by zonzpoo** [PlatONnetwork/PlatON-Go#1648]
Hi there,

I try to use [CallContract](https://github.com/PlatONnetwork/PlatON-Go/blob/bc8e5d4d4442c25858af68ee44688635482f9c82/ethclient/ethclient.go#L409) function in `ethclient` pkg，funcType is 1102，but got a error message

#### System information

PlatON version: `alaya-0.14.0`
OS & Version: OSX
Commit hash : (if `develop`)

#### Actual behaviour
msg => invalid argument 0: json: cannot unmarshal decoding bech32 failed: checksum failed. Expected pv6qxd, got 000002. into Go struct field CallArgs.from of type common.Address

#### Backtrace

````
to, _ := common.Bech32ToAddress("atp1zqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqzfyslg3")
msg := ethereum.CallMsg{
    From: to,
    To:   &to,
    Data: buf,
}
client.CallContract(ctx, msg, blockNumber)
````

Should （`To` AND `From`）be  Bech32Address？ but [common.Address](https://github.com/PlatONnetwork/PlatON-Go/blob/bc8e5d4d4442c25858af68ee44688635482f9c82/interfaces.go#L117) represents the 20 byte address of an Ethereum account.

**Comment by benbaley** [comment]
Yes, when you convert common.Address from literal string, the string must Bech32.

**Comment by zonzpoo** [comment]
Can i submit a `merge request` to fix it？and which branch to checkout

**Comment by benbaley** [comment]
> Hi there,
> 
> I try to use [CallContract](https://github.com/PlatONnetwork/PlatON-Go/blob/bc8e5d4d4442c25858af68ee44688635482f9c82/ethclient/ethclient.go#L409) function in `ethclient` pkg，funcType is 1102，but got a error message
> 
> #### System information
> PlatON version: `alaya-0.14.0`
> OS & Version: OSX
> Commit hash : (if `develop`)
> 
> #### Actual behaviour
> msg => invalid argument 0: json: cannot unmarshal decoding bech32 failed: checksum failed. Expected pv6qxd, got 000002. into Go struct field CallArgs.from of type common.Address
> 
> #### Backtrace
> ```
> to, _ := common.Bech32ToAddress("atp1zqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqzfyslg3")
> msg := ethereum.CallMsg{
>     From: to,
>     To:   &to,
>     Data: buf,
> }
> client.CallContract(ctx, msg, blockNumber)
> ```
> 
> Should （`To` AND `From`）be Bech32Address？ but [common.Address](https://github.com/PlatONnetwork/PlatON-Go/blob/bc8e5d4d4442c25858af68ee44688635482f9c82/interfaces.go#L117) represents the 20 byte address of an Ethereum account.

In this case, you can't get error msg when 'Bech32ToAddress' failed
mostly 'Bech32ToAddress' verify the strAddr by hrp(human readable part), if hrp is not current chain's hrp, it return error immediately

**Comment by benbaley** [comment]
Closed due to lack of feedback for a long time
