### ISSUE TITLE
Validators staking shares error

### ISSUE THREAD

**Issue by jiangshangqifeng** [PlatONnetwork/PlatON-Go#1654]
Hi there,

The validator's staking share was wrong when it's status was locking and withdrawing happend

#### System information

PlatON version: `0.14.0`
OS & Version: Windows/Linux/OSX
Commit hash : (if `develop`)

**Comment by cheng762** [comment]
this is a bug，The delegate amount is not handled correctly, resulting in abnormal node weight
，Fixed in 0.16.0。

**Comment by benbaley** [comment]
fixed in #1683
