### ISSUE TITLE
When the upgrade proposal is passed, the node information that is in the zero-block lock status is not updated correctly.

### ISSUE THREAD

**Issue by jiangshangqifeng** [PlatONnetwork/PlatON-Go#1666]
Hi there,

When the upgrade proposal is passed, the node information that is in the zero-block lock status is not updated correctly.
node's version was old and needed to redeclare the version.
#### System information

PlatON version: `0.14.0`
OS & Version: Windows/Linux/OSX
Commit hash : (if `develop`)

#### Actual behaviour

When the upgrade proposal is passed, the node information that is in the zero-block lock status is not updated correctly.
node's version was old and needed to redeclare the version.

#### Steps to reproduce the behaviour

do not need redeclare the version.

#### Backtrace

````
[backtrace]
````

**Comment by benbaley** [comment]
fixed in #1663
