### ISSUE TITLE
频繁调用【ERC721合约】或【ERC20合约】的balanceOf()方法查询同一地址的余额，返回错误码：-3200

### ISSUE THREAD

**Issue by 804259890** [PlatONnetwork/PlatON-Go#1769]
Hi there,

频繁调用ERC721合约balanceOf()方法查询同一地址的余额，返回错误码：-3200

#### System information

PlatON version: `platon version`
OS & Version: Windows/Linux/OSX
Commit hash : (if `develop`)

#### Expected behaviour
返回余额

#### Actual behaviour
12:14:16.374 [Test worker] DEBUG com.platon.protocol.http.HttpService - {"jsonrpc":"2.0","method":"platon_call","params":[{"from":"lat196278ns22j23awdfj9f2d4vz0pedld8anl5k3a","to":"lat18v25d02zwnghpwh0xtc0ay4mt9ur258nx7thgt","data":"0x70a082310000000000000000000000002e95e3ce0a54951eb9a99152a6d5827872dfb4fd"},"latest"],"id":87996}
12:14:16.374 [Test worker] DEBUG com.platon.protocol.http.HttpService - --> END POST (259-byte body)
12:14:16.386 [Test worker] DEBUG com.platon.protocol.http.HttpService - <-- 200 OK http://192.168.112.31:8202/ (11ms)
12:14:16.386 [Test worker] DEBUG com.platon.protocol.http.HttpService - Content-Type: application/json
12:14:16.386 [Test worker] DEBUG com.platon.protocol.http.HttpService - Date: Wed, 21 Apr 2021 04:14:28 GMT
12:14:16.386 [Test worker] DEBUG com.platon.protocol.http.HttpService - Content-Length: 107
12:14:16.386 [Test worker] DEBUG com.platon.protocol.http.HttpService - 
12:14:16.386 [Test worker] DEBUG com.platon.protocol.http.HttpService - {"jsonrpc":"2.0","id":3383,"error":{"code":-32000,"message":"execution aborted (timeout = 5s)"}}

12:14:16.386 [Test worker] DEBUG com.platon.protocol.http.HttpService - <-- END HTTP (97-byte body)

#### Steps to reproduce the behaviour
1、部署一个普通的ERC721合约；
2、通过Java sdk循环调用:
    @Test
    public void balance() throws IOException {

        String contractAddress = "lat18v25d02zwnghpwh0xtc0ay4mt9ur258nx7thgt";
        String userAddress = "lat196278ns22j23awdfj9f2d4vz0pedld8anl5k3a";
        Erc721Contract contract = loadArc721Contract(contractAddress, adminWallet);
        while (true){
            long start = System.currentTimeMillis();
            try {
                BigInteger balance = contract.balanceOf(userAddress).send();
                log.error("balance:{}",balance);
            }catch (Exception e){
                long end = System.currentTimeMillis();
                log.error("查询余额失败：{}", userAddress, e);
                long  diff = end - start;
                System.out.println(diff);
                break;
            }
        }
    }

#### Backtrace

````
[backtrace]
````

**Comment by benbaley** [comment]
ref:#1771

**Comment by benbaley** [comment]
fixed in https://github.com/AlayaNetwork/Alaya-Go/pull/30

**Comment by sigrlot** [comment]
Verify 10,000 times in 45 seconds, successful.
