### ISSUE TITLE
question

### ISSUE THREAD

**Issue by Fei-FeiLiang** [PlatONnetwork/PlatON-Go#1781]
Hi there,

please note that this is an issue tracker reserved for bug reports and feature requests.

#### System information

PlatON version: `platon version`
OS & Version: Windows/Linux/OSX
Commit hash : (if `develop`)

#### Backtrace

````
[backtrace]
````

这又是个割韭菜的项目吗？代码都是从以太坊拿过来的，随便改了几行啊！

**Comment by biganxin** [comment]
Have you seen the code in full?
welcome to read the code and come back with your feedback, thank you!

**Comment by benbaley** [comment]
PlatON is an Ethereum-based, high-performance and high-security Blockchain Infrastructure. 
suggestion: read the PlatON's [whitepaper](https://www.platon.network/pdf/zh/PlatON_A_High-Efficiency_Trustless_Computing_Network_Whitepaper_ZH.pdf)
.

**Comment by benbaley** [comment]
Closed due to lack of feedback
