### ISSUE TITLE
选举共识节点随机性不够的bug

### ISSUE THREAD

**Issue by benbaley** [PlatONnetwork/PlatON-Go#1785]
感谢 二妞@blueatsky 严谨的统计和持续观察，为最终确认该问题提供了充足的信息。

PlatON在共识机制中关于每个共识轮共识节点选取的设计原则是：
1. 足够的随机，通过VRF确保每一轮的选举结果都不可预测
2. 公平性，节点自身的权益比重占总权益比重越高，节点被选中的概率相对越大
3. 抑制权力集中，高权重不一定会获得高收益，权重的平方根占所有节点权重平方根的和的比，与节点累积被选中次数占总选举次数的比， 趋近于相同

通过PlatON主网上对各个验证节点的观察和统计，发现实际的情况和以上原则不符， 经持续对比和深入的分析，现已确认选举共识节点在随机性和公平性方面和设计目标存在偏差，原因是底层在计算每个节点参选的累积随机目标 `X` 时，相同的 `X` 值排序过程中使用了节点质押所在的区块高度参与排序，导致了实际随机性出现偏差。

#### System information

PlatON version: v1.0.0
OS & Version: Windows/Linux/OSX
Commit hash : (if `develop`)

#### Expected behaviour
1. 足够的随机，通过VRF确保每一轮的选举结果都不可预测
2. 公平性，节点自身的权益比重占总权益比重越高，节点被选中的概率相对越大
3. 抑制权力集中，高权重不一定会获得高收益，权重的平方根占所有节点权重平方根的和的比，与节点累积被选中次数占总选举次数的比， 趋近于相同

#### Actual behaviour
个别高权重节点实际被选中次数不如低权重节点，持续观察发现并非偶然现象

#### Steps to reproduce the behaviour
https://scan.platon.network/node

**Comment by junjiequ123** [comment]
[English translation] Thanks to @blueatsky for your rigorous statistics and continuous observation, which provided sufficient information for the final confirmation of the issue.

PlatON's design principles in the consensus mechanism regarding the selection of consensus nodes (validators) for each consensus round are

1. randomness, with the VRF ensuring that the election results of each round are unpredictable
2. Fairness, the higher the weight of the node's portion to the total, the higher the probability of the node being selected as validator
3. The ratio of the square root of a node's weight to the sum of the square root of the weights of all nodes equals to the ratio of the cumulative number of this node be selected to the total number of elections

After continuous comparison and in-depth analysis, it is confirmed that there is a deviation from the design goal in terms of randomness and fairness in validator election. The actual randomness is deviated due to the validator election sorting logic included the block height of the node pledge, which should not be used.

System information
PlatON version: v1.0.0
OS & Version: Windows/Linux/OSX
Commit hash : (if develop)

Expected behaviour
(same as above design principle)

Steps to reproduce the behaviour
https://scan.platon.network/node

**Comment by WeiLoy** [comment]
在目前验证人选举的机制中，首先获取排名前201的备选节点，排除其中正在参与共识的43个节点，剩余的158个节点按照原先权重高低的顺序参选下一个共识轮的验证人选举。验证人的选举使用VRF随机数+二项分布完成，每个节点通过各自不同的随机数（前N个区块的VRF随机数）从各自的二项分布累计曲线中获取一个随机的x值，然后根据x值逆序排列，排列前面的当选验证人，当x值出现相同时，再根据质押块高正序排列，如果再相同则根据交易index正序排列。

**问题原因：** 由于为了让选中和权重比接近1，所以二项分布中使用的期望概率值选择的比较小，这也让出现相同x值的概率比较高，最终根据质押块高正序排列，所以导致目前有些权重高的当选次数偏低了。而在当初的测试中，由于是测试权重概率，并未在测试数据中加入stakingNumber等，并且测试过程中选举输入的备选节点列表是乱序的，最终导致该问题未能暴露出来。

下一步将制定一个合适的解决方案。

**Comment by biganxin** [comment]
Excellent. Further suggestions and contributions are encouraged

**Comment by WeiLoy** [comment]
**可行的解决方案：** 针对选举过程中涉及的算法增加随机性，并且选中的影响因素只与权重相关。

**测试数据：**
> 来源于主网

![备选节点](https://user-images.githubusercontent.com/19259075/119799013-46034980-bf0e-11eb-964b-5b12f5eafab2.png)

以下是使用测试数据根据不同方案的测试结果所绘制的效果图：

> 所有方案均经过25W次选举测试，其中包含目前正使用的方案和一些改进的方案
>
> X轴：备选节点按权重高低的排列
>
> Y轴：节点选中次数占总选中次数比例和节点权重占总权重比例的比

![election_sort](https://user-images.githubusercontent.com/19259075/119789053-4814da80-bf05-11eb-8a5a-43175b51589d.png)

- **stkNumber：** 目前正在使用的方案，x值相同时，根据质押块高正序排列
- **weight：**  x值相同时，根据权重逆序排列，优先选择高权重的节点
- **targetP：** x值相同时，根据targetP正序排列，权重高的节点大概率排在前面
- **shuffle：** x值相同时，不做二次排序，而是选择在选举运算之前，将158名备选节点原本按照权重高低排列的顺序，使用shuffle算法随机打乱，再输入到选举算法中执行选举，这样当出现x值相同时，不必根据某种规则做二次排序，因为本身x值相同的节点间已经是随机的顺序了

从以上结果来看，`shuffle`算法的引入能更好的带来随机性，并且从长期的抽样数据中也表明结果符合预期。

**shuffle方案细则：** shuffle首先需要输入一个种子，在选举节点时使用了前N个区块的VRF随机数，这里的种子将使用其中的第一个随机数作为输入种子。这样选择的种子首先保证一致性，并且种子是公开透明的、随机的和可验证的，当前出块节点也无法篡改和阻止该种子的生成，而在种子生成时，由于该种子是未来才使用到，所以在生成时和未到选举区块时，大家都无法预知该种子所带来的影响，保障了种子使用的安全性。


> 附件：
[stakingBlockNumber_30_25W.txt](https://github.com/PlatONnetwork/PlatON-Go/files/6620805/stakingBlockNumber_30_25W.txt)
[weight_30_25W.txt](https://github.com/PlatONnetwork/PlatON-Go/files/6620803/weight_30_25W.txt)
[targetP_30_25W.txt](https://github.com/PlatONnetwork/PlatON-Go/files/6620806/targetP_30_25W.txt)
[shuffle_30_25W.txt](https://github.com/PlatONnetwork/PlatON-Go/files/6620804/shuffle_30_25W.txt)

**Comment by WeiLoy** [comment]
结合上述随机性的方案，并且调整测试方式，新的结果对比如下：

![不同抽样方式的选举测试-25W-30P](https://user-images.githubusercontent.com/19259075/120291120-8c352000-c2f5-11eb-8848-81f090416bad.png)

- 放回抽样：原测试方案，从201个节点中选举14个节点，放回201，再次选举14个节点，重复此过程，统计结果
- 不放回抽样：新测试方案，首先从201个备选节点中挑出前43个作为当前节点列表，随后用剩余的158个选举，选举14个节点，追加到当前节点列表，并且移出前14个节点放入到备选节点中，再用158个备选节点选举，重复此过程，统计结果

两种方案所使用的期望值都为：30
经过测试方案的调整后，新的测试方案的期望值与此前方案的期望结果不一致（选中与权重比未平滑的接近1），因此期望值的选择还需进行调整

**Comment by jiangshangqifeng** [comment]
> 结合上述随机性的方案，并且调整测试方式，新的结果对比如下：
> 
> ![不同抽样方式的选举测试-25W-30P](https://user-images.githubusercontent.com/19259075/120291120-8c352000-c2f5-11eb-8848-81f090416bad.png)
> 
> * 放回抽样：原测试方案，从201个节点中选举14个节点，放回201，再次选举14个节点，重复此过程，统计结果
> * 不放回抽样：新测试方案，首先从201个备选节点中挑出前43个作为当前节点列表，随后用剩余的158个选举，选举14个节点，追加到当前节点列表，并且移出前14个节点放入到备选节点中，再用158个备选节点选举，重复此过程，统计结果
> 
> 两种方案所使用的期望值都为：30
> 经过测试方案的调整后，新的测试方案的期望值与此前方案的期望结果不一致（选中与权重比未平滑的接近1），因此期望值的选择还需进行调整

很棒的测试！
“不放回抽样”符合真实的场景，因此这个目标的值看起来仍需要优化， 请有新的测试结果后及时分享， 谢谢！

**Comment by WeiLoy** [comment]
![主网络不同P对比](https://user-images.githubusercontent.com/19259075/120878148-1aa6eb80-c5ed-11eb-8f0b-f2c28964bfab.png)

以上图示结果为不同期望值的测试结果。

数据来源：5月21日主网络数据快照
测试次数：25W

**Comment by WeiLoy** [comment]
根据主网络替换规则，6月5号权重数据进行测试，以下是不同期望值的结果。

选举次数：25W

第一名权重：20125273（LAT）
第二名权重：14517973（LAT）
第三名权重：13874308（LAT）

![主网规则_不同期望值](https://user-images.githubusercontent.com/19259075/120953323-4fe34300-c77f-11eb-8747-bd69552289c1.png)
![主网规则_不同期望值_1](https://user-images.githubusercontent.com/19259075/120953328-5376ca00-c77f-11eb-88a9-f0f8e9aa4ac4.png)
![主网规则_不同期望值_2](https://user-images.githubusercontent.com/19259075/120953335-55d92400-c77f-11eb-8bc7-26a94ade9ee1.png)
![主网规则_不同期望值_3](https://user-images.githubusercontent.com/19259075/120953339-583b7e00-c77f-11eb-9084-40ef8ef9f33c.png)

> 附件：
[40.txt](https://github.com/PlatONnetwork/PlatON-Go/files/6620912/main_40_25W_210605.txt)
[42.txt](https://github.com/PlatONnetwork/PlatON-Go/files/6620913/main_42_25W_210605.txt)
[43.txt](https://github.com/PlatONnetwork/PlatON-Go/files/6620914/main_43_25W_210605.txt)
[45.txt](https://github.com/PlatONnetwork/PlatON-Go/files/6620915/main_45_25W_210605.txt)
[50.txt](https://github.com/PlatONnetwork/PlatON-Go/files/6620916/main_50_25W_210605.txt)
[53.txt](https://github.com/PlatONnetwork/PlatON-Go/files/6620917/main_53_25W_210605.txt)
[56.txt](https://github.com/PlatONnetwork/PlatON-Go/files/6620918/main_56_25W_210605.txt)
[57.txt](https://github.com/PlatONnetwork/PlatON-Go/files/6620919/main_57_25W_210605.txt)

**Comment by benbaley** [comment]
建议可以用模拟权重，比如等差数列重新测试一下
以上的测试数据说明：用当前的随机性方案，权重靠前整体上有优势，但权重过大（如超过第二名25%）则优势会减弱

**Comment by WeiLoy** [comment]
沿用6月5号权重数据进行测试，对第一名的权重进行修改，调整为接近第二名。

选举次数：25W

第一名权重：14527973
第二名权重：14517973
第三名权重：13874308

![等差对比_43_P](https://user-images.githubusercontent.com/19259075/121146537-99608a80-c872-11eb-824a-7bc882140e6a.png)
> 附件：
[43.txt](https://github.com/PlatONnetwork/PlatON-Go/files/6620891/main_43_25W_210605.txt)
[dengcha.txt](https://github.com/PlatONnetwork/PlatON-Go/files/6620892/main_43_25W_210605_dengcha.txt)


![等差对比_57_P](https://user-images.githubusercontent.com/19259075/121146543-9b2a4e00-c872-11eb-9b49-4f7181186b8a.png)
> 附件：
[57.txt](https://github.com/PlatONnetwork/PlatON-Go/files/6620893/main_57_25W_210605.txt)
[dengcha.txt](https://github.com/PlatONnetwork/PlatON-Go/files/6620894/main_57_25W_210605_dengcha.txt)


> 线1：原权重
> 线2：本次调整后权重

整体比例都在接近1的范围，虽然中部存在低于比例1的，但选中次数任是高于尾部的，并且整体选中次数是呈高低趋势。

**Comment by WeiLoy** [comment]
本次测试基于五十亿总权重进行选举，观察总权重上升一定量级后，与先前相同期望值选举的结果差异。

总权重：50亿（模拟生成）
选举次数：25W
期望值：57、43

![五十亿权重](https://user-images.githubusercontent.com/19259075/121669079-8a7e1000-cade-11eb-9c29-cd5c718101c9.png)
![五十亿权重_43_57](https://user-images.githubusercontent.com/19259075/121669088-8c47d380-cade-11eb-98a1-83d30ab1df59.png)

**Comment by WeiLoy** [comment]
![image](https://user-images.githubusercontent.com/19259075/131971954-958383bf-272b-46f5-8463-e04c2d76ee4c.png)

PlatON在8月30日成功升级，之后针对随机性优化的问题做了进一步的验证，上图为单次选举的结果，前N名为选中的下一轮节点。
**其中重点关注值：**
weight 为节点总权重开根号后的值。
blockNumber 为节点的质押块高。

根据之前的解决方案可以看出，结果是符合预期的。
当 x 值相同时，相同 x 值的节点间排列是随机的，不再像改进之前受 blockNumber值的影响了。

**Comment by WeiLoy** [comment]
fixed in #1801

**Comment by benbaley** [comment]
close by fixed
