### ISSUE TITLE
block rate metrics on explorer is inconsistent for alarm condition

### ISSUE THREAD

**Issue by qianxiaofeng** [PlatONnetwork/PlatON-Go#1787]
#### System information

PlatON version: `1.0.0`
explorer: https://scan.platon.network/

#### Expected behaviour
block rate from explorer should staying as 100% if no block misses.

#### Actual behaviour
validator's block rate drops below 100%( 97.8% for example) once QC starts, and grows back to 100% after finishes its turn to produce.

#### Steps to reproduce the behaviour

1. wait when one round QC starts.
2. check any selected validator, providing most of validator has 100% block rate as now,  new QC round set them below 100% on validator details page 
3. after producing blocks, block rate grows back to 100%

#### Feature Request

block rate  =  actual block Qt / expected block Qt,  explorer seems adding 10 to expected block Qt before the time point validator can produce, thus falsely set block rate lower than actual value for a short period of time.

It would be helpful if we can have a prometheus metric embedded in node, and such block rate could be a nice feature to monitor.

[waitSlashingNodeListKey](https://github.com/PlatONnetwork/PlatON-Go/blob/1c595e9b258f6f6c3a806142bbe261c174d75ac4/x/plugin/slashing_plugin.go#L58) is tracking related records, also could be manipulated a bit and export as a metric.

other common metrics:
- CPU, MEM, DISK
- p2p number
- block height
- validator rank
- process up and up time
- produced block number

**Comment by biganxin** [comment]
Thank you very much, very well observed

**Comment by benbaley** [comment]
Very good idea.
And now there is a ’RPC‘ function called `getWaitSlashingNodeList` in the `debug` interface which can get a list of nodes in the current network that have had zero-produced blocks but are still in the watch period
Special emphasis needs to be placed on: this method is designed for debug purposes and requires special care when using it.
As you mentioned, a formal method is necessary, and I'm considering what data are needed for monitoring?

**Comment by qianxiaofeng** [comment]
I have created a topic in forum for discussing https://forum.latticex.foundation/t/topic/5066

also we can refer prysm grafana dashboard https://docs.prylabs.network/docs/prysm-usage/monitoring/grafana-dashboard/
