### ISSUE TITLE
crypto\bls\bls.go:4:10: fatal error: bls/bls.h: No such file or directory

### ISSUE THREAD

**Issue by woyouwole2012** [PlatONnetwork/PlatON-Go#1788]
crypto\bls\bls.go:4:10: fatal error: bls/bls.h: No such file or directory

**Comment by woyouwole2012** [comment]
exit status 3221225781

**Comment by jiangshangqifeng** [comment]
What‘s the OS info? Is `libssl-dev` installed?

```
sudo apt install -y golang-go cmake llvm g++ libgmp-dev libssl-dev
```
try it

**Comment by jiangshangqifeng** [comment]
https://devdocs.platon.network/docs/en/Install_PlatON/

**Comment by woyouwole2012** [comment]
> What‘s the OS info? Is `libssl-dev` installed?
> 
> 
> 
> ```
> 
> sudo apt install -y golang-go cmake llvm g++ libgmp-dev libssl-dev
> 
> ```
> 
> try it

windows 10 ,I've installed
 mingw ,what should I do next

**Comment by benbaley** [comment]
> > What‘s the OS info? Is `libssl-dev` installed?
> > ```
> > 
> > sudo apt install -y golang-go cmake llvm g++ libgmp-dev libssl-dev
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > try it
> 
> windows 10 ,I've installed
> mingw ,what should I do next

You should add bls dependent library to your environment variables
```
git submodule init && git submodule update
export PATH=$PATH:"$GOPATH/src/github.com/PlatONnetwork/PlatON-Go/crypto/bls/bls_win/lib"
```

**Comment by benbaley** [comment]
Closed due to prolonged absence of feedback
