### ISSUE TITLE
why platon.blockNumber is zero

### ISSUE THREAD

**Issue by woyouwole2012** [PlatONnetwork/PlatON-Go#1789]
I run my client ,and platon.blockNumber is zero for a long time ! why?

**Comment by jiangshangqifeng** [comment]
Take a look at how many peers are connected? 
You can enter ` admin.peers.length`  in the console

**Comment by woyouwole2012** [comment]
> Take a look at how many peers are connected? 
> 
> You can enter ` admin.peers.length`  in the console
It's still zero, but I've run for one day

**Comment by woyouwole2012** [comment]
> > Take a look at how many peers are connected? 
> > 
> > You can enter ` admin.peers.length`  in the console
> It's still zero, but I've run for one day

**Comment by woyouwole2012** [comment]
> > Take a look at how many peers are connected? 
> > 
> > You can enter ` admin.peers.length`  in the console
> It's still zero, but I've run for one day
Does it need LAT coin

**Comment by woyouwole2012** [comment]
![image](https://user-images.githubusercontent.com/53109661/120185251-8af7ea80-c244-11eb-828c-6bd868d78887.png)
Is it ok?

**Comment by benbaley** [comment]
> ![image](https://user-images.githubusercontent.com/53109661/120185251-8af7ea80-c244-11eb-828c-6bd868d78887.png)
> Is it ok?

that’s OK
can you check the genesis block's hash value? you can type:
```
platon.getBlock(0).hash
```
in console，the PlatON mainnet genesis hash is `0xbd3e148a58392bc546aee5e69aa751c8e572e2cd2c82d06d9418a686b82252b9`

**Comment by benbaley** [comment]
> > Take a look at how many peers are connected?
> > You can enter ` admin.peers.length`  in the console
> > It's still zero, but I've run for one day

No need coin at all， can you send me your node's log file?

**Comment by woyouwole2012** [comment]
> > > Take a look at how many peers are connected?
> > > You can enter ` admin.peers.length`  in the console
> > > It's still zero, but I've run for one day
> 
> No need coin at all， can you send me your node's log file?

[log.log](https://github.com/PlatONnetwork/PlatON-Go/files/6581073/log.log)
Here is my log

**Comment by niuxiaojie81** [comment]
From the log, I see that your startup option adds `--nodiscover`, so that your node can't find the rest of the nodes in the network, try to delete this option.

**Comment by woyouwole2012** [comment]
> From the log, I see that your startup option adds `--nodiscover`, so that your node can't find the rest of the nodes in the network, try to delete this option.

Thanks , I'll try

**Comment by benbaley** [comment]
> > From the log, I see that your startup option adds `--nodiscover`, so that your node can't find the rest of the nodes in the network, try to delete this option.
> 
> Thanks , I'll try

Does this work?

**Comment by benbaley** [comment]
Closed due to prolonged lack of feedback
