### ISSUE TITLE
投票接口中投票选择字段传非接口定义的值，结果交易成功

### ISSUE THREAD

**Issue by chenxiaodai** [PlatONnetwork/PlatON-Go#1790]
软件版本： 1.0.0

问题：发起投票时，投票接口参数 VoteOption 设置了49， 结果交易成功了。 但是接口文档该字段只定义了3个枚举，1-支持   2-反对   3-弃权

**Comment by benbaley** [comment]
在实际处理voteoption时，如果不是0x01、0x02、0x03，都是按 `Abstentions` 处理的， jssdk中没有封装枚举值，因此需要在[接口文档](https://devdocs.platon.network/docs/zh-CN/JS_SDK)中加以说明，javasdk是有封装的

**Comment by benbaley** [comment]
fixed in https://github.com/PlatONnetwork/docs/pull/68
