### ISSUE TITLE
能否支持一下ERC-1155

### ISSUE THREAD

**Issue by Eason123** [PlatONnetwork/PlatON-Go#1792]
nft合约想迁移过来发现不支持。

希望platon也与时俱进！

**Comment by benbaley** [comment]
ERC只是一个合约规范， 对于底层来说只要支持合约的指令都可以支持呀？
你迁移时具体遇到什么问题呢？

**Comment by chenxiaodai** [comment]
NFT 目前在scan上面只支持ERC721显示， ERC1155的不支持。 不过底层合约是支持的，如果发现不支持，可提供问题的NFT合约链接便于分析
