### ISSUE TITLE
Genesis file sets timestamp to the future time. Before the block is generated, an error occurs when restarting the node 

### ISSUE THREAD

**Issue by pengzhepz** [PlatONnetwork/PlatON-Go#1808]
Hi there,

please note that this is an issue tracker reserved for bug reports and feature requests.

#### System information

PlatON version: 0.16.0
OS & Version: Windows/Linux/OSX
Commit hash : (if `develop`)

#### Expected behaviour
Successful restart 

#### Actual behaviour
Node failed to start 

#### Steps to reproduce the behaviour
[platon (3).log](https://github.com/PlatONnetwork/PlatON-Go/files/6790579/platon.3.log)

#### Backtrace

````
[backtrace]
````

**Comment by niuxiaojie81** [comment]
修改创世区块时间戳为未来时间，节点启动后无法出块（出块的时间必须大于创世区块），但可以切换view，节点成功切换view时会把切换信息ConfirmedViewChange记录到wal日志中。
ConfirmedViewChange消息包含切换view时的blockQC，但该字段不允许为nil，所以导致rlp编解码异常

**Comment by niuxiaojie81** [comment]
针对这种不出块又重启的情况，将ConfirmedViewChange消息中的blockQC字段设置为允许为空

**Comment by pengzhepz** [comment]
bug fixed
