### ISSUE TITLE
跨版本升级，跳过了0.14.0，minimumRelease参数无法查询。

### ISSUE THREAD

**Issue by sigrlot** [PlatONnetwork/PlatON-Go#1811]
hi，  我搭了个私链，从0.13.2版本，直接升到了0.15.0版本，跳过了0.14.0版本。  
现在我查询restricting.minimumRelease参数，返回了{'Code': 302031, 'Ret': 'Unsupported governent parameter'}。

我的理解是，我即使跳过了0.14.0版本， 在0.13.2升级到0.15.0时，0.14.0的变更应该以应用器的方式，智能应用并生效。

这是一个小建议，请评估。

**Comment by benbaley** [comment]
按我们目前的实现逻辑， 不能跳版本的
这个参数在0.14.0提案通过的块高生效， 你没走这个提案，肯定生效不了的
