### ISSUE TITLE
platon_estimateGas 返回的message信息过少

### ISSUE THREAD

**Issue by shadow-001** [PlatONnetwork/PlatON-Go#1819]
代码中给了require，但是报错信息没有提示，对于开发定位问题非常不友好：
![image](https://user-images.githubusercontent.com/25794754/127996764-5a7db763-8172-4957-840e-3360b9083900.png)

个人建议，可以参考eth，给出报错信息：
![image](https://user-images.githubusercontent.com/25794754/127996855-d6f29cd5-28f5-429d-91a5-47b78ca22001.png)

**Comment by WeiLoy** [comment]
在EVM合约的执行中，如果抛出异常了，是会组装成 execution reverted: xxx 返回的，除非合约执行本身返回的是execution reverted错误。
请检查合约是不是按理想情况执行的，可能合约本身存在问题并没有执行到期望的步骤上，导致失败了

**Comment by shadow-001** [comment]
> execution reverted

用的同一个合约文件，以太坊上调用eth_estimateGas返回提示信息，而platon上没有看到。
我把合约源文件贴出来，您试一下呢。
部署完成后，执行addTime方法即可复现报错：

`pragma solidity =0.5.17;



/**
    被部署的合约
 */
contract DeployedContractt{

    address public creatorAddr;
    uint public createTime;

    constructor() public{
        creatorAddr = msg.sender;
        createTime = block.timestamp + 180000;
    }
    
    function addTime(address to) external returns(uint){
        require(createTime < now,"too early");
        creatorAddr = to;
        createTime = block.timestamp + 1000;
    }

}`

**Comment by WeiLoy** [comment]
出现该问题的原因是，由于历史原因有两处文件定义了errExecutionReverted错误，旧error未删除，返回的client处和evm中的不同，导致自定义错误为提示

**解决：**
删除instructions.go中的errExecutionReverted，所有地方改为应用errors.go中新定义的ErrExecutionReverted

**Comment by benbaley** [comment]
close by done
