### ISSUE TITLE
启动节点时不指定私钥，质押后节点不出块，查看零出块惩罚日志时发现节点收益打印错误

### ISSUE THREAD

**Issue by pengzhepz** [PlatONnetwork/PlatON-Go#1836]
#### System information

PlatON version: `platon version` 、`alaya version` 
OS & Version: Windows/Linux/OSX
Commit hash : (if `develop`)

#### Expected behaviour
1、质押成功，节点正常出块
2、节点收益地址为质押时指定地址，且日志收益地址打印正确

#### Actual behaviour
1、质押成功，节点零出块
2、节点收益地址为质押时指定地址，但是日志收益地址打印错误
![5c12d69dfffedf442c4562110e5b498](https://user-images.githubusercontent.com/78134846/130546814-58b6f16a-8be0-42a5-97ce-091f1c27c3d6.png)

#### Steps to reproduce the behaviour
1、质押节点、启动节点不指定私钥
2、等待节点进入验证人列表，查看出块数
3、节点零出块处罚触发，查看日志。

#### Backtrace

````
[backtrace]
````

When submitting logs: please submit them as text and not screenshots.

**Comment by cheng762** [comment]
2. 日志是对的，惩罚的钱流向奖励池

**Comment by cheng762** [comment]
该原因的产生时因为，节点在启动时如果没有指定 --nodekey 或者--nodekeyhex，运行过程中会无法在共识模块中设置自己的节点ID，导致节点即使质押成功，本身依旧无法出块。
修复方法，共识模块中如果没有获取到节点ID的情况下，会去node模块中获取。

**Comment by benbaley** [comment]
close by fixed
