### ISSUE TITLE
graph-node连接节点rpc后，graph报解析错误，不能同步

### ISSUE THREAD

**Issue by a2a6c172b3f1b60a8ce26f** [PlatONnetwork/PlatON-Go#1885]
subgraph是dapp开发中的重要一环。链上数据查询能力有限。通过subgraph定义业务规则。把合约的数据同步到graph节点中。graph节点提供api给dapp前端数据查询的能力。

**Comment by a2a6c172b3f1b60a8ce26f** [comment]
该问题主要是当前platon的rpc与geth不兼容导致的。本人写了一个脚本用于临时该解决。脚本连接platon公共节点。本地监听3000端口。graph-node连接3000端口即可。
https://github.com/a2a6c172b3f1b60a8ce26f/rpc-adaptor

**Comment by benbaley** [comment]
感谢反馈， 关于graphql的支持已启动调研， 也欢迎您一起参与开发和讨论

**Comment by benbaley** [comment]
请将节点更新到最新版本试试， 如有不兼容的地方欢迎反馈
