### ISSUE TITLE
random number generation times out

### ISSUE THREAD

**Issue by sigrlot** [PlatONnetwork/PlatON-Go#1914]
version: 1.2.0

Use the inner contract (lat1xqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqpe9fgva) to generate random numbers, when the number parameter is large (>450), the generation will time out.

if is call,  timed out while generation.

if is transaction, timed out while estimating gas.

**Comment by benbaley** [comment]
fixed in #1913

**Comment by sigrlot** [comment]
latest code is causing a new issue,  when the number parameter is greater than 5,  got: ContractLogicError: execution reverted
