### ISSUE TITLE
I cann't get error info form contract lat1xqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqpe9fgva

### ISSUE THREAD

**Issue by sigrlot** [PlatONnetwork/PlatON-Go#1916]
I cann't get error info form contract lat1xqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqpe9fgva, only ContractLogicError: execution reverteda

**Comment by benbaley** [comment]
fixed in #1915

**Comment by benbaley** [comment]
close by done
