### ISSUE TITLE
可治理参数取值范围异常

### ISSUE THREAD

**Issue by HYPWolf** [PlatONnetwork/PlatON-Go#1966]
可治理参数unDelegateFreezeDuration的desc为：quantity of epoch for delegate withdrawal, range:  [1, 5]
实际上：range: (0,unStakeFreezeDuration]

**Comment by Tharolzakariya** [comment]
> 可治理参数unDelegateFreezeDuration的desc为：quantity of epoch for delegate withdrawal, range:  [1, 5]
> 
> 实际上：range: (0,unStakeFreezeDuration]

**Comment by benbaley** [comment]
close by done
