### ISSUE TITLE
ethclient can't SubscribeNewHead

### ISSUE THREAD

**Issue by LeonTing1010** [PlatONnetwork/PlatON-Go#2012]
error :  hex string has length 162, want 16 for BlockNonce

**Comment by benbaley** [comment]
Which RPC endpoint are you connecting to? 
If it's your own node, add the `http.ethcompatible` flag and restart it, 
otherwise use `wss://openapi2.platon.network/ws` for mainnet and `wss://devnet2openapi.platon.network/ws` for testnet

**Comment by benbaley** [comment]
Closed due to prolonged non-response
