### ISSUE TITLE
There is a null pointer problem with qc parameter

### ISSUE THREAD

**Issue by shinnng** [PlatONnetwork/PlatON-Go#346]
func (cbft *Cbft) verifyPrepareQC(qc *ctypes.QuorumCert) error {
	var cb []byte
	var err error
	if cb, err = qc.CannibalizeBytes(); err != nil {
		return err
	}
	if err = cbft.validatorPool.VerifyAggSigByBA(qc.BlockNumber, qc.ValidatorSet, cb, qc.Signature.Bytes()); err != nil {
		return fmt.Errorf("verify prepare qc failed: %v", err)
	}
	return err
}

**Comment by zjsunzone** [comment]
Yes, here we add security check:
`func (cbft *Cbft) verifyPrepareQC(oriNum uint64, oriHash common.Hash, qc *ctypes.QuorumCert) error {
	if qc == nil {
		return fmt.Errorf("verify prepare qc failed,qc is nil")
	}
	if err := cbft.validatorPool.EnableVerifyEpoch(qc.Epoch); err != nil {
		return err
	}
...
}`

**Comment by shinnng** [comment]
The issue has been resolved, please use the latest version.
