### ISSUE TITLE
if lock!=nil Constant is true

### ISSUE THREAD

**Issue by shinnng** [PlatONnetwork/PlatON-Go#350]
func (b *BlockTree) commitBlock(ext *blockExt) (*types.Block, *types.Block) {
	lock := ext.Parent
	if lock == nil {
		panic(fmt.Sprintf("%s,%d", ext.Block.Hash().String(), ext.Block.NumberU64()))
	}
	if lock.Block.Hash() == b.root.Block.Hash() {
		return b.root.Block, b.root.Block
	}
	var commit *blockExt
	if lock != nil {
		commit = lock.Parent
	}
	return lock.Block, commit.Block
}

**Comment by zjsunzone** [comment]
Sorry, can you explain more carefully?

**Comment by shinnng** [comment]
The issue has been resolved, please use the latest version.
