### ISSUE TITLE
verifyConsensusMsg has null pointer errors

### ISSUE THREAD

**Issue by shinnng** [PlatONnetwork/PlatON-Go#367]
func (cbft *Cbft) verifyConsensusMsg(msg ctypes.ConsensusMsg) (*cbfttypes.ValidateNode, error) {
	// Verify consensus msg signature
	if err := cbft.verifyConsensusSign(msg); err != nil {
		return nil, err
	}

	// Get validator of signer
	vnode, err := cbft.validatorPool.GetValidatorByIndex(msg.EpochNum(), msg.NodeIndex())

	if err != nil {
		return nil, errors.Wrap(err, "get validator failed")
	}

	// check if the prepareBlock must take viewChangeQC
	needViewChangeQC := func(pb *protocols.PrepareBlock) bool {
		_, localQC := cbft.blockTree.FindBlockAndQC(pb.Block.ParentHash(), pb.Block.NumberU64()-1)
		return localQC != nil && localQC.BlockIndex < cbft.config.Sys.Amount-1
	}
	// check if the prepareBlock base on viewChangeQC maxBlock
	baseViewChangeQC := func(pb *protocols.PrepareBlock) bool {
		_, _, _, _, hash, number := pb.ViewChangeQC.MaxBlock()
		return pb.Block.NumberU64()-1 != number || pb.Block.ParentHash() != hash
	}
	var (
		prepareQC *ctypes.QuorumCert
		oriNumber uint64
		oriHash   common.Hash
	)

	switch cm := msg.(type) {
	case *protocols.PrepareBlock:
		proposer := cbft.currentProposer()
		if uint32(proposer.Index) != msg.NodeIndex() {
			return nil, fmt.Errorf("current proposer index:%d, prepare block author index:%d", proposer.Index, msg.NodeIndex())
		}
		// BlockNum equal 1, the parent's block is genesis, doesn't has prepareQC
		// BlockIndex is not equal 0, this is not first block of current proposer
		if cm.BlockNum() == 1 || cm.BlockIndex != 0 {
			return vnode, nil
		}
		if needViewChangeQC(cm) && cm.ViewChangeQC == nil {
			return nil, fmt.Errorf("prepareBlock need ViewChangeQC,index:%d", prepareQC.BlockIndex)
		}
		if cm.ViewChangeQC != nil {
			if !baseViewChangeQC(cm) {
				return nil, fmt.Errorf("prepareBlock is not based on viewChangeQC maxBlock")
			}
			if err := cbft.verifyViewChangeQC(cm.ViewChangeQC); err != nil {
				return nil, err
			}
		}
		prepareQC = cm.PrepareQC
		_, localQC := cbft.blockTree.FindBlockAndQC(cm.Block.ParentHash(), cm.Block.NumberU64()-1)
		if localQC == nil {
			return nil, fmt.Errorf("parentBlock and parentQC not exists,number:%d,hash:%s", cm.Block.NumberU64()-1, cm.Block.ParentHash())
		}
		oriNumber = localQC.BlockNumber
		oriHash = localQC.BlockHash

	case *protocols.PrepareVote:
		if cm.BlockNum() == 1 {
			return vnode, nil
		}
		prepareQC = cm.ParentQC
		if cm.BlockIndex == 0 {
			_, localQC := cbft.blockTree.FindBlockAndQC(prepareQC.BlockHash, cm.BlockNumber-1)
			if localQC == nil {
				return nil, fmt.Errorf("parentBlock and parentQC not exists,number:%d,hash:%s", cm.BlockNumber-1, prepareQC.BlockHash)
			}
			oriNumber = localQC.BlockNumber
			oriHash = localQC.BlockHash
		} else {
			parentBlock := cbft.state.ViewBlockByIndex(cm.BlockIndex - 1)
			oriNumber = parentBlock.NumberU64()
			oriHash = parentBlock.Hash()
		}

	case *protocols.ViewChange:
		// Genesis block doesn't has prepareQC
		if cm.BlockNumber == 0 {
			return vnode, nil
		}
		prepareQC = cm.PrepareQC
		oriNumber = cm.BlockNumber
		oriHash = cm.BlockHash
	}

	if err := cbft.verifyPrepareQC(oriNumber, oriHash, prepareQC); err != nil {
		return nil, err
	}

	return vnode, nil
}

if needViewChangeQC(cm) && cm.ViewChangeQC == nil {
			return nil, fmt.Errorf("prepareBlock need ViewChangeQC,index:%d", prepareQC.BlockIndex)
		}

**Comment by zjsunzone** [comment]
Hi, 
The latest code fragment is as follows:
```go
func (cbft *Cbft) verifyConsensusMsg(msg ctypes.ConsensusMsg) (*cbfttypes.ValidateNode, error) {
	// check if the consensusMsg must take prepareQC, Otherwise maybe panic
	if err := cbft.checkPrepareQC(msg); err != nil {
		return nil, err
	}
	// Verify consensus msg signature
	if err := cbft.verifyConsensusSign(msg); err != nil {
		return nil, err
	}

	// Get validator of signer
	vnode, err := cbft.validatorPool.GetValidatorByIndex(msg.EpochNum(), msg.NodeIndex())

	if err != nil {
		return nil, authFailedError{err: errors.Wrap(err, "get validator failed")}
	}

	var (
		prepareQC *ctypes.QuorumCert
		oriNumber uint64
		oriHash   common.Hash
	)

	switch cm := msg.(type) {
	case *protocols.PrepareBlock:
		proposer := cbft.currentProposer()
		if uint32(proposer.Index) != msg.NodeIndex() {
			return nil, fmt.Errorf("current proposer index:%d, prepare block author index:%d", proposer.Index, msg.NodeIndex())
		}
		// BlockNum equal 1, the parent's block is genesis, doesn't has prepareQC
		// BlockIndex is not equal 0, this is not first block of current proposer
		if cm.BlockNum() == 1 || cm.BlockIndex != 0 {
			return vnode, nil
		}
		if err := cbft.checkViewChangeQC(cm); err != nil {
			return nil, err
		}
		prepareQC = cm.PrepareQC
		_, localQC := cbft.blockTree.FindBlockAndQC(cm.Block.ParentHash(), cm.Block.NumberU64()-1)
		if localQC == nil {
			return nil, fmt.Errorf("parentBlock and parentQC not exists,number:%d,hash:%s", cm.Block.NumberU64()-1, cm.Block.ParentHash())
		}
		oriNumber = localQC.BlockNumber
		oriHash = localQC.BlockHash

	case *protocols.PrepareVote:
		if cm.BlockNum() == 1 {
			return vnode, nil
		}
		prepareQC = cm.ParentQC
		if cm.BlockIndex == 0 {
			_, localQC := cbft.blockTree.FindBlockAndQC(prepareQC.BlockHash, cm.BlockNumber-1)
			if localQC == nil {
				return nil, fmt.Errorf("parentBlock and parentQC not exists,number:%d,hash:%s", cm.BlockNumber-1, prepareQC.BlockHash.String())
			}
			oriNumber = localQC.BlockNumber
			oriHash = localQC.BlockHash
		} else {
			parentBlock := cbft.state.ViewBlockByIndex(cm.BlockIndex - 1)
			oriNumber = parentBlock.NumberU64()
			oriHash = parentBlock.Hash()
		}

	case *protocols.ViewChange:
		// Genesis block doesn't has prepareQC
		if cm.BlockNumber == 0 {
			return vnode, nil
		}
		prepareQC = cm.PrepareQC
		oriNumber = cm.BlockNumber
		oriHash = cm.BlockHash
	}

	if err := cbft.verifyPrepareQC(oriNumber, oriHash, prepareQC); err != nil {
		return nil, err
	}

	return vnode, nil
}
```

**Comment by shinnng** [comment]
The issue has been resolved, please use the latest version.
