### ISSUE TITLE
Build failed

### ISSUE THREAD

**Issue by VosAmoWho** [PlatONnetwork/PlatON-Go#37]
Hi there,
     Build failed with error:
     `ls: cannot access '/home/hyperchain/PlatON-Go/life/resolver/softfloat': No such file or directory
/usr/lib/git-core/git-submodule: 83: /usr/lib/git-core/git-sh-setup: Cannot fork
build/build_deps.sh: line 43: cd: /home/hyperchain/PlatON-Go/life/resolver/softfloat/build/Linux-x86_64-GCC: No such file or directory
make[6130]: Entering directory '/home/hyperchain/PlatON-Go'
build/build_deps.sh
ls: cannot access '/home/hyperchain/PlatON-Go/life/resolver/softfloat': No such file or directory
/usr/lib/git-core/git-submodule: 7: /usr/lib/git-core/git-submodule: Cannot fork
/usr/lib/git-core/git-submodule: 83: /usr/lib/git-core/git-sh-setup: Cannot fork
build/build_deps.sh: line 43: cd: /home/hyperchain/PlatON-Go/life/resolver/softfloat/build/Linux-x86_64-GCC: No such file or directory
make[6131]: Entering directory '/home/hyperchain/PlatON-Go'
build/build_deps.sh
make[6131]: fork: Resource temporarily unavailable
make[6131]: Leaving directory '/home/hyperchain/PlatON-Go'
cp: cannot stat './softfloat.a': No such file or directory`

#### System information
    
PlatON version: `current master branch`
OS & Version:  Ubuntu 16.04.4

````

**Comment by TraceBundy** [comment]
You need to make sure if there is code in PlatON-Go/life/resolver/softfloat, if not, try update submodule

**Comment by jiangshangqifeng** [comment]
@VosAmoWho

**Comment by junjiequ123** [comment]
please use new version of 0.7.X, close this issue.  Documentation will be enriched after.
