### ISSUE TITLE
wal is not enabled, causing problems caused by restarting the node

### ISSUE THREAD

**Issue by qunchenlu** [PlatONnetwork/PlatON-Go#393]
Hi there,

please note that this is an issue tracker reserved for bug reports and feature requests.

#### System information

PlatON version: `0.7.1`
OS & Version: Linux
Commit hash : (if `develop`)

#### Expected behaviour
Since there is no WAL restart, two blocks are generated after restarting.

Currently no wal is enabled by default. It is recommended to enable it by default.

#### Backtrace

````
[backtrace]
````

**Comment by zjsunzone** [comment]
Hi,
WAL is enable by default. Please confirm whether the command is enabled or not.
