### ISSUE TITLE
error while loading shared libraries: libcurl.so.4

### ISSUE THREAD

**Issue by awake006** [PlatONnetwork/PlatON-Go#43]
Hi,
Appears when I use platon initialization，
error:
error while loading shared libraries: libcurl.so.4: cannot open shared object file: No such file or directory
#### System information

PlatON version: 0.4
OS & Version: ubuntu16.04
Commit hash : (if `develop`)

**Comment by jiangshangqifeng** [comment]
````
# download the mpclib
$ wget https://download.platon.network/0.5/platon-mpclib-ubuntu-amd64-0.5.0.tar.gz

$ tar -xvzf platon-mpclib-ubuntu-amd64-0.5.0.tar.gz

$ mv platon-mpclib-ubuntu-amd64-0.5.0 platon-mpclib

# add mpclib to LD_LIBRARY_PATH eg: 
$ grep "export LD_LIBRARY_PATH=\$LD_LIBRARY_PATH:/path/to/platon-mpclib" ~/.bashrc || echo "export LD_LIBRARY_PATH=\$LD_LIBRARY_PATH:/path/to/platon-mpclib" >> ~/.bashrc

$ export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/path/to/platon-mpclib

$ env | grep LD_LIBRARY_PATH
LD_LIBRARY_PATH=:/path/to/platon-mpclib
````
try this

**Comment by awake006** [comment]
> ```
> # download the mpclib
> $ wget https://download.platon.network/0.5/platon-mpclib-ubuntu-amd64-0.5.0.tar.gz
> 
> $ tar -xvzf platon-mpclib-ubuntu-amd64-0.5.0.tar.gz
> 
> $ mv platon-mpclib-ubuntu-amd64-0.5.0 platon-mpclib
> 
> # add mpclib to LD_LIBRARY_PATH eg: 
> $ grep "export LD_LIBRARY_PATH=\$LD_LIBRARY_PATH:/path/to/platon-mpclib" ~/.bashrc || echo "export LD_LIBRARY_PATH=\$LD_LIBRARY_PATH:/path/to/platon-mpclib" >> ~/.bashrc
> 
> $ export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/path/to/platon-mpclib
> 
> $ env | grep LD_LIBRARY_PATH
> LD_LIBRARY_PATH=:/path/to/platon-mpclib
> ```
> try this

Thank you, according to the steps you gave, I successfully solved this issue.
