### ISSUE TITLE
Overprint Logs in Unit Test Code Causes Memory Overflow Problem

### ISSUE THREAD

**Issue by renshengruxi666** [PlatONnetwork/PlatON-Go#432]
Hi there,

please note that this is an issue tracker reserved for bug reports and feature requests.

#### System information

PlatON version: `platon version`
OS & Version: Windows/Linux/OSX
Commit hash : (if `develop`)

#### Backtrace

````
[backtrace]
````

**Comment by zjsunzone** [comment]
Hi,
    The bug has been optimized,  thank you for your question.
