### ISSUE TITLE
 failed to restarting node

### ISSUE THREAD

**Issue by cheng762** [PlatONnetwork/PlatON-Go#456]
Hi there,

please note that this is an issue tracker reserved for bug reports and feature requests.

#### System information

PlatON version: `feature/bump-version-to-0.7.2`
OS & Version: Windows/Linux/OSX
Serial number: #PLATON-505

#### Actual behaviour
Shut down the node, restart it, the node will repeat 261 times and it will not succeed.

**Comment by zjsunzone** [comment]
Hi,
In determining whether the block logic is: 
```
cbft.state.NumViewBlocks() >= cbft.config.Sys.Amount 
```
is changed to:  
```
cbft.state.NextViewBlockIndex() >= cbft.config.Sys.Amount
```
