### ISSUE TITLE
 wget platon-ubuntu-amd64-0.5.0.tar.gz version error

### ISSUE THREAD

**Issue by awake006** [PlatONnetwork/PlatON-Go#46]
Hi,
I refer to the official website，
` wget https://download.platon.network/0.5/platon-ubuntu-amd64-0.5.0.tar.gz`
'''
`./platon version`
![image](https://user-images.githubusercontent.com/26763721/55155777-31429400-5193-11e9-8828-ff1467ab453b.png)

**Comment by Vivi728** [comment]
Version issues have been resolved
