### ISSUE TITLE
Samurai钱包客户端区块未同步完成时，发起交易失败

### ISSUE THREAD

**Issue by chenxiaodai** [PlatONnetwork/PlatON-Go#47]
Hi there,

please note that this is an issue tracker reserved for bug reports and feature requests.

#### System information

PlatON version: `platon version`        0.5.0
OS & Version: Windows/Linux/OSX        Windows
Commit hash : (if `develop`)

#### Expected behaviour
success

#### Actual behaviour
fail

#### Backtrace

````
[backtrace]
````

**Comment by chenxiaodai** [comment]
应该是交易未转发成功

**Comment by niuxiaojie81** [comment]
Thank you for your question, in this case may indeed happen. We will fix this bug soon
