### ISSUE TITLE
Change the configuration file cbft.json and observe the block time

### ISSUE THREAD

**Issue by wyq5610522** [PlatONnetwork/PlatON-Go#48]
Hi ,

I changed the cbft.json file field to period: duration=3:30
But the block time is still 1s out of the block.

I hope to get your answer

System information
PlatON version: pangu_dev
OS & Version: ubuntu16.04
Commit hash : (if develop)

**Comment by bglmmz** [comment]
Yes, it is a bug, next version will fix it.
