### ISSUE TITLE
I called the CandidateWithdraw, but it didn't succeed. 

### ISSUE THREAD

**Issue by shinnng** [PlatONnetwork/PlatON-Go#49]
Hi,

I called the CandidateWithdraw, but it didn't succeed.  I tried to call it again and it worked.

System information
PlatON version: `platon 0.5.0`
OS & Version: Ubuntu 5.3.1

**Comment by jiangshangqifeng** [comment]
so you called it by RPC? or Samurai?  
what's the error message said?

**Comment by shinnng** [comment]
I'm using RPC,  it return success, but not work actually.

**Comment by GavinXu520** [comment]
This bug will be fixed in the next version
