### ISSUE TITLE
Unreasonable configuration parameters, resulting in switching consensus round cannot block

### ISSUE THREAD

**Issue by shinnng** [PlatONnetwork/PlatON-Go#494]
hese parameters did not previously limit the maximum and minimum values: ExpectedMinutes、PerRoundBlocks、ValidatorCount

**Comment by GavinXu520** [comment]
These parameters have not been limited by the minimum value before, and the minimum value is specific. If you can't think of a suitable number, you need to repeatedly think about it, but the default configuration parameters are in line with normal logic.
Use the correct parameter configuration， Plaese!
