### ISSUE TITLE
Switching failure on packet loss rate is 15%

### ISSUE THREAD

**Issue by chenxiaodai** [PlatONnetwork/PlatON-Go#498]
Hi there,

The ring network test increases the disk IO and CPU load verification scenarios, and the packet loss rate is 15%. Switching failure

#### System information

PlatON version: feature/bump-version-to-0.7.2
OS & Version: Linux
Commit hash : (if develop)
Serial number: #PLATON-426

#### Backtrace

````
[backtrace]
````

**Comment by zjsunzone** [comment]
What is the network structure tested?
