### ISSUE TITLE
Contract's balance is not enough

### ISSUE THREAD

**Issue by shinnng** [PlatONnetwork/PlatON-Go#50]
Hi,

An error occurred when I called CandidateWithdraw: 
  --Failed to CandidateWithdraw to RefundBalance RefundBalance return err: ="Contract's balance is not enough"

System information
PlatON version: platon 0.6.0
OS & Version: Ubuntu 5.3.1

**Comment by GavinXu520** [comment]
This bug has been fixed and the code will be uploaded soon!
