### ISSUE TITLE
The node is abnormally punished, and the returned stakes is inconsistent with expectations.

### ISSUE THREAD

**Issue by biganxin** [PlatONnetwork/PlatON-Go#536]
Hi there,

#### System information
PlatON version: `0.7.2`
OS & Version: Linux
Serial Number: #PLATON-445

#### Steps to reproduce the behaviour
After the staking is successfully executed using the lock amount, during the lockout period, the node is manually stopped, the node is kicked out of the list by the system penalty, and after the stakes is returned, the remaining lock amount is found to be incorrect.

#### Expected
The punishment logic is correct and the returned stakes is correct.

[Log]
[Uploading PLATON-445.zip…]()

**Comment by GavinXu520** [comment]
Reason: In the penalty kicking logic, there is no certifier who has punished the revoked action and then punishes the certifier. This causes the certifier to receive the penalty multiple times and deduct more money, which leads to the cancellation of the payment. Expected asymmetry.

Solution: In the penalty kicking logic, whether or not you have taken the initiative to cancel before being punished, as long as you receive the penalty, the list of verifiers is eliminated.
