### ISSUE TITLE
Change local version (large version unchanged, only minor version changed), version declaration failed

### ISSUE THREAD

**Issue by biganxin** [PlatONnetwork/PlatON-Go#538]
Hi there,

#### System information
PlatON version: `0.7.1`
OS & Version: Linux
Serial Number: #PLATON-449

#### Steps to reproduce the behaviour
Pre-conditions: the chain version is: 0.7.1, and the upgrade proposal version is: 0.8.1.

The node has voted on the upgrade proposal

Operation steps: The node changes the local version and changes it to 0.8.0/0.8.9 to make the version declaration.

Result: Version declaration failed

#### Expected behaviour
success

[Log]
..

**Comment by bglmmz** [comment]
the minor version  is not handled properly, this will fixed in v0.7.2.
