### ISSUE TITLE
The node is staked using the balance of the Restricted , and the node is punished and the stakes is released back to the lock contract. The Restricted  plan information is displayed incorrectly.

### ISSUE THREAD

**Issue by biganxin** [PlatONnetwork/PlatON-Go#548]
Hi there,

#### System information

PlatON version: `0.7.1`
OS & Version: Linux
Serial Number: #PLATON-452

#### Steps to reproduce the behaviour
1. Staking  with Restricted  amount

2, Stop the node after the lock period

3, After the node is punished, waiting for the lock release block high

4. View the information of the Restricting Plan, indicating that the debt information is incorrect.

#### Expected behaviour
correct

[Log]
[PLATON-452.zip](https://github.com/PlatONnetwork/PlatON-Go/files/3694321/PLATON-452.zip)

**Comment by cheng762** [comment]
After the lockout amount is canceled, after the lockout is released, the lockout information is not correctly deleted.
