### ISSUE TITLE
Use the Restricted balance to staking the node, enter the restricted release block high, the node requests to exit, the restricted plan information is displayed incorrectly

### ISSUE THREAD

**Issue by biganxin** [PlatONnetwork/PlatON-Go#549]
Hi there,

#### System information
PlatON version: `0.7.1`
OS & Version: Linu
Serial Number: #PLATON-453

#### Steps to reproduce the behaviour
1. Staking  with Restricted  amount

2. Arrive at the release block of the Restricting  plan and the node requests to exit.

3. After the stakes t is released to the Restricted account, check the Restricting Plan.

4, Prompt that the Restricting  plan has been deleted.

#### Expected
correct

[Log]
````

**Comment by cheng762** [comment]
this is a bug ,have fix now
