### ISSUE TITLE
How wavm worked in PlatON?

### ISSUE THREAD

**Issue by MaggieNgWu** [PlatONnetwork/PlatON-Go#55]
Platon used both evm and wavm, I was wondering how wavm worked, especially how to load and store data from the state MPT storage.
#
- What are the functions of ``$_Znwm, $_Znam, $_ZdlPv`` in wasm file?
- How to load contract data from MPT tree, which code do this?
- When and where store back contract data?

Thanks!

**Comment by MaggieNgWu** [comment]
I write a small contract, it output a temp cpp file.
```
#include "example3.hpp"

void example3::init() {}

void example3::setBalance(uint32_t b) {
  balance = b;
}

CONSTANT uint32_t example3::getBalance(){
  return balance;
}

//platon autogen begin
extern "C" { 
void init() {
example3 example3_platon;
example3_platon.init();
}
void setBalance(unsigned long w) {
example3 example3_platon;
example3_platon.setBalance(w);
}
unsigned long getBalance() {
example3 example3_platon;
return example3_platon.getBalance();
}
}
```
And a wasm file. It turn out a wat file:
```
(module
  (type $t0 (func))
  (type $t1 (func (param i32)))
  (type $t2 (func (result i32)))
  (func $f0 (type $t0))
  (func $init (export "init") (type $t0))
  (func $setBalance (export "setBalance") (type $t1) (param $p0 i32))
  (func $getBalance (export "getBalance") (type $t2) (result i32)
    (local $l0 i32)
    (get_local $l0))
  (table $T0 1 1 anyfunc)
  (memory $memory (export "memory") 2)
  (global $g0 (mut i32) (i32.const 66560))
  (global $__heap_base (export "__heap_base") i32 (i32.const 66560))
  (global $__data_end (export "__data_end") i32 (i32.const 1024)))
```
I was wondering where is the function body of function $setBalance?
```
(func $setBalance (export "setBalance") (type $t1) (param $p0 i32))
```

**Comment by woda0109** [comment]
Please submit "example3.hpp“.

**Comment by mowind** [comment]
`_Znwm` is operator new(unsigned long)
`_Znam` is operator new[](unsigned long)
`_ZdlPv` is operator delete(void*)

**Comment by MaggieNgWu** [comment]
Thank you very much for your quick reply.

The source code of my contract is here for your reference.
example3.hpp
```
#pragma once
#include <platon/platon.hpp>
using namespace platon;

class example3 : public Contract {
 public: 
  void init();
  uint32_t balance;

  void setBalance(uint32_t w);
  CONSTANT uint32_t getBalance();
};

// You must define ABI here.
PLATON_ABI(example3, init);
PLATON_ABI(example3, setBalance);
PLATON_ABI(example3, getBalance);
```

example3.cpp
```
#include "example3.hpp"

void example3::init() {}

void example3::setBalance(uint32_t b) {
  balance = b;
}

CONSTANT uint32_t example3::getBalance(){
  return balance;
}
```

**Comment by MaggieNgWu** [comment]
@mowind  Thanks. It's helpful.
I was wondering if you can answer me the other two questions.
- How to load contract data from MPT tree, before or within the function call? Which code do this operation?
- When and which code responsible for storing back contract data?

**Comment by woda0109** [comment]
@MaggieNgWu Reference code  https://github.com/PlatONnetwork/PlatON-Go/blob/a70b96d6083094a045439171a378c0d73709aab6/life/resolver/cplusplus.go#L156
https://github.com/PlatONnetwork/PlatON-Go/blob/a70b96d6083094a045439171a378c0d73709aab6/life/resolver/cplusplus.go#L157

**Comment by MaggieNgWu** [comment]
@woda0109 

I defined a variable “balance", I thought it would be store in MPT storage. But the compiled wasm file never called that "setState" function you mentioned. Actually the "setBalance" function have no function body.

```c++
#pragma once
#include <platon/platon.hpp>
using namespace platon;

class example3 : public Contract {
 public: 
  void init();
  uint32_t balance;
  void setBalance(uint32_t w);
  CONSTANT uint32_t getBalance();
};
...
```
```
(module
  (type $t0 (func))
  (type $t1 (func (param i32)))
  (type $t2 (func (result i32)))
  (func $f0 (type $t0))
  (func $init (export "init") (type $t0))
  (func $setBalance (export "setBalance") (type $t1) (param $p0 i32))
 ......
```

**Comment by woda0109** [comment]
Buildin type is defined StorageType 
https://github.com/PlatONnetwork/PlatON-CDT/blob/e3d9d97dd48f11060f07939bd189378768bc5297/libraries/platonlib/include/platon/storagetype.hpp#L141

**Comment by MaggieNgWu** [comment]
I'm not sure what's that mean. Can this explain why the "setBalance" function body missing? Or other questions? 

> Buildin type is defined StorageType
> https://github.com/PlatONnetwork/PlatON-CDT/blob/e3d9d97dd48f11060f07939bd189378768bc5297/libraries/platonlib/include/platon/storagetype.hpp#L141

**Comment by woda0109** [comment]
"balance" is not defined storage type, compiler optimization level is O3. "balance" is unused member variable.

**Comment by MaggieNgWu** [comment]
How to define a storage type? Thanks a lot!

**Comment by woda0109** [comment]
Reference code https://github.com/PlatONnetwork/PlatON-CDT/blob/e3d9d97dd48f11060f07939bd189378768bc5297/tests/unit/storagetype_special.cpp

**Comment by MaggieNgWu** [comment]
Do you mean that I should define "balance" as type "Int" which is a storage type, instead of "int32_t"?

```c++
#pragma once
#include <platon/platon.hpp>
using namespace platon;

class example3 : public Contract {
 public: 
  void init();
  Int balance;

  void setBalance(uint32_t w);
  CONSTANT Int getBalance();
};

// You must define ABI here.
PLATON_ABI(example3, init);
PLATON_ABI(example3, setBalance);
PLATON_ABI(example3, getBalance);
```

**Comment by MaggieNgWu** [comment]
@woda0109 
Thanks a lot. Your answer is very clear and helpful.

**Comment by MaggieNgWu** [comment]
我写了以下代码，试图定义一个Storage Type。但编译时出错了。我想问：
- 我的这种写法是否正确，如果不正确， 那么正确的方式是什么样的？
- 当返回类型和参数类型为自定义类型时，编译成WASM会出错。是PlatON现在并不支持自定义的参数类型或者返回值类型吗？PlatON支持的参数类型和返回值类型有哪些呢？

example3.hpp:
```c++
#pragma once
#include <platon/platon.hpp>
using namespace platon;

char temp[4] = "bb";

class example3 : public Contract {
 public: 
  void init();
  Int<temp> balance;

  void setBalance(Int<temp> w);
  CONSTANT Int<temp> getBalance();
};

// You must define ABI here.
PLATON_ABI(example3, init);
PLATON_ABI(example3, setBalance);
PLATON_ABI(example3, getBalance);
```
example.cpp:
```c++
#include "example3.hpp"

void example3::init() {}

void example3::setBalance(Int<temp> b) {
  balance = b.get();
}

CONSTANT Int<temp> example3::getBalance(){
   return balance.get();
 }
```

**Comment by woda0109** [comment]
return value is must buildin type, so abi function is enabled define

```
void setBalance(int w) {
*balance = w;
}
int getBalance(){
return *balance;
}
```

**Comment by MaggieNgWu** [comment]
Thanks a lot!

**Comment by MaggieNgWu** [comment]
使用这种Storage类型Int时，底层是如何调用malloc分配内存的?
