### ISSUE TITLE
undelegate the unlocked delegate and find that a node does not Production block

### ISSUE THREAD

**Issue by biganxin** [PlatONnetwork/PlatON-Go#550]
Hi there,
#### System information
PlatON version: `0.7.0`
OS & Version: Linux
Serial Number: #PLATON-454

#### Steps to reproduce the behaviour
undelegate the unlocked delegate and find that a node does not Production block

#### Expected 
Normal production block

[log]
````
![image](https://user-images.githubusercontent.com/29141931/66269231-b4e2e900-e878-11e9-9d28-63901e25dec9.png)

**Comment by GavinXu520** [comment]
When revoking the entrustment, when verifying the balance in the entrustment details, the balance of the staking contract is checked first, and the panic is manually thrown. When the revocation is cancelled, if the revocation amount is large (more than staking) The balance of the contract) will throw panic.

Solution: The previously added balance of the staking contract is judged and the logic of manually panic is somewhat redundant. Now delete these logics. You can compare the balance in the original commission details with the amount you entered when you initiated the cancellation!

**Comment by GavinXu520** [comment]
The reason:
When withdrew the delegation, and then verifying the balance in the delegation, the balance of the staking contract is checked first, nd the panic is manually thrown. 
if the amount of withdrew delegation is large (more than balance of staking contract) will throw panic.

The solution:
The previously added logic for judging the balance of the staking contract and manually throwing the panic is somewhat redundant, and now these logics are removed. The balance between the original entrusted details and the amount entered when the revocation is initiated can be compared.
