### ISSUE TITLE
[Proposal] After the node uses the lower version to vote, it will cause bad block.

### ISSUE THREAD

**Issue by biganxin** [PlatONnetwork/PlatON-Go#557]
Hi there,

#### System information
PlatON version: `0.7.2`
OS & Version: Linux
Serial Number: #PLATON-473

#### Steps to reproduce the behaviour
1. For example, use the underlying code with version v0.7.1.1 to modify only the version number v1.0.0 for voting on version upgrade.
2. When deploying the chain, use the version number v0.7.1.2
3. The A node initiates the upgrade proposal, and the Node B votes for the proposal after the v1.0.0 upgrade. After the voting is successful, the chain stops.

#### Expected behaviour

````
[log]
````

**Comment by bglmmz** [comment]
Obviously the node B is a Byzantine Node, and the number of Byzantine Node more than f in your test environment, and, actually the blocks are not compatible between v0.7.1.1 and v0.7.1.2.  So, please make sure the number Byzantine Node less than f, or stake more valid nodes to be verifiers, PlatON will kict out the Byzantine Nodes from consensus nodes,  and fill up the consensus nodes from the verifiers list, so, the PlatON will keep moving on.
