### ISSUE TITLE
Why PlatON wasm vm supports memory malloc functions

### ISSUE THREAD

**Issue by MaggieNgWu** [PlatONnetwork/PlatON-Go#56]
Hi, guys

I was wondering why PlotON VM supply functions of "malloc" and "free" memory.

```go
"malloc":  &exec.FunctionImport{Execute: envMalloc, GasCost: envMallocGasCost},
"free":    &exec.FunctionImport{Execute: envFree, GasCost: envFreeGasCost},
"calloc":  &exec.FunctionImport{Execute: envCalloc, GasCost: envCallocGasCost},
"realloc": &exec.FunctionImport{Execute: envRealloc, GasCost: envReallocGasCost},
```

This struct seems like defined by PlatON.  As I have known, memory in WAVM is a byte array, used by program to store string and other values. The memory can be managed by WAVM. So, __why PlatON would like to define this Memory structure and supply "malloc" function for smart contracts?__

```go
type Memory struct {
	Memory []byte
	Start  int //start position for malloc
	Size   int //memory size for malloc
	tree   []int
}
```

**Comment by woda0109** [comment]
Efficient use of memory, reusing destructed memory.

**Comment by MaggieNgWu** [comment]
What is the mechanism of the memory use?/ How PlatON manage wavm memory?
(We can use Chinese if you like)

**Comment by jiangshangqifeng** [comment]
The question you mentioned is more detailed and may not be clearly described in a few words. Do you have any problems during the specific application development process? You can send a look at the specific problems you have encountered. thx @MaggieNgWu

**Comment by MaggieNgWu** [comment]
Let's make it simple. In which case, a smart contract wasm code would call "malloc" function?

**Comment by MaggieNgWu** [comment]
Let's make it simple. In which case, a smart contract wasm code would call "malloc" function?

**Comment by jiangshangqifeng** [comment]
you can use ‘malloc' as you need
I suggest you debug the code and see the details ：）

**Comment by MaggieNgWu** [comment]
Would you please make an example?
