### ISSUE TITLE
No undo record was added to the failed node when penalized

### ISSUE THREAD

**Issue by danielgogo** [PlatONnetwork/PlatON-Go#572]
PLATON-217 To be penalized for passively withdrawing from the candidature, there is no revocation record, resulting in the revocation of the money frozen forever, resulting in the verifier cannot be repledged!

**Comment by GavinXu520** [comment]
The same to issue 575:
https://github.com/PlatONnetwork/PlatON-Go/issues/575

Plaese, look at that.
