### ISSUE TITLE
Failure to clear the details of invalid candidates without money when penalizing

### ISSUE THREAD

**Issue by MrHurricaner** [PlatONnetwork/PlatON-Go#575]
PLATON-213 In addition, when emptying the details of the candidate, the lock warehouse should be informed to clear the lock warehouse information. This is a boundary case, which was not detected by the self-test before and was omitted, which was found by the code walk.

**Comment by GavinXu520** [comment]
The reason:
When slashing, do not clean details of the candidate who will be slashed a number of times and the balance is 0! And when the candidate details are emptied, the restictingPlan plugin is also notified to clear the resticting plun information.
The solution:
At the time of slashing, if the node still has a lock period of von, add the unstaking record, and if the balance of it is 0, delete the staking details.
