### ISSUE TITLE
Release lock logic in lock lock plug-in, logic that causes storage of invalid data

### ISSUE THREAD

**Issue by xingquba** [PlatONnetwork/PlatON-Go#577]
PLatON-211 The logic of releasing the lock amount in the lock plug-in does not judge whether the lock details are invalid. Instead, after the lock is released, the lock details of the fully released lock will be directly stored back to stateDB regardless of whether there is any available unreleased lock plan, resulting in a waste of resources!

**Comment by cheng762** [comment]
this issue have reslove in 0.7.3+，now will del all empty restring info
