### ISSUE TITLE
Code optimization

### ISSUE THREAD

**Issue by MrHurricaner** [PlatONnetwork/PlatON-Go#581]
PLATON-203 Phenomenon analysis: there are parts of the code logic that need to be optimized.
1. Concurrent lock mechanism. When obtaining the number of nodes missing viewChange in the process of viewChange synchronization, concurrent protection or serial execution is required

**Comment by zjsunzone** [comment]
Code change scenario: 
1. avoid concurrency issues by using the chan mechanism.
