### ISSUE TITLE
"BAD BLOCK" appears on the non-consensus node   Error: invalid vrf prove

### ISSUE THREAD

**Issue by liuhangya** [PlatONnetwork/PlatON-Go#587]
Hi there,

#### System information

PlatON version: `0.7.2`
OS & Version: Linux
Serial Number: #PLATON-487

#### Steps to reproduce the behaviour
See log for details.

#### Expected behaviour

[log]
[PLATON-487.zip](https://github.com/PlatONnetwork/PlatON-Go/files/3720159/PLATON-487.zip)

**Comment by zjsunzone** [comment]
Maybe the same problem #445 .
