### ISSUE TITLE
[Lock pledge] Use the lock position plan amount pledge node, the error code returned after exceeding the lock order plan amount is incorrect.

### ISSUE THREAD

**Issue by liuhangya** [PlatONnetwork/PlatON-Go#589]
Hi there,

#### System information

PlatON version: `0.7.2`
OS & Version: Linux
Serial Number: #PLATON-482

#### Steps to reproduce the behaviour

1, create a lock warehouse plan amount: 10000000

2, with the lock warehouse pledge node amount: 10000001

3, the error code returned is incorrect

{'Code': 304004, 'Data': '', 'ErrMsg': 'the balance is not enough in restrict'}

#### Expected behaviour

[log]

**Comment by cheng762** [comment]
hi,the issues  have sovled in version highter than 0.7.2
