### ISSUE TITLE
Consistency between PrepareQC and native message package number and hash need to be check.

### ISSUE THREAD

**Issue by NedColin** [PlatONnetwork/PlatON-Go#596]
Hi there,

please note that this is an issue tracker reserved for bug reports and feature requests.

System information
PlatON version: 0.7.1
OS & Version: Ubuntu 18.04
Serial Number: #PLATON-309

**Comment by zjsunzone** [comment]
Hi,

We will add a check for message consistency

**Comment by benbaley** [comment]
close by done
