### ISSUE TITLE
PrepareBlock messages are processed multiple times.

### ISSUE THREAD

**Issue by NedColin** [PlatONnetwork/PlatON-Go#597]
Hi there,

please note that this is an issue tracker reserved for bug reports and feature requests.

System information
PlatON version: 0.7.1
OS & Version: Ubuntu 18.04
Serial Number: #PLATON-307

**Comment by zjsunzone** [comment]
In the code receiveLoop, there is filtering processing for successfully processing MsgHash messages.

**Comment by benbaley** [comment]
close by done
