### ISSUE TITLE
The problem of nonuniform block producing on 25+10 nodes

### ISSUE THREAD

**Issue by NedColin** [PlatONnetwork/PlatON-Go#598]
Hi there,

please note that this is an issue tracker reserved for bug reports and feature requests.

System information
PlatON version: 0.7.1
OS & Version: Ubuntu 18.04
Serial Number: #PLATON-305

Description：
It was mainly manifested in the cluster which could not package blocks for a long time after a period of stress test, and the view change required more time than usual.

**Comment by zjsunzone** [comment]
The main cause of the problem is that the DDOS attack queue is full, causing the connection to close immediately and not to be blocked. The reason why the DDOS message queue is full is that the logical order of message filtering is incorrect, and the message queue is deleted in time.

**Comment by benbaley** [comment]
close by done
