### ISSUE TITLE
【0.7.3】After the node is punished, the updateStakingInfo transaction is initiated successfully.

### ISSUE THREAD

**Issue by wyq5610522** [PlatONnetwork/PlatON-Go#637]
After the node is punished, the updateStakingInfo transaction is initiated successfully.
Expectation: failure
Actual: successful

**Comment by GavinXu520** [comment]
What？ I don't unstand this question meaning?

**Comment by GavinXu520** [comment]
Please, talk me clear about this question. Thank you~
