### ISSUE TITLE
dead code appears in 'update-license.go'

### ISSUE THREAD

**Issue by benbaley** [PlatONnetwork/PlatON-Go#702]
Hi there,

please note that this is an issue tracker reserved for bug reports and feature requests.

#### System information

PlatON version: `feature/bump-version-to-0.7.4`
OS & Version: Windows/Linux/OSX
Commit hash : (if `develop`)

#### Expected behaviour

Refactor this piece of code to not have any dead code after this "return".
![image](https://user-images.githubusercontent.com/45843736/68392011-cbe06800-01a3-11ea-957b-bcca6b0ccb6b.png)

#### Backtrace

````
[backtrace]
````

**Comment by zhouxi-jzheng** [comment]
Please give feedback.Why dead code appears？

**Comment by benbaley** [comment]
this had been fixed in 0.7.4
