### ISSUE TITLE
After the voting deadline，the interface of getAccuVerifiersCount returned information is incorrect.

### ISSUE THREAD

**Issue by lipingD** [PlatONnetwork/PlatON-Go#707]
After the voting deadline， the voting information is cleared.the interface of getAccuVerifiersCount returned information is incorrect.

**Comment by bglmmz** [comment]
After the vote is over，user shuold call getTallyResult instead of getAccuVerifiersCount.

**Comment by zhouxi-jzheng** [comment]
Confirm it is not a problem, please close the problem
