### ISSUE TITLE
The actual value of the maximum gas limit of the block queried is larger than the preset value of the system

### ISSUE THREAD

**Issue by qiusese** [PlatONnetwork/PlatON-Go#708]
PlatON version: `platon 0.7.4`
OS & Version: Windows/Linux/OSX

1、The maximum gas limit of the default block queried is 100800000
2、View receipt return information of packed block（Block contains 76 transactions）
3、Receipt return information：'gasLimit': 40112162212 Out of system preset

**Comment by GavinXu520** [comment]
Is this initial gasLimit useing by your own genesis.json? If so, this is normal.

**Comment by GavinXu520** [comment]
Is this initial gasLimit using by your own genesis.json? If so, this is normal.

**Comment by GavinXu520** [comment]
Suggestion using '4712388' for gasLimit in your genesis.json

**Comment by zhouxi-jzheng** [comment]
This is not a problem. Please close it @qiusese
