### ISSUE TITLE
Unit test cannot pass

### ISSUE THREAD

**Issue by jiangshangqifeng** [PlatONnetwork/PlatON-Go#709]
Hi there,

please note that this is an issue tracker reserved for bug reports and feature requests.

#### System information

PlatON version: `feature/bump-version-to-0.7.4`
OS & Version: Windows/Linux/OSX
Commit hash : (if `develop`)

#### Expected behaviour
Unit test pass

#### Actual behaviour
errors occur!

#### Backtrace
--- FAIL: TestGovContract_SubmitParam_GetAccuVerifiers (0.00s)
        gov_contract_test.go:272: setup()......
        gov_contract_test.go:1256: the expected resultCode: 0
        Error Trace:    gov_contract_test.go:1241
                        gov_contract_test.go:456
        Error:          Should be true
        gov_contract_test.go:1256: the expected resultCode: 0
        gov_contract_test.go:300: tear down()......
--- FAIL: TestGovContract_SubmitParam_Pass (0.63s)
        gov_contract_test.go:272: setup()......
        gov_contract_test.go:1256: the expected resultCode: 0
        Error Trace:    gov_contract_test.go:1241
                        gov_contract_test.go:480
        Error:          Should be true
        gov_contract_test.go:1256: the expected resultCode: 0
        gov_contract_test.go:503: the result status 2 yeas 3 accuVerifiers 3
        gov_contract_test.go:300: tear down()......
0x000000000000000000000000000000000001046a
buildDbRestrictingPlan, store addr 0x0eEf233120cE31b3FAc20DAC379db243021A5234 balance 600000000000000000000000000 epochs 1

buildDbRestrictingPlan, store addr 0x0eEf233120cE31b3FAc20DAC379db243021A5234 balance 999999999999999999999999 epochs 1

buildDbRestrictingPlan, store addr 0x0eEf233120cE31b3FAc20DAC379db243021A5234 balance 1000000000000000000000000 epochs 1

FAIL
FAIL    github.com/PlatONnetwork/PlatON-Go/core/vm      4.908s
````
[backtrace]
````

**Comment by luo-dahui** [comment]
The creation block hash was not modified in the unit test, so it has been modified in the latest version.

**Comment by luo-dahui** [comment]
The creation block hash was not modified in the unit test, so it has been modified in the latest version.

**Comment by benbaley** [comment]
close by done
