### ISSUE TITLE
Optimize the storage of the blockchain.

### ISSUE THREAD

**Issue by benbaley** [PlatONnetwork/PlatON-Go#714]
Reducing the total disk space occupied by the blockchain storage.
The following content can be cleaned regularly or automatically after timeout
- Receipt
- Preimage
- MPT

**Comment by TraceBundy** [comment]
The historical state of the cleanup mainly includes the history of the history, the history of the MPT, and the Receipt can be cleaned up very simply. The MPT history needs to reference the MPT of different blocks, and the reference count is zero, which can be cleaned up.

**Comment by zhouxi-jzheng** [comment]
If the  Milestone v0.7.4 issue is resolved, close it as soon as possible

**Comment by zhouxi-jzheng** [comment]
Is this enhancement done

**Comment by benbaley** [comment]
close by done
