### ISSUE TITLE
listGovernParam interface returns information is incorrect；

### ISSUE THREAD

**Issue by lipingD** [PlatONnetwork/PlatON-Go#717]
一、minimum amount of stake, range：[1000000000000000000000000, +∞) LAT ；
       minimum amount of stake increasing funds, delegation funds, or delegation withdrawing funds, range：[10000000000000000000, +∞) LAT；
   ‘LAT’ should be removed

二、maximum gas limit per block, range：(4200000, +∞)
4200000 should be changed to 4712388

三、Whether the returned module and name need lowercase，   to be confirmed

@GavinXu520

**Comment by GavinXu520** [comment]
The first and second points have been revised! The third point of our design is to capitalize the first letter, about the detailed of the third point let  @bglmmz to answer.

**Comment by zhouxi-jzheng** [comment]
@bglmmz Can you answer this question

**Comment by bglmmz** [comment]
Yes,  all the values  of module and parameter  involved in ParamProposal are lower camel case.
@lipingD
