### ISSUE TITLE
After the warehouse locking verifier returns the pledge deposit and waits for the warehouse locking release, the pledge information is not cleared

### ISSUE THREAD

**Issue by qiusese** [PlatONnetwork/PlatON-Go#724]
PlatON version: `platon 0.7.4`
OS & Version: Windows/Linux/OSX

1. Create a lock plan with a lock release cycle of 1
2. Pledge node with lock in amount
3. Waiting for the end of settlement cycle
4. Application for return of deposit
5. Wait for the end of two settlement cycles
6. Create a new lock plan with the original wallet address
7. The pledge information before the lock in plan has not been cleared
![image](https://user-images.githubusercontent.com/48665478/68636519-b7e78e00-0536-11ea-83ac-212aac29e91f.png)

**Comment by mowind** [comment]
When call `SetState(addr, key, []byte{})`, the key delete from state, but still in parent's state. At the next state call `GetState(addr, key)` unexpected return historical value, is not  our hoped.

**Comment by mowind** [comment]
We are treat empty value as a normal value, without storage, only for read. I think will fix this issue. #730

**Comment by zhouxi-jzheng** [comment]
Has this problem been solved?
