### ISSUE TITLE
The amount of the locked warehouse is pledged, and the amount will be returned to the pledge deposit after release. The error code of the locked warehouse plan is incorrect

### ISSUE THREAD

**Issue by qiusese** [PlatONnetwork/PlatON-Go#742]
PlatON version: `platon 0.7.4`
OS & Version: Windows/Linux/OSX

1. Create a lock in plan and pledge the node with the lock in amount（Lock period: 1）
2. Amount to be released
3. Apply for returning the pledge and query the lock in plan
4. Code display error of transaction receipt: 1

**Comment by cheng762** [comment]
the error code should be return 304005,will fix it soon

**Comment by cheng762** [comment]
#749
