### ISSUE TITLE
The parameter MaxBlockGasLimit、StakeThreshold、OperatingThreshold、 needs to set the maximum value， not the +00

### ISSUE THREAD

**Issue by lipingD** [PlatONnetwork/PlatON-Go#744]
The parameter MaxBlockGasLimit、StakeThreshold、OperatingThreshold、 needs to set the maximum value， not the +00；
@GavinXu520

**Comment by benbaley** [comment]
this had been fixed by https://github.com/PlatONnetwork/PlatON-Go/pull/748
now the range are:

MaxBlockGasLimit： [4712388, 210000000] unit ：VON
OperatingThreshold: [10, 10000]  unitLAT                   
StakeThreshold:         [1000000, 10000000]  unit LAT
