### ISSUE TITLE
Transfer transaction， check receipt timeout

### ISSUE THREAD

**Issue by lipingD** [PlatONnetwork/PlatON-Go#756]
v0.7.3.3

@zjsunzone

**Comment by zjsunzone** [comment]
Please provide transaction hash, timeout occurred。

**Comment by zjsunzone** [comment]
The main analysis is as follows：
1.When the node receives the transaction request, it has not connected to the network yet.
2.Message forwarding failed.

**Comment by zjsunzone** [comment]
Conclusion: This problem does not occur with real networks. 
@lipingD
