### ISSUE TITLE
The lock in plan information has not been cleared after the lock in account No. pledge is punished and all pledge amounts are deducted

### ISSUE THREAD

**Issue by qiusese** [PlatONnetwork/PlatON-Go#757]
PlatON version: `platon 0.7.4`
OS & Version: Windows/Linux/OSX

1. Create a lock in plan and pledge the node with the lock in amount
2. Stop the node and let the node trigger 0 block rate after the lock release period arrives.
3. Waiting for the end of the pledge locking period, the record of the warehouse locking plan has not been cleared

**Comment by cheng762** [comment]
this is abug, it is will del  Restricting info after slash the total mount.
fix in #758
