### ISSUE TITLE
Query consensus person validates that the shares field amount did not increase

### ISSUE THREAD

**Issue by wyq5610522** [PlatONnetwork/PlatON-Go#760]
Hi there,

PlatON version: `V0.7.4`
OS & Version: Linux

#### Test procedure:
1、The initial verifier initiated an increase of 100,000 LAT
2、After 5 consensus rounds
3、Query the getValidatorList interface

####expected result：
1、Query shares field increased by 100000

####actual result
1、Query that the shares field amount did not change

**Comment by GavinXu520** [comment]
This issue has been changed as expected

**Comment by GavinXu520** [comment]
Has been changed as expected

**Comment by wyq5610522** [comment]
Have validation
