### ISSUE TITLE
Support for governing system parameters

### ISSUE THREAD

**Issue by benbaley** [PlatONnetwork/PlatON-Go#762]
## Some params needed to be governed by PIP:
- SkasgBlocksReward
- MaxEvidenceAge
- SlashFractionDuplicateSign
- DuplicateSignReportReward
- StakeThreshold
- OperatingThreshold
- UnStakeFreezeDuration
- MaxValidators
- MaxBlockGasLimit
- MaxTxDatalimit

**Comment by zhouxi-jzheng** [comment]
Is this enhancement done

**Comment by benbaley** [comment]
close by done
