### ISSUE TITLE
After the lock in pledge is punished, the lock in plan is not cleared after the pledge deposit is returned

### ISSUE THREAD

**Issue by qiusese** [PlatONnetwork/PlatON-Go#769]
PlatON version: `platon 0.7.4`
OS & Version: Windows/Linux/OSX

1. Create warehouse locking plan and pledge node
2. Wait for the release amount of lock in plan
3. Wait for the pledge node to become the consensus verifier, and then the control node will stop blocking
4. After the node is punished (the penalty amount is less than the pledge amount), wait for the node amount to be returned
5. Query that the lock plan has not been cleared

**Comment by cheng762** [comment]
the restring  info    shoud be del after lock  return with zero balance, fix in  #767
