### ISSUE TITLE
Line 127 of file x/handler/vrf_handler.go and line 1017 of x/plugin/staking_plugin.go

### ISSUE THREAD

**Issue by qunchenlu** [PlatONnetwork/PlatON-Go#838]
Threat level: low

Problem analysis: If the call to the governance interface gov.GovernMaxValidators returns an error, the program logic cannot run normally.

Suggested fix: Is there a default value when the gov.GovernMaxValidators interface returns an error?

**Comment by GavinXu520** [comment]
When the value cannot be obtained, it indicates that an error has occurred. If the default value is returned at this time, it cannot be guaranteed that the default value is the value we expect, so the processing result of the program is still wrong.
