### ISSUE TITLE
Line 3024 of file x/plugin/staking_plugin.go

### ISSUE THREAD

**Issue by qunchenlu** [PlatONnetwork/PlatON-Go#839]
Threat level: low

Problem analysis: If gov.GovernUnStakeFreezeDuration returns an error, the pledge transaction cannot be run.

Suggested fix: Is there a default value when the gov.GovernUnStakeFreezeDuration interface returns an error?

**Comment by GavinXu520** [comment]
When the value cannot be obtained, it indicates that an error has occurred. If the default value is returned at this time, it cannot be guaranteed that the default value is the value we expect, so the processing result of the program is still wrong.
