### ISSUE TITLE
Line 188 of document x/gov/gov_params.go

### ISSUE THREAD

**Issue by qunchenlu** [PlatONnetwork/PlatON-Go#840]
Threat level: low

Problem analysis: There is no judgment on the situation in which GovernmentUnStakeFreezeDuration returns an error.

Suggested fix: When the GovernorUnStakeFreezeDuration interface returns an error, give a default value.

**Comment by GavinXu520** [comment]
Your idea is right. We will fix it in the next version

**Comment by zhouxi-jzheng** [comment]
Which version is next @GavinXu520 .Is version 0.7.5 resolved？
