### ISSUE TITLE
Lines 363 and 370 of file x/plugin/slashing_plugin.go

### ISSUE THREAD

**Issue by qunchenlu** [PlatONnetwork/PlatON-Go#841]
Threat level: low

Problem analysis: When gov.GovernSlashFractionDuplicateSign and gov.GovernDuplicateSignReportReward return errors, the punishment operation cannot run normally.

Suggested fix: When the interface returns an error, give a default value.

**Comment by zhouxi-jzheng** [comment]
@WeiLoy It has been 7 days, please arrange to explain this problem
