### ISSUE TITLE
Line 3053 of file x/plugin/staking_plugin.go and line 279 of x/plugin/slashing_plugin.go

### ISSUE THREAD

**Issue by qunchenlu** [PlatONnetwork/PlatON-Go#842]
Threat level: low

Problem analysis: When gov.GovernMaxEvidenceAge returns an error, the program logic cannot run normally.

Suggested fix: When the interface returns an error, give a default value.

**Comment by zhouxi-jzheng** [comment]
@WeiLoy It has been 7 days, please arrange to explain this problem
