### ISSUE TITLE
Line 117 of file x/plugin/slashing_plugin.go

### ISSUE THREAD

**Issue by qunchenlu** [PlatONnetwork/PlatON-Go#844]
Threat level: low

Problem analysis: When gov.GovernSlashBlocksReward returns an error, the penalty reward cannot be issued.

Suggested fix: When the gov.GovernSlashBlocksReward interface returns an error, give a default value.

**Comment by zhouxi-jzheng** [comment]
@WeiLoy It has been 7 days, please arrange to explain this problem
