### ISSUE TITLE
Line 235 of file eth/backend.go

### ISSUE THREAD

**Issue by qunchenlu** [PlatONnetwork/PlatON-Go#845]
Threat level: low

Problem Analysis: When gov.GovernMaxBlockGasLimit returns an error, the chain initialization does not work properly.

Suggested fix: When the gov.GovernMaxBlockGasLimit interface returns an error, give a default value. Core/block_validator.go has default values ​​for line 112.

**Comment by cheng762** [comment]
The gov.GovernMaxBlockGasLimit has been set in snapshotdb before. If it is not found, an error should be reported instead of the default value.

**Comment by cheng762** [comment]
Core/block_validator.go has default values，Because this method will be called by the mock function, the mock function does not write  gov.GovernMaxBlockGasLimit to the snapshotDB during the initialization process.
