### ISSUE TITLE
There is a mistake in the calculation of bonus after annual additional issuance

### ISSUE THREAD

**Issue by qiusese** [PlatONnetwork/PlatON-Go#883]
PlatON version: `platon 0.7.5`
OS & Version: Windows/Linux/OSX
Commit hash : (if `develop`)

1、Wait for the current year to pass
2、View the pledge reward and block out reward issued in the first settlement cycle of the new year

**Comment by WeiLoy** [comment]
After the increase issuance logic is extracted as a function, the sampling range for calculating the average block time is reduced by one settlement cycle.
