### ISSUE TITLE
Contract byte code maximum byte adjustment& verification 

### ISSUE THREAD

**Issue by kw805** [PlatONnetwork/PlatON-Go#919]
Hi there,

please note that this is an issue tracker reserved for bug reports and feature requests.

#### System information

PlatON version: `platon version`
OS & Version: Windows/Linux/OSX
Commit hash : (if `develop`)

#### Backtrace

````
[backtrace]
````

**Comment by zjsunzone** [comment]
Completion:
1. Reduced the size limit on contract code.
