### ISSUE TITLE
Transaction pool limit contract creation transaction adjustment + verification

### ISSUE THREAD

**Issue by kw805** [PlatONnetwork/PlatON-Go#920]
Hi there,

please note that this is an issue tracker reserved for bug reports and feature requests.

#### System information

PlatON version: `platon version`
OS & Version: Windows/Linux/OSX
Commit hash : (if `develop`)

#### Backtrace

````
[backtrace]
````

**Comment by zjsunzone** [comment]
@GavinXu520 @fksyuan

**Comment by zjsunzone** [comment]
After verification, the contract can be created normally.
