### ISSUE TITLE
The system contract supporting the virtual machine is adjusted from the home version to the Byzantine version + verification

### ISSUE THREAD

**Issue by kw805** [PlatONnetwork/PlatON-Go#922]
Hi there,

please note that this is an issue tracker reserved for bug reports and feature requests.

#### System information

PlatON version: `platon version`
OS & Version: Windows/Linux/OSX
Commit hash : (if `develop`)

#### Backtrace

````
[backtrace]
````

**Comment by zjsunzone** [comment]
The system contract supports the Byzantine version verification..
