### ISSUE TITLE
The default value for virtual machine support is adjusted to evm + authentication

### ISSUE THREAD

**Issue by kw805** [PlatONnetwork/PlatON-Go#923]
Hi there,

please note that this is an issue tracker reserved for bug reports and feature requests.

#### System information

PlatON version: `platon version`
OS & Version: Windows/Linux/OSX
Commit hash : (if `develop`)

#### Backtrace

````
[backtrace]
````

**Comment by zjsunzone** [comment]
No errors found through simple contract testing.
