### ISSUE TITLE
Step through the economic model invocation process to ensure that it does not enter the virtual machine

### ISSUE THREAD

**Issue by kw805** [PlatONnetwork/PlatON-Go#929]
Hi there,

please note that this is an issue tracker reserved for bug reports and feature requests.

#### System information

PlatON version: `platon version`
OS & Version: Windows/Linux/OSX
Commit hash : (if `develop`)

#### Backtrace

````
[backtrace]
````

**Comment by zjsunzone** [comment]
Completion:
1. Verify as expected.
