### ISSUE TITLE
Deploy test nodes (single node, multiple nodes)

### ISSUE THREAD

**Issue by kw805** [PlatONnetwork/PlatON-Go#930]
Hi there,

please note that this is an issue tracker reserved for bug reports and feature requests.

#### System information

PlatON version: `platon version`
OS & Version: Windows/Linux/OSX
Commit hash : (if `develop`)

#### Backtrace

````
[backtrace]
````

**Comment by zjsunzone** [comment]
Completion:

* Single node verification simple contract is no problem.
* Multi-node verification simple contract is no problem.

**Comment by zjsunzone** [comment]
Verification completed without problems.
