### ISSUE TITLE
Transaction sending debugging with different GasLimit

### ISSUE THREAD

**Issue by kw805** [PlatONnetwork/PlatON-Go#955]
Hi there,

please note that this is an issue tracker reserved for bug reports and feature requests.

#### System information

PlatON version: `platon version`
OS & Version: Windows/Linux/OSX
Commit hash : (if `develop`)

#### Backtrace

````
[backtrace]
````

**Comment by zjsunzone** [comment]
Tested with java-sdk and found no problems.

**Comment by zjsunzone** [comment]
Valid for changing gas limit.
