### ISSUE TITLE
Verify after adjusting the block's gasLimit

### ISSUE THREAD

**Issue by kw805** [PlatONnetwork/PlatON-Go#956]
Hi there,

please note that this is an issue tracker reserved for bug reports and feature requests.

#### System information

PlatON version: `platon version`
OS & Version: Windows/Linux/OSX
Commit hash : (if `develop`)

#### Backtrace

````
[backtrace]
````

**Comment by zjsunzone** [comment]
Program: 
1. Send the transaction after increasing the block's GasLimit.
2.GasLimit to increase transactions simultaneously.

**Comment by zjsunzone** [comment]
In Conclusion:
No errors found during testing.
