### ISSUE TITLE
Complete VM UT

### ISSUE THREAD

**Issue by kw805** [PlatONnetwork/PlatON-Go#967]
Hi there,

please note that this is an issue tracker reserved for bug reports and feature requests.

#### System information

PlatON version: `platon version`
OS & Version: Windows/Linux/OSX
Commit hash : (if `develop`)

#### Backtrace

````
[backtrace]
````

**Comment by zjsunzone** [comment]
update #1014

**Comment by zjsunzone** [comment]
update unit test #1013
