### ISSUE TITLE
deploy contract gas used exceed block gas limit

### ISSUE THREAD

**Issue by dugusanfeng** [PlatONnetwork/PlatON-Go#980]
Hi there,
when I use truffle to deploy smart contract, I choose 0.5.13 solidity compile contract and then  deploy,deploy will fail that  the gas used so large to exceed block gas limit, but 0.4.22 solidity compiled contract deploy successfully
#### System information

PlatON version: `platon version`
OS & Version: ubuntu18.04
Commit hash : (if `develop`)

#### Backtrace

````
Transaction: 0x27254d2e5c2134e53b4690adc4250418a492b744d4203edae012441d05b3bb05 exited with an error (status 0) after consuming all gas.
     Please check that the transaction:
     - satisfies all conditions set by Solidity `assert` statements.
     - has enough gas to execute the full transaction.
     - does not trigger an invalid opcode by other means (ex: accessing an array out of bounds)
````

**Comment by zjsunzone** [comment]
The default GasTable is too old. This issue has been resolved. Please refer to: #981
